### ISSUE TITLE
Geocode Returns 0/0 for lat/long when zip code is Included

### ISSUE THREAD

**Issue by xxTheDavexx** [demianrasko/Dynamics-365-Workflow-Tools#10]
When using the geocoding workflow activity, if the postal code is included in the workflow activity parameter "Address," "0" is returned for both latitude and longitude. 

Steps to reproduce:

1. Enter address
![image](https://cloud.githubusercontent.com/assets/5041544/26604134/9503409e-4546-11e7-8a47-4c12283d3cbf.png)
2. Run Workflow without zip code removed from input parameter (see screenshot below). Lat/Long is returned
3. Run Workflow with zip code included. Lat/Long of 0 is returned

------------------------------------

Parameter:	{Address 1: Street 1(Account)} {Address 1: City(Account)} {Address 1: State/Province(Account)} {Address 1: ZIP/Postal Code(Account)} {Address 1: Country/Region(Account)} 
![address including zip code](https://cloud.githubusercontent.com/assets/5041544/26603858/90eb7a04-4545-11e7-9f1f-6ce501ff7142.png)

Parameter:	{Address 1: Street 1(Account)} {Address 1: City(Account)} {Address 1: State/Province(Account)} {Address 1: Country/Region(Account)}
![address sans zip code](https://cloud.githubusercontent.com/assets/5041544/26603859/90edc386-4545-11e7-9167-c8fc1d5b3bca.png)

**Comment by demianrasko** [comment]
Hi xxTheDavexx , 
This is how Works by default Bing Maps.
Right now my request is in this way: 
string UrlRequest = "http://dev.virtualearth.net/REST/v1/Locations/" +
                                 queryString +
                                 "?output=json" +
                                 " &key=" + bingMapsKey;
Where "queryString" is the "Parameter".
I think that you can send the full address without the postal code right now, or test another formats. I think in the future for next releases maybe to create different parameters for address, postal code, city, country, etc..

thanks!
