### ISSUE TITLE
Child Records were not cloned Using "Clone Children"

### ISSUE THREAD

**Issue by LeeSungYao** [demianrasko/Dynamics-365-Workflow-Tools#101]
### Expected behavior and actual behavior.
Expected: Child records should be cloned.
Actual: Child records were not cloned. Workflow completed successfully, green ticks appeared.
### Steps to reproduce the problem (screenshots are really usefull)
A 2 steps workflow:
![image](https://user-images.githubusercontent.com/36430247/45250071-94d3b400-b35e-11e8-9b51-9e2e3d9d85bd.png)

![image](https://user-images.githubusercontent.com/36430247/45250062-33abe080-b35e-11e8-9ce1-c76ace507805.png)

### CRM Version - online/onpremise - WorkflowTools version
CRM Online, latest version of WorkflowTools.

**Comment by rvroemen** [comment]
Hi, I have a similar problem e.g. when cloning a Sales Order with Order Details.
I created an on demand workflow, details are presented in the screen shots added to this ticket.

**Comment by demianrasko** [comment]
Solved today. will be deployed in the next version 1.0.53.0 during this weekend. 
Thanks!

**Comment by meghanareed** [comment]
@demianrasko - what was fixed for this issue? Still having the same problem where no children are being created. My scenario is similar to the original issue. Also, out of curiosity would this work on children activities (with regarding)? Thanks!

**Comment by Joeostr** [comment]
Hi, is 1.0.53 available for 8.2?
