### ISSUE TITLE
Set Process Stage - Out of bounds of array

### ISSUE THREAD

**Issue by sutibun-w** [demianrasko/Dynamics-365-Workflow-Tools#102]
Trying to get a bunch of old opportunities to a new business process and set to the follow up stage, by triggering a two option field and having the workflow run when saved.

### Expected behavior and actual behavior.
Expect behavior would be the ribbon changes to the new busniess flow and progresses to Follow Up

Actual error:
![image](https://user-images.githubusercontent.com/43276924/45564707-27180400-b806-11e8-915e-1e2dc4e0bebf.png)

### Steps to reproduce the problem (screenshots are really usefull)
![image](https://user-images.githubusercontent.com/43276924/45565043-43687080-b807-11e8-8a69-bed32dfbd254.png)

![image](https://user-images.githubusercontent.com/43276924/45564806-73634400-b806-11e8-96d3-422cb46d89a6.png)

### CRM Version - online/onpremise - WorkflowTools version
![image](https://user-images.githubusercontent.com/43276924/45564829-84ac5080-b806-11e8-9c21-61619cb6da52.png)
![image](https://user-images.githubusercontent.com/43276924/45564873-a0aff200-b806-11e8-89ae-b2a7d0744b05.png)

**Comment by demianrasko** [comment]
Solved today. will be deployed in the next version 1.0.53.0 during this weekend. 
Thanks!
