### ISSUE TITLE
"StringFunction" throws System.NullReferenceException when configured attribute is null

### ISSUE THREAD

**Issue by HTBLALeonding** [demianrasko/Dynamics-365-Workflow-Tools#104]
### Expected behavior and actual behavior.
Usage of "StringFunction" should also work if attribute is null.

Currently an exception is thrown:

Error : 500: Internal Server Error: Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.StringFunctions: System.NullReferenceException: Object reference not set to an instance of an object."

### Steps to reproduce the problem (screenshots are really usefull)

1. Add "String Functions" workflow activity to your workflow
2. Open "Properties" dialog
3. Configure an attribute as input text which could be null
4. Start the workflow

Implementing a workflow condition to check if the used attribute is null isn't an option in that case.

### CRM Version - online/onpremise - WorkflowTools version

- Dynamics 365 (8.2.2.112)
- Workflow Tools (1.0.51.1)

**Comment by demianrasko** [comment]
Solved today. will be deployed in the next version 1.0.53.0 during this weekend. 
Thanks!
