### ISSUE TITLE
Error on updating child records through workflow

### ISSUE THREAD

**Issue by PClements64** [demianrasko/Dynamics-365-Workflow-Tools#107]
### Expected behavior and actual behavior.
Have a custom currency to Opportunity relationship and want the exchange rate to be updated on the Opportunity when the Currency Ex Rate is updated.
When running the workflow I get the error "The specified field does not exist in Microsoft Dynamics 365"
### Steps to reproduce the problem (screenshots are really usefull)
Custom currency lookup and ex rate on the Opportunity.  Use update child records utility and update the custom ex rate on the Opportunity from the ex rate on the Currency
### CRM Version - online/onpremise - WorkflowTools version
Version 1710 (9.1.0.294) online

**Comment by brf132** [comment]
You probably typed in the wrong field and/or relationship name into the configuration of that workflow step.  Please try to  double check these items by going directly to the relationship and field name within your solution (or default solution if youre not using solutions)

**Comment by PClements64** [comment]
Thanks - I did and corrected it but forgot to come back and update the thread.
