### ISSUE TITLE
Suggestion - Workflow activity to delete record audit

### ISSUE THREAD

**Issue by AdamGra** [demianrasko/Dynamics-365-Workflow-Tools#108]
When record auditing is enabled you can view the record audit and delete the audit history for that record. 

A workflow activity to do this would be a great addition to the toolkit.

**Comment by demianrasko** [comment]
I didn't used it in the past...but maybe it can be done using this method: https://docs.microsoft.com/en-us/dotnet/api/microsoft.crm.sdk.messages.deleterecordchangehistoryrequest?view=dynamics-general-ce-9
to my backlog ;)

thanks

**Comment by demianrasko** [comment]
Is coming in the next 1.0.54.0 version. :)

**Comment by AdamGra** [comment]
Great news, thanks Demian.

Regards, Adam

Sent from my iPhone

On 18 Dec 2018, at 12:00, Demian Adolfo Raschkovan <notifications@github.com<mailto:notifications@github.com>> wrote:


Is coming in the next 1.0.54.0 version. :)
