### ISSUE TITLE
Problem with CRM 8.2.1 and "delete record" activity

### ISSUE THREAD

**Issue by bluvoMarcel** [demianrasko/Dynamics-365-Workflow-Tools#11]
Hello,

I wanna use the workflow Tools to delete records, in my case automatically generated  appointments.
But the "delete record" activity gives me an error message like this:
"Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.Class.DeleteRecord]
[msdyncrmWorkflowTools (1.0.40.0): Delete Record]

Load CRM Service from context --- OK

Error Message:

Unhandled Exception: Microsoft.Crm.CrmException: Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.Class.DeleteRecord: System.AggregateException: Mindestens ein Fehler ist aufgetreten.
   bei Microsoft.Crm.Sandbox.SandboxCodeUnit.Execute(IExecutionContext context)
   bei Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
"

Does somebody know this Problem and give a solution for this?

Thanks in advance,
Marcel

**Comment by demianrasko** [comment]
Hi bluvoMarcel, 
sorry for the delay in my answer.
I just tested the delete action with Opportunitity and with Appointment and it working fine in my environment with versión 8.2.1.271.

Please find attached the example I used.

thanks
![16-07-2017 22-47-07](https://user-images.githubusercontent.com/18124945/28251231-2ee690ec-6a79-11e7-9efa-e2ce827e7426.png)

**Comment by bluvoMarcel** [comment]
Hi demianrasko,

thanks for your answer. I tried again and got a new error message...
our crm versions are different..my version is 8.2.1.1.176.
I want to delete an announcement through a workflow, but this Messages accurs:

an Unexpected error occured

Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.Class.DeleteRecord]
[msdyncrmWorkflowTools (1.0.40.0): Delete Record]
Load CRM Service from context --- OK


Error Message:

Unhandled Exception: Microsoft.Crm.CrmException: An unexpected error occurred.
   bei Microsoft.Crm.Sandbox.SandboxCodeUnit.Execute(IExecutionContext context)
   bei Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)

The error message is a bit different now but it´s not even better. 
I got security roles like systemadmin and should have enough rights to perform this action.
Maybe i have to wait for the next CU to get it working? 

Best regards,

Marcel

**Comment by demianrasko** [comment]
I Marcel, it still doesn't work?
it should work, based on the details you set here...

**Comment by bluvoMarcel** [comment]
Hallo demianrasko,
last time i tried to delete sth. it did not work. I will try later this day if it works now but i am not very optimistic :/

hmm should i ignore the error message?

Best regards,

Marcel

**Comment by demianrasko** [comment]
Ok, send me the params too to try to test it here.

thanks!

**Comment by bluvoMarcel** [comment]
[Bildschirmausschnitt]



Mit freundlichen Grüßen

Marcel Hötzel

[bluvo AG]<http://www.bluvo.de/>

bluvo AG
Siemensstraße 8-10
40885 Ratingen

T: +49 (2102) 7315 - 208 (Durchwahl)
T: +49 (2102) 7315 - 777 (Hotline)
F: +49 (2102) 7315 – 799
Marcel.Hoetzel@bluvo.de<mailto:Marcel.Hoetzel@bluvo.de>

[fb]<http://www.facebook.com/bluvo> [Twitter] <http://twitter.com/bluvo>  [xing] <http://www.xing.com/companies/bluvoAG>  [youtube] <http://www.youtube.com/user/bluvo>  [linked-in] <http://www.linkedin.com/company/bluvo-ag>

Vorstand


Holger Blumenkamp, Marcus Vogel


Gesellschaftssitz


Ratingen, AG Düsseldorf, HRB 44686


Aufsichtsratsvorsitz


Manfred Vogel


Von: Demian Adolfo Raschkovan [mailto:notifications@github.com]
Gesendet: Donnerstag, 12. Oktober 2017 11:44
An: demianrasko/Dynamics-365-Workflow-Tools <Dynamics-365-Workflow-Tools@noreply.github.com>
Cc: Marcel Hötzel <Marcel.Hoetzel@bluvo.de>; Author <author@noreply.github.com>
Betreff: Re: [demianrasko/Dynamics-365-Workflow-Tools] Problem with CRM 8.2.1 and "delete record" activity (#11)


Ok, send me the params too to try to test it here.

thanks!

**Comment by bluvoMarcel** [comment]
Hallo demianrasko,

i got the same error message…and the workflow status is pending :/

[Bildschirmausschnitt]



Mit freundlichen Grüßen

Marcel Hötzel

[bluvo AG]<http://www.bluvo.de/>

bluvo AG
Siemensstraße 8-10
40885 Ratingen

T: +49 (2102) 7315 - 208 (Durchwahl)
T: +49 (2102) 7315 - 777 (Hotline)
F: +49 (2102) 7315 – 799
Marcel.Hoetzel@bluvo.de<mailto:Marcel.Hoetzel@bluvo.de>

[fb]<http://www.facebook.com/bluvo> [Twitter] <http://twitter.com/bluvo>  [xing] <http://www.xing.com/companies/bluvoAG>  [youtube] <http://www.youtube.com/user/bluvo>  [linked-in] <http://www.linkedin.com/company/bluvo-ag>

Vorstand


Holger Blumenkamp, Marcus Vogel


Gesellschaftssitz


Ratingen, AG Düsseldorf, HRB 44686


Aufsichtsratsvorsitz


Manfred Vogel


Von: Demian Adolfo Raschkovan [mailto:notifications@github.com]
Gesendet: Donnerstag, 12. Oktober 2017 11:44
An: demianrasko/Dynamics-365-Workflow-Tools <Dynamics-365-Workflow-Tools@noreply.github.com>
Cc: Marcel Hötzel <Marcel.Hoetzel@bluvo.de>; Author <author@noreply.github.com>
Betreff: Re: [demianrasko/Dynamics-365-Workflow-Tools] Problem with CRM 8.2.1 and "delete record" activity (#11)


Ok, send me the params too to try to test it here.

thanks!

**Comment by demianrasko** [comment]
I cannot see the screen capture here at github.
just the email text...

**Comment by bluvoMarcel** [comment]
Hallo demianrasko,

now u should see the screenshots. 
The error is just the same :/

**Comment by demianrasko** [comment]
hi, the entity called "Termin" is a custom entity?
I'm trying with different entities and works fine... please also update to the last version: 1.0.41.3

**Comment by demianrasko** [comment]
and also, activate the tracing in the CRM, and see if you can get some traces from there too.
thanks!

**Comment by bluvoMarcel** [comment]
Hi demianrasko,

i will try to update within the next 2 hours. 
"Termin" is just the german Translation for "Announcement"...so it is not a custom entity.
okay i will update soon and try with different entities.

Thx for your Help.

Best regards,
Marcel

**Comment by bluvoMarcel** [comment]
Hello demianrasko,

i´ve tested a lot now... even from different entities like eMails or appointments.
Just getting the same error... trying to trace the errors during the afternoon :/
