### ISSUE TITLE
release 1.0.53.0 doesn't include a managed solution for Dynamics 365 version 8.2

### ISSUE THREAD

**Issue by nathaniel-holder** [demianrasko/Dynamics-365-Workflow-Tools#111]
The previous release (version 1.0.52.1) included different zip files for Dynamics 365 8.0, 8.1, and 8.2.  Is it possible to create one that supports 8.2?  I'm very much looking forward to using the fixed "Clone Child Records" workflow but can't as we're on Dynamics 365 8.2.  Thanks!

**Comment by alwalters** [comment]
It's not allowing me to import for on-premise 9.0 either.  "You can only import solutions with a package version of 9.0 or earlier into this organization."

**Comment by demianrasko** [comment]
Hi, sorry for that. I don't have different environments to test it in onprem and in 8.x. 

I have only online instances to test everything.
This is why during the last weekend I created a branch for version 8, and I will leave it and not support it anymore.
Please try to get the code and compile with the onprem assemblies and try them again. If you find anything I can change, please create a pull request in the project.

Thanks.

**Comment by snugglesftw** [comment]
@demianrasko do you need 8.2 env? I can help you out if you wish.

**Comment by alwalters** [comment]
I've been trying to recompile this for 9.0.2 on-prem (was going to try the newer before going to an 8.2 server), but I'm getting tonnes of namespace does not exist errors, even after fixing all the references.  Not at all sure how else to proceed.  :-(

**Comment by alwalters** [comment]
Heh...never mind.  Was somehow missing one.  Got those resolved, but now getting three warnings - one about a reference comparison, but the two concerning ones are about conflicts between versions of Newtonsoft.json that could not be resolved.  Still poking, though.

**Comment by alwalters** [comment]
Never mind - got the references sorted.  Recompiled for version 9, and changed the solution XML to be for version 9.  However, when importing, now I'm getting the error "The solution package you are importing was generated on Microsoft Dynamics 365 (online). You can’t import it into on-premises or hosted versions of Microsoft Dynamics 365."

This is concerning - I've imported a large number of solutions over the years and never had to download an on-premise-specific version.

**Comment by alwalters** [comment]
I changed the "Generated By" tag in the solution XML to OnPremise instead of CrmLive, and was then able to import.  So very strange...never had issues like that before.  So here's a solution file for v9 on-premise, if it's useful to anyone.  Very curious now if it can be imported into Online, given that change...
[MODv9OnPrem-Dynamics365WorkflowTools_1_0_53_0_ummanaged.zip](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/files/2725102/MODv9OnPrem-Dynamics365WorkflowTools_1_0_53_0_ummanaged.zip)

**Comment by alwalters** [comment]
Unfortunately, this won't compile as-is for version 8.2.  Replaced the references, and getting the error "The type or namespace name 'DeleteRecordChangeHistoryRequest' could not be found".  Looking up the class, it looks like it was added in version 9.  Feel free to put in a pull request about it if you need version 8.2, but I don't know if it will be able to be fulfilled, if that functionality is needed (which presumably it is).
