### ISSUE TITLE
Send Email to Team as CC

### ISSUE THREAD

**Issue by Lubits** [demianrasko/Dynamics-365-Workflow-Tools#114]
### Expected behavior and actual behavior.
The CWA "EmailToTeam" only allows a team to be added to the "To" field, but not the "CC" (or BCC) field. This doesn't require a large change in the code, but could be useful, at least to us.

I'm willing to pick this up, however, I was wondering what your thoughts on this and the implementation details are. There are a few solutions that quickly come to mind for me:

1. Expand the EmailToTeam CWA to include a Team for CC somehow. For example, add a new input argument that accepts a team, and adds that team to the CC. This would mean that both inputs for Teams should not be required arguments anymore, as a user can only want to add a team to the CC or To specifically.

2. Let the user specify when calling EmailToTeam in which field they want to add the team. 

3. Create a new CWA, which is pretty much the same as EmailToTeam, but just adds to the CC instead.

Thoughts?

**Comment by demianrasko** [comment]
Thanks Lubits for your feedback, will add to the backlog
