### ISSUE TITLE
When Attribute1´s value is empty, the activity Query Values failed "The given key was not present in the dictionary"

### ISSUE THREAD

**Issue by jagovier** [demianrasko/Dynamics-365-Workflow-Tools#118]
### Expected behavior and actual behavior.
Expected behavior is the field not contains data.
When Attribute1´s value is empty, the activity Query Values failed "The given key was not present in the dictionary".

### Steps to reproduce the problem (screenshots are really usefull)
The field to query is an string and it´s empty.

Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.QueryValues]
[msdyncrmWorkflowTools (1.0.54.0): Query Values]

Load CRM Service from context --- OK
EntityName: account - Attribute1:mks_emailaddress - Attribute2:name - FilterAttribute1:name - FilterAttribute2:statecode - ValueAttribute1:Unilever España, S.A.  ValueAttribute2:Active
Executing Query...
Executed Query Ok, 1 records ...
Setting results
error: The given key was not present in the dictionary. -    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at msdyncrmWorkflowTools.QueryValues.Execute(CodeActivityContext executionContext)

### CRM Version - online/onpremise - WorkflowTools version
Dynamics 365 v9 Online - Dynamics365WorkflowTools_1_0_54_1

**Comment by demianrasko** [comment]
solved the issue in version 1.0.55.0-
thanks for reporting!
