### ISSUE TITLE
The entity with a name = 'процесобробкизверення' with namemapping = 'Logical' was not found in the MetadataCache

### ISSUE THREAD

**Issue by Samitya** [demianrasko/Dynamics-365-Workflow-Tools#119]
### Expected behavior and actual behavior.
The entity with a name = 'процесобробкизверення' with namemapping = 'Logical' was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=3828389439, MinActiveRowVersion=3828389439

### Steps to reproduce the problem (screenshots are really usefull)
always

### CRM Version - online/onpremise - WorkflowTools version
dynamics 365 online v 9.0

**Comment by Samitya** [comment]
Yes, I get this error on Set Process Stage
I rolled back to the previous version of your plug-in and fixed the error, but more than a hundred processes did not work because of this error :(

If I can give you some testing, write what you need to do.

**Comment by richardlondon** [comment]
Duplicate of #119 
The entity with a name = 'subcontractorapprovalprocess' with namemapping = 'Logical' was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=90427769, MinActiveRowVersion=90427769

I am getting the same error..

[Error #119.txt](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/files/2851861/Error.119.txt)

**Comment by demianrasko** [comment]
Hi guys, sorry for the delay, I have been working a lot during the last couple of months...
I just trying this with 3-4 environments and different processes and is working fine, so I need more details about your issues. 
Can you share with me a solution o maybe screenshots?

thanks!

**Comment by demianrasko** [comment]
Just applied a change today, based on the details shared in other issue: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/issues/124

Please check if version 1.0.55.0 solves your issue. thanks!
