### ISSUE TITLE
Minor issue with documentation on force rollup calculation

### ISSUE THREAD

**Issue by dpoggemann** [demianrasko/Dynamics-365-Workflow-Tools#12]
The documentation says:  
FieldName: The Rollup field schema name of the parent entity.

It should probably state:
FieldName: The Rollup field Name of the parent entity.

This is because if you put in the schema name it fails, you must put in the "Name" of the field.  

Thanks much for the great utils!

Drew

**Comment by demianrasko** [comment]
Thanks dpoggemann !
just updated!

best regards!
