### ISSUE TITLE
No puedo referenciar los hijos del Clon Children

### ISSUE THREAD

**Issue by walmir1998** [demianrasko/Dynamics-365-Workflow-Tools#120]
Hola Estoy utilizando Clone Children con Dinamics 365 9.0 y funciona ok , pero necesito poder referenciar a los hijos , y no tengo forma de hacerlo.
Vi que la acción debería  contener un argumento de salida llamado Cloned Guid , pero he tratado de diversas maneras y ese argumento no puedo utilizarlo ya que nunca aparece.
No se si estoy realizando algo mal ,incluí el Clon Children en una acción , también en un flujo de trabajo , pero luego cuando quiero utilizar la salida , dentro del combo para elegir , nunca aparece la acción realizada, gracias de antemano

![clone](https://user-images.githubusercontent.com/33701938/51562826-797ac880-1e69-11e9-84f9-53d9cbc7b396.png)

 WorkflowTools version 1.0.54.0

**Comment by demianrasko** [comment]
Hola walmir1998 , 
efectivamente era un error en la documentación. El Clone Children no debe devolver ningun Guid, ya que pueden ser varios, no es uno solo.

**Comment by walmir1998** [comment]
Ok gracias por tu respuesta saludos
