### ISSUE TITLE
Check user in Team

### ISSUE THREAD

**Issue by TristanHolt** [demianrasko/Dynamics-365-Workflow-Tools#121]
###When using this plugin, how or what format is the output? I am receiving this error "System.InvalidOperationException: Instance validation error: 'xml - platform' is not a valid value for FetchOutputformat."

**Comment by demianrasko** [comment]
Hi TristanHolt, I just tested it in the last version in online (9.1) and is working fine.
I'm executing a very simple query to find if the user is in the team: 
<fetch version=""1.0"" output-format=""xml - platform"" mapping=""logical"" distinct=""true""><entity name=""team"">
                         <attribute name=""teamid""/>
                         <filter type=""and"">
                          <condition attribute=""teamid"" operator=""eq"" value="""+ teamReference.Id.ToString() + @"""/>
                                </filter>
                                <link-entity name=""teammembership"" from=""teamid"" to=""teamid"" visible=""false"" intersect=""true"">
                                             <link-entity name=""systemuser"" from=""systemuserid"" to=""systemuserid"" alias=""ag"">
                                                        <filter type=""and"">
                                                           <condition attribute=""systemuserid"" operator=""eq""  uitype=""systemuser"" value= """+ userId + @"""/>
                                                                 </filter>
                                                               </link-entity>
                                                             </link-entity>
                                                           </entity></fetch>

Could you please share with me more details about your scenario?

thanks

**Comment by TristanHolt** [comment]
What is this in reference to?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
