### ISSUE TITLE
ynamics-365-Workflow-Tools ( Force Calculate Rollup Field)

### ISSUE THREAD

**Issue by skmancuso** [demianrasko/Dynamics-365-Workflow-Tools#122]
### I want a custom rollup field on the Quote form to refresh as soon as a Quote Line is created/modified.
 
Created a workflow with the entity as Quote Line. The Quote Line entity is where the data is added, and the rollup field is on the Quote record. I tried to implement the steps as described, but I keep getting an error that “The specified field does not exist in Microsoft Dynamics 365.” These are the properties I set…I believe they align with what is suggested. And I have the trigger on the workflow for Quote Line create and field changes which impact the total unit cost value which contribute to the Total Unit Cost value on the Quote. Any suggestions would be appreciated.

### CRM Version - Version 1710 (9.1.0.2034) online - WorkflowTools version 1.0.54.1

![rollup workflow](https://user-images.githubusercontent.com/47248512/52127331-0868ad00-25ef-11e9-83ba-c24eb6aa6e0a.png)

**Comment by demianrasko** [comment]
Hi skmancuso, 
you are not using the parameters correctly. On the first one (FieldName) you should set a string with the schame name of the field, like "new_totalamount", and in this case you are passing a number from a field value, this is not correct.
please check the documentation: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Force%20Calculate%20Rollup%20Field.md

best regards!
