### ISSUE TITLE
Query Values - transform the result in an entity reference

### ISSUE THREAD

**Issue by thomasBID** [demianrasko/Dynamics-365-Workflow-Tools#123]
### Expected behavior and actual behavior.
Hi Demian,

your workflow tools are really great. Thanks.

But I have a question: With "Query Values" I get two text values from the filtered record, let us say for the account entity the GUID and the Account Number. After that I want to use the result as an input value in a lookup field like parent account. But the workflow editor doesn't give me the Query Value Result parameters.

Do you have a solution for that?

### CRM Version - online/onpremise - WorkflowTools version
Version 8.1.0.395 on premise / Workflow Tools 1.0.51.1

**Comment by brichardson2013** [comment]
+1 - I would also like the option of having an entity reference returned as the result of the query.  I could fork the code and write it myself, but any updates in the main branch would overwrite my changes.  Better to do it in the main branch for everyone.

**Comment by demianrasko** [comment]
Thank you two, I'll addedd this to my future backlog.

all the best!

**Comment by Lday75300** [comment]
Hello @demianrasko did you happen to add this feature yet?  I am also trying to capture an account (if it is returned in the filter) and add that account as the Account lookup on a new Contact record in my flow.  However I am not being presented any options when I select the result1 from the query in the Account lookup field.  Thank You
