### ISSUE TITLE
The entity with a name = 'subcontractorapprovalprocess' with namemapping = 'Logical' was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=90449216, MinActiveRowVersion=90449216

### ISSUE THREAD

**Issue by richardlondon** [demianrasko/Dynamics-365-Workflow-Tools#124]
# #119 Looks like the same issue

Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.Class.SetProcessStage]

[msdyncrmWorkflowTools (1.0.54.2): Set Process Stage]

Load CRM Service from context --- OK

ObjectTypeCode=1--ParentId=58952ca8-b32b-e911-a972-000d3a38c0b3

[Dynamics.ChangeBPFandPhase.Execute] Process stage: Approved

[Dynamics.ChangeBPFandPhase.Execute] Fetching the requested Stage.

Starting the update

Starting the update2

Error Message:

Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: The entity with a name = 'subcontractorapprovalprocess' with namemapping = 'Logical' was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=90449216, MinActiveRowVersion=90449216

   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)

   at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass24_0.<Execute>b__0()

   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)

   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)

   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)

   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePluginContainer.Execute(IServiceProvider serviceProvider)

   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)

-- End stack trace --
![image](https://user-images.githubusercontent.com/45997025/52622983-0f22da00-2ea3-11e9-9804-e6c32ad4c3a7.png)

### CRM Version - online/onpremise - WorkflowTools version
msdyncrmWorkflowTools (1.0.54.2): Set Process Stage]
CRM 9.0

**Comment by wingzeroaa** [comment]
save is here.
it looks the custom workflow code, does not get entity name correctly.

**Comment by Robimbrie** [comment]
Hey All,

We experienced the same issue when we upgraded the managed solution to the latest msdyncrmWorkflowTools (1.0.54.2).

I did some digging and fixed the bug in our own deployment, as it was not getting the logical name correctly of the underlying entity for the Business Process Flow (workflow)

The fix is below if you can please add it to the code base, please test it too, and possibly create a new minor release.

The fix is in the class: msdyncrmWorkflowTools.**SetProcessStage.cs** starting at line 109


            // Declare variables to store values returned in response
            Entity activeProcessInstance = null;
            Guid _processOpp1Id = Guid.Empty;
            string _procInstanceLogicalName = "";
            if (procOpp1Resp.Processes.Entities.Count > 0)
            {
                activeProcessInstance = procOpp1Resp.Processes.Entities[0]; // First record is the active process instance
                _processOpp1Id = activeProcessInstance.Id; // Id of the active process instance, which will be used
                                                           // later to retrieve the active path of the process instance

                Console.WriteLine("Current active process instance for the Opportunity record: '{0}'", activeProcessInstance["name"].ToString());
                
                // Get the BPF underlying entity logical name
                var uniqueProcessNameAttribute = "uniquename";
                var processEntity = objCommon.service.Retrieve("workflow", process.Id, new ColumnSet(uniqueProcessNameAttribute));
                _procInstanceLogicalName = processEntity.Attributes[uniqueProcessNameAttribute].ToString();

                //_procInstanceLogicalName = activeProcessInstance["name"].ToString().Replace(" ", string.Empty).ToLower(); // TO BE REMOVED: Incorrect as it only gets the display name.
            }
            else
            {
                Console.WriteLine("No process instances found for the opportunity record; aborting the sample.");
                Environment.Exit(1);
            }

**Comment by jagmann1** [comment]
This has actually been a problem since msdyncrmWorkflowTools (1.0.54.1). It would be great if that could be fixed so we dont need to create an own solution for this issue using the code described above?

**Comment by demianrasko** [comment]
Thanks Robimbrie, just applied your changes to the las version 1.0.55.0
