### ISSUE TITLE
Question: Remove Whitespaces from phone number with string fucntions

### ISSUE THREAD

**Issue by joshua-lehmann** [demianrasko/Dynamics-365-Workflow-Tools#125]
I would like to use your Workflow Tools to remove whitespaces from phone numbers, for example I have
041 111 22 33 and would like to get 0411112233. 
I tried with the a space in the replcae old value and nothing in the new value but it did not work. How can I replace all spaces with nothing, using your string functions?

Thanks for the help!

**Comment by demianrasko** [comment]
Thanks joshua-lehmann!
I just addedd in the String Functions a new Output parameter called "Without Spaces" to cover your requirement.

hope this helps!

**Comment by joshua-lehmann** [comment]
Thanks a lot for your effort! I will try and test it as soon as I can!
