### ISSUE TITLE
Could not load file or assembly Newtonsoft.Json

### ISSUE THREAD

**Issue by radoslavy** [demianrasko/Dynamics-365-Workflow-Tools#126]
Hi, 
We have this problem with Json Parser:

An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.JsonParser: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

msdyncrmWorkflowTools (1.0.54.2):Json Parser

**Comment by demianrasko** [comment]
This is an issue because now we cannot use this external class anymore, actually I think It was unsupported. I need to find how to do it, because using DataContractJsonSerializer I think I cannot get a Dynamics object to be serialized...

**Comment by StefanS365** [comment]
Hi Demian,
I'm running into this issue as well. Hope you'll able to fix it though. Found this blog post bij inogic claiming you should be able tot serialize Dynamics objects with DataContractJsonSerializer:
https://www.inogic.com/blog/2016/10/working-with-json-objects-in-dynamics-crm-plugins/

**Comment by StefanS365** [comment]
Hi Demian,
Mike Factorial create the custom workflow action Webhook – Get Value From Json as part of the Workflow Elements project of Aiden Kaskela. I guess you just have to copy the code ;-)
Blog post:
https://mikefactorial.com/2019/08/29/flow-everything-calling-synchronous-flows-from-cds-and-d365/
GitHub-project:
https://github.com/akaskela/WorkflowElements/releases

**Comment by demianrasko** [comment]
Thanks StefanS365 for the recomendation. I just used the same workaround. Instead of loading the Newtosoft library from Nuget, I get the source code classes and included in the assembly. Now is working fine again ;)
