### ISSUE TITLE
Can Not Import New Version To Dynamics 365 v8.2 On-Premise

### ISSUE THREAD

**Issue by payamiii** [demianrasko/Dynamics-365-Workflow-Tools#127]
Hi, I Used your old version and when i check your project page at GitHub i saw that you have been released new version and that is  1.0.54.2. we use dynamics 365 on-premise v8.2 and when i import your solution on my CRM it shows to me an error that is: 

> You can only import solutions with a package version of 8.2 or earlier into this organization. Also, you can't import any solutions into this organization that were exported from Microsoft Dynamics 365 2011 or earlier.

please help me to solve this problem because i use many workflow step from your solution.

![github](https://user-images.githubusercontent.com/20769601/53696295-ccd22600-3dda-11e9-8a17-b3625de725ef.jpg)

**Comment by miklemiracle** [comment]
The very same thing happened with me today:
> Microsoft Dynamics 365
> Version 1612 (8.2.2.112) (database 8.2.2.112) (On-Premise)

Any ideas for QF? Or we should wait for the new release

**Comment by demianrasko** [comment]
Hi guys! the last release supported to 8.x versions is the 1.0.52.1.
Right now I don't have any 8.x onprem environment to test everything and support the new stuff, so you can get the source code of the new things and develop the 8.x version by your own.
If you want to share it, create a branch for it.

thanks!

**Comment by bandeh** [comment]
Hi

Is not supported on 9 on premise?
You can only import solutions with a package version of 9.0 or earlier into this organization. Also, you can't import any solutions into this organization that were exported from Microsoft Dynamics 365 2011 or earlier.

Thanks
