### ISSUE TITLE
Runtime Error on "Send Email From Template To Users In Role": "There is no active transaction."

### ISSUE THREAD

**Issue by Boydski** [demianrasko/Dynamics-365-Workflow-Tools#128]
An error is thrown when workflow is triggered. Please see attached log file.

Workflow works fine with email template when driven from built-in D365 email functionality.

D365 Version 1710 (9.1.0.2648) online

D365 Workflow Tools v1.0.54.2

[ErrorDetails.txt](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/files/2962151/ErrorDetails.txt)

**Comment by demianrasko** [comment]
Hi Boydski, 
I need more details to try to reproduce what's happening.
Sometimes this happend when you are trying to execute this in a sync workflow, please try an Async one, or share me more details about your scenario.

thanks!
