### ISSUE TITLE
Set Process Stage Security Issue

### ISSUE THREAD

**Issue by Ingo-Louw** [demianrasko/Dynamics-365-Workflow-Tools#129]
### Expected behavior and actual behavior.

I am getting the following error when saving a case. The stage is not moving as expected. I am using a systems administrator account. I am using Dynamics 365 online Version 1710 (9.1.0.3451) online.

An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.Class.SetProcessStage: System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.SecurityPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed. If you contact support, please provide the technical details.

**Comment by Ingo-Louw** [comment]
I am using a realtime workflow.

**Comment by demianrasko** [comment]
Please download the error text, and maybe with that we can identify the missing privilegeID.
In any case, I'm uploading a bug fixed on this action on the version 1.0.55.0, that maybe could help.

thanks!

**Comment by Ingo-Louw** [comment]
Still getting a permission error. Below is the Error text.

Unhandled exception: 
Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]
Message: An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute):  msdyncrmWorkflowTools.Class.SetProcessStage: System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.SecurityPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>cd011a4e-57a4-48b1-9310-95e1f9548023</ActivityId>
  <ErrorCode>-2147220891</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
    <KeyValuePairOfstringanyType>
      <d2p1:key>OperationStatus</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">0</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>SubErrorCode</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">-2146233088</d2p1:value>
    </KeyValuePairOfstringanyType>
  </ErrorDetails>
  <Message>An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute):  msdyncrmWorkflowTools.Class.SetProcessStage: System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.SecurityPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.</Message>
  <Timestamp>2019-05-02T08:07:13.8563834Z</Timestamp>
  <ExceptionRetriable>false</ExceptionRetriable>
  <ExceptionSource i:nil="true" />
  <InnerFault i:nil="true" />
  <OriginalException i:nil="true" />
  <TraceText>

[Microsoft.Crm.ObjectModel: Microsoft.Crm.ObjectModel.SyncWorkflowExecutionPlugin]
[b64e93fa-b06c-e911-a97d-000d3a2bc547: ]
Entered Microsoft.Dynamics.Service.Plugins.PreOperationIncidentCreate.Execute(), Correlation Id: 5f0734e5-b9b7-4ee1-9b99-c82b1270b012, Initiating User: 2b92d76d-61ae-e711-8110-5065f38be4f1
Exiting Microsoft.Dynamics.Service.Plugins.PreOperationIncidentCreate.Execute(), Correlation Id: 5f0734e5-b9b7-4ee1-9b99-c82b1270b012, Initiating User: 2b92d76d-61ae-e711-8110-5065f38be4f1
Entered Microsoft.Dynamics.Service.Plugins.PreOperationIncidentCreateEntitlement.Execute(), Correlation Id: 5f0734e5-b9b7-4ee1-9b99-c82b1270b012, Initiating User: 2b92d76d-61ae-e711-8110-5065f38be4f1
Exiting Microsoft.Dynamics.Service.Plugins.PreOperationIncidentCreateEntitlement.Execute(), Correlation Id: 5f0734e5-b9b7-4ee1-9b99-c82b1270b012, Initiating User: 2b92d76d-61ae-e711-8110-5065f38be4f1
Entered Microsoft.Dynamics.Service.Plugins.PostOperationIncidentCreateEntitlement.Execute(), Correlation Id: 5f0734e5-b9b7-4ee1-9b99-c82b1270b012, Initiating User: 2b92d76d-61ae-e711-8110-5065f38be4f1
Exiting Microsoft.Dynamics.Service.Plugins.PostOperationIncidentCreateEntitlement.Execute(), Correlation Id: 5f0734e5-b9b7-4ee1-9b99-c82b1270b012, Initiating User: 2b92d76d-61ae-e711-8110-5065f38be4f1
Starting sync workflow 'Set Latitude and Longitude', Id: 0f78380a-571e-e911-a97d-000d3a22ca8c
Entering UpdateStep1_step: 
Sync workflow 'Set Latitude and Longitude' completed successfully
Starting sync workflow 'GEO Code  Latitude and Longitude', Id: b1840f1f-345c-e911-a97c-000d3a2bc547
Entering ConditionStep3_step: Get Address Fields
Entering InvokeSdkMessageStep5_step: Get Address
Entering UpdateStep6_step: 
Entering ConditionBranchStep4_step: 
Sync workflow 'GEO Code  Latitude and Longitude' completed successfully
Starting sync workflow 'MetroGrid Move to Assignment or Acknowledgement Workflow', Id: 9c4e93fa-b06c-e911-a97d-000d3a2bc547
Entering ConditionStep1_step: Is Category and Sub-Category Other
Entering CustomActivityStep8_step: Move to Acknowledgement Stage
Sync workflow 'MetroGrid Move to Assignment or Acknowledgement Workflow' terminated with error 'An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute):  msdyncrmWorkflowTools.Class.SetProcessStage: System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.SecurityPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.'

</TraceText>
</OrganizationServiceFault>

**Comment by demianrasko** [comment]
Hi Ingo-Louw, I think you are having this issue on a Synch Plugin Assembly, maybe this triggers when you use the set stage action. 

please try to deactivate all plugins and test it again. if this works, you should have something to check in the other plugins you have in than entity.

thanks!
