### ISSUE TITLE
e-Mail to Team e-mail remain in draft status

### ISSUE THREAD

**Issue by mtonarelli** [demianrasko/Dynamics-365-Workflow-Tools#13]
I use Dynamics 365 Workflow Tools the custom workflow activities , very great job.
Many compliments
Just one question, when i use the activity e-Mail to Team i prepare a generic e-mail with the activity Create e-Mail e then use the Dynamics 365 Workflow Tools activity e-Mail to Team. When the workflow run why the generated e-Mail remain in the draft status e don't send to Team members.

Thank You
Marcello Tonarelli, Florence, Italy

**Comment by demianrasko** [comment]
Hi Marcello, thanks for following.
If the email stays in draft, maybe is because you have any issue in the email configuration.Did you try to send a manual email and it worked fine?
if yes, please try to see if you have any log error to send to me.

thanks!

**Comment by demianrasko** [comment]
Hi Marcello, 
Any update about this?
thanks
