### ISSUE TITLE
Clone Children produces duplicates

### ISSUE THREAD

**Issue by miklemiracle** [demianrasko/Dynamics-365-Workflow-Tools#130]
### Expected behaviour and actual behaviour.
We have a simple custom solution for making Questionnaires:

1. Parent Questionnaire = template
1. Child Questionnaire = actual questionnaire
1. Questions of Parent Questionnaire = questions template
1. Questions of Child Questionnaire = actual questions

So we made a WF, cloning Questions of Parent Questionnaire for every Child Questionnaire created, making Questions of Child Questionnaire

Occasionally, duplicates of Questions of Child Questionnaire are started to occur. There is no system in duplicated creation — 1 question can be duplicated 3 times in 1st Questionnaire, 2 times in 2nd Questionnaire and no duplicated in 3rd

I can provide additional screenshots of WF and duplicated data, but they are in Russian. Don't sure it'll be useful

### CRM Version - online/on-premise - WorkflowTools version
Dynamics 8.2.2.112 On-Prem
msdyncrmWorkflowTools (1.0.52.1):Clone Children

**Comment by demianrasko** [comment]
sorry miklemiracle, I think I don't understand all the details you shared.
If this is an ocasional issue, and almos all the time works fine, we need to identify what happend on this situations, what could be changed or modified.
I don't have an onprem environment where to test this in any case, so I think the best way is to try to debug it.

best regards.
