### ISSUE TITLE
Cannot Import Solution // Dynamics 365 v9

### ISSUE THREAD

**Issue by geremysantos** [demianrasko/Dynamics-365-Workflow-Tools#131]
Receiving an error upon solution import for both managed and unmanaged solution.
Generic errors on types 'Plugin Assembly' and 'Solution'.
![image](https://user-images.githubusercontent.com/49735140/56325282-89cbd800-6126-11e9-892e-d272396cc7d7.png)

1. Download the zip file (managed or unmanaged)
2. Attempt to import zip file (managed or unmanaged)
3. Received import failure notification

Dynamics 365 v9.1
Dynamics 365 Workflow Tools Solution 1.0.54.2

**Comment by demianrasko** [comment]
Are you importing this to a CDS "clean" environment? maybe this fails because there are some actions that need some special entities installed by Dynamics 365 App Solutions. please read the "NOTE ABOUT CDS" in the main page
