### ISSUE TITLE
Issue with Get Record ID and Rollup Function

### ISSUE THREAD

**Issue by vaanib** [demianrasko/Dynamics-365-Workflow-Tools#132]
### Expected behavior and actual behavior.
Getting Error for Rollup Function when we are getting the PARENT_GUID from Get Record ID step
### Steps to reproduce the problem (screenshots are really usefull)
First use GetRecordID as a First Step
In the next step use Rollup Function and Pass the RecordID from First Step as a parameter
### CRM Version - online/onpremise - WorkflowTools version
CRM Online d365 9.1
[ErrorDetails (1).txt](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/files/3141139/ErrorDetails.1.txt)

**Comment by demianrasko** [comment]
Hi, 
first of all, check if you are replacing correctly the Parent_GUID with the ID you retrieved in previous step.
Second, check if the first attribute of the FetchXML is a number, this is the number I use for calculations, and must to be a number.
Third, I uploading a new fix in this action, so please try with the new one if this works.

Thanks!
