### ISSUE TITLE
Srring function - Capitalize text

### ISSUE THREAD

**Issue by AbilioRLemos** [demianrasko/Dynamics-365-Workflow-Tools#133]
Hi Demian

I'm unable to make the Capitalize Text String function work properly when the field value is written in uppercase letters. It works if ther word is written in any other way except if it is uppercase 

Eg:
test test - works perfectly
tEst - works perfectly
test TEST - change first word but not the second one
TEST - don't ghange anything

Could you please give any clue to properly configure the function.

Thank you for you support

Best regards
Abílio Lemos

**Comment by demianrasko** [comment]
Hi Abilio, 
Capitalize text is base on the Input parameter called "Capitalize All Words".
If this is true then we call ToTitleCase method (https://docs.microsoft.com/es-es/dotnet/api/system.globalization.textinfo.totitlecase?view=netframework-4.8) .
If is false, then capitalize only the first letter of the text.

hope this helps.

Demian.
