### ISSUE TITLE
CE 365 version compatibilities

### ISSUE THREAD

**Issue by CryogenicPotato** [demianrasko/Dynamics-365-Workflow-Tools#135]
Hello,

how do I know what is the latest version that supports our CRM OnPremise environment Version 1612 (9.0.3.7) I can't seem to find the supported CRM version for each package.

Best regards

**Comment by demianrasko** [comment]
Hi CryogenicPotato, 
sorry for that, I don't have anymore onprem environments to test everything now, so I don't supported anymore. You can open a custom fork or branch, and maintain by your own.

thanks!

**Comment by snugglesftw** [comment]
@demianrasko  can you not download trial version of the on prem crm?
