### ISSUE TITLE
Clone Child records not working

### ISSUE THREAD

**Issue by johnnoball** [demianrasko/Dynamics-365-Workflow-Tools#136]
### Expected behavior and actual behavior.
Clone Parent (Account Plan)- Works Fine
Next step to clone Child records (Account Plan Competitor) not working

I have checked https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Clone%20Children.md to try to ensure I have followed the instructions

### Steps to reproduce the problem (screenshots are really usefull)

![AccountPlanWorkflow](https://user-images.githubusercontent.com/12562630/57635947-222b7000-75a0-11e9-8567-7ca708006bfa.PNG)

![AccPlanClone](https://user-images.githubusercontent.com/12562630/57635972-2bb4d800-75a0-11e9-8e21-e76898ae1831.PNG)

![CloneCompetitorChild](https://user-images.githubusercontent.com/12562630/57636002-3a02f400-75a0-11e9-91b7-ad6a20c30d48.PNG)

### CRM Version - online/onpremise - WorkflowTools version
D365 Customer Experience Version 1710 (9.1.0.4824) online 
Workflow tools 1.0.54.2

**Comment by johnnoball** [comment]
It doesn't look as if the Clone GUID function is receiving a value, and so when then parameter is being passed to the clone child function nothing is happening.


I updated my workflow to write Cloned GUID back to a memo field on the Parent Record to check the value, nothing gets written

**Comment by johnnoball** [comment]
So, I an now getting a return from Clone GUID, and I have constructed a URL for the Target URL parameter.  I also populate the constructed 

URL to Parent Record from which I want to clone the child records

Clone Children is still not working

![ConstructedURL](https://user-images.githubusercontent.com/12562630/57691867-38d3d480-763d-11e9-97ff-4c9276d442b0.png)

The constructed URL updated on the parent opens up the cloned record when passed into a browser, but Clone Children still does nothing.  I am fairly sure all of the parameters required are correct

Constructed URL for Target URL:   https://mycrmorg-crm-dev.crm11.dynamics.com/main.aspx?etc=10232&extraqs=formid%3ded3dffae-d9f8-4225-a764-650e0eeea1ed&id=%7b46ae259a-3376-e911-a9a0-002248004a4b%7d&pagetype=entityrecord

**Comment by zeusfaber** [comment]
I have **exact** the same issue

**Comment by zeusfaber** [comment]
I have **_exact_** same issue.

**Comment by demianrasko** [comment]
I can't reproduce the issue, are you able to share with me a solution with the issue? 
thanks!

**Comment by jcfetzer** [comment]
I am also experiencing the same issue with the child clone and using the clone GUID.  

@demianrasko can you please advise on what should go into the "Target Record URL" param?  ie, how to compose the URL with the clone GUID?  Maybe a screen cap of how you are doing it successfully?  Maybe you are using an intermediary step between the Parent Clone and the Child Clone?  Whose output is then used to set the child clone target record url?

Many thanks!

**Comment by demianrasko** [comment]
Hi jcfetzer, 
Note: The Parent Record URL, is a standard feature of Dynamics CRM, taht contains the full URL of a record. In this URL you have the entity type, and the record GUID. Right now this is the only way we have to pass a "Dynamic" EntityReference (with not hard coding an entity type) to Workflows Activities. If you pass this string URL as a parameter, in the Workflow Activity you can retrieve this entity Reference.

**Comment by ACFlorianD** [comment]
Hi, Any update? I have the same problem with Target Url.

**Comment by MartinMcGlade** [comment]
Hi, Im facing the same issue of having the Target Record Url not being a dynamic value.
Ive managed to hardcode the Target Record Url and get it to work, but im looking for a solution where I dont need to update each environment it is deployed to.

https://<yourorg>.crm.dynamics.com/main.aspx?etc=3&id={Cloned Guid(Clone Opportunity)}

**Comment by kimxaviernati-alm** [comment]
Hi,

I have the same question, how do you set the Target Record URL? Where do I get the Target Record URL? Plugging in just the Cloned GUID doesn't work. Thanks in advance.

**Comment by davephilips** [comment]
Hi everyone, 
I'm using it on version 1.0.52. apparently, the issue is not on the target url, but on the "fields to ignore" field. leaving it empty (or filling it with a space) was throwing an unhandled exception. remember to use the New Parent Field Name (and not the Old) to identify the field on the child to overwrite with the new parent.
