### ISSUE TITLE
Clone child tasks?

### ISSUE THREAD

**Issue by Rayne2244** [demianrasko/Dynamics-365-Workflow-Tools#137]
I should be able to close task from a parent using regardingobjectid 

1. I am using the source and record URL as intended.
2. I am use the parent field as regardingobjectid
3. I am using the relationship name between a change request and task mcs_smtchangerequest_Tasks

8.2

**Comment by demianrasko** [comment]
Hi Rayne2244, not sure to understand what you need.
could you please share screenshots ?

thanks!
