### ISSUE TITLE
Rollup Functions - min always returns zero?

### ISSUE THREAD

**Issue by petertschmidt17** [demianrasko/Dynamics-365-Workflow-Tools#139]
### Expected behavior and actual behavior.
I have a custom entity with a number of custom activities "regarding" that custom entity. The activities include a custom whole number field to specify their sequence. The MIN function always returns zero, even when all child activities are numbered one and above. The AVERAGE, COUNT, MAX and SUM functions all return the correct values. I also tested with a currency field and the MIN function always returned zero.

### CRM Version - online/onpremise - WorkflowTools version
1710 (9.1.0.4441) online

**Comment by SnippetsUnlimited** [comment]
The Roll up function needs rework. It does not return min if minimum value or more than zero and maximum value is less than zero.

The code should accept the very first "number" as _min or _max and work there on, to compare rest of the "numbers" in the list to be aggregated. Also getting the "number" from the list of records can be moved to another function for clarity.

**Comment by SnippetsUnlimited** [comment]
I have created a pull request for the fix. Lets see when its pulled in.

**Comment by demianrasko** [comment]
I just merge your pull request with this fixed today.
Thanks!
