### ISSUE TITLE
Working with Update Child Records

### ISSUE THREAD

**Issue by fvakiliev** [demianrasko/Dynamics-365-Workflow-Tools#14]
Hi Demian!

I try to change **Property Instance** (dynamicpropertyinstance) field values (e.g. valuetext) from workflow on **Order Product** (salesorderdetail) using **Update Child Records** step.

...and get error:

> Plugin Trace:
> 
> [msdyncrmWorkflowTools: msdyncrmWorkflowTools.UpdateChildRecords]
> [msdyncrmWorkflowTools (1.0.40.0): Update Child Records]
> Load CRM Service from context --- OK
> ObjectTypeCode=1089--ParentId=6549c1de-156a-e711-80d9-005056b37a5c
> RelationshipName=SalesOrderDetail_Dynamicpropertyinstance--_ParentFieldNameToUpdate=
> _ValueToSet=Text--_ChildFieldNameToUpdate=valuestring
> 
> Error Message:
> 
> Unhandled Exception: Microsoft.Crm.CrmException: An unexpected error occurred.
>    at Microsoft.Crm.Sandbox.SandboxCodeUnit.Execute(IExecutionContext context)
>    at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
> 
Using **Parent Field Name** options instead **Value to Set** throws the same error.
Clarify please, what am I doing wrong.

Also, it will be nice if the filter options for child records will be provided (aka FetchXML).

Best regards!
Firat Vakiliev

**Comment by demianrasko** [comment]
Hi Firat, thanks for youe email.
with your scenario it's required to make an "update" on the dynamicpropertyinstance entity. But this entity doesn't Support the updateRequest Message, and I need to implement the UpdateProductPropertiesRequest message instead, but there is another issue, that depending on the property type, the update is another field (valuedecimal, valuedouble, valueinteger,valuestring...)

Right now I don't Support this kind of updates, maybe in future I'll implement anpther action for this feature. I'll add it to the Product Properties Update.

Thanks for your contact.

Demian.
