### ISSUE TITLE
Error importing solution:  The entity list doesn't exist. Property: Marketing List

### ISSUE THREAD

**Issue by rtebar** [demianrasko/Dynamics-365-Workflow-Tools#142]
Hi Demian! 

### Expected behavior and actual behavior.
I cannot import the solution into a new environment v9.1.0.5825. I have tried on two different environments and it happens the same. I get the error shown below. I have also attached the import logs with all details.

Microsoft.Crm.Tools.ImportExportPublish.ImportPluginTypesException: Plugin Types import: FAILURE. Error: Plugin: msdyncrmWorkflowTools, Version=1.0.55.0, Culture=neutral, PublicKeyToken=416e876b9bee261e of PluginTypeName: Microsoft.Crm.Entities.PluginType caused an exception.: Invalid CrmReferenceTarget: The entity list doesn't exist. Property: Marketing List ---> Microsoft.Crm.CrmException: Invalid CrmReferenceTarget: The entity list doesn't exist. Property: Marketing List    at Microsoft.Crm.ObjectModel.WorkflowActivityValidator.ValidateNet4SpecialTypeAttribute(Type propertyType, String propertyName, String[] activityParameterTargets, String[] attributeTargets, String attributeName, DynamicMetadataCache metadata)    at Microsoft.Crm.ObjectModel.WorkflowSandboxCustomActivityValidator.ValidateNet4SpecialTypeAttribute(CustomActivityParameterInfo customActivityParameterInfo, DynamicMetadataCache metadata)    at Microsoft.Crm.ObjectModel.WorkflowSandboxCustomActivityValidator.ValidateInternal()    at Microsoft.Crm.ObjectModel.PluginValidatorBase.Validate()    at Microsoft.Crm.ObjectModel.PluginTypeValidator.ValidateInternal()    at Microsoft.Crm.ObjectModel.PluginValidatorBase.Validate()    at Microsoft.Crm.ObjectModel.PluginTypeServiceInternal`1.Create(IBusinessEntity entity, ExecutionContext context)    at Microsoft.Crm.Tools.ImportExportPublish.ImportPluginAssemblyHandler.ImportItem()    --- End of inner exception stack trace ---    at Microsoft.Crm.Tools.ImportExportPublish.ImportPluginAssemblyHandler.ImportItem()

[importlog_Dynamics365WorkflowTools_1_0_55_0.zip](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/files/3328557/importlog_Dynamics365WorkflowTools_1_0_55_0.zip)

### Steps to reproduce the problem (screenshots are really usefull)
- Create a new trial environment with PowerApps Plan 2 license
- The environment shouldn't have any solution, just the basic one "Common Data Service Default Solution"
- Import Dynamics-365-Workflow-Tools solucion version 1.0.55.0

### CRM Version - online/onpremise - WorkflowTools version
- Online
- PowerApps Plan 2
- v9.1.0.5825
- Environment with no solutions, just the basic one "Common Data Service Default Solution"

**Comment by demianrasko** [comment]
Hi Ramon, that's correct.
I need to separate in two solutions, one for CDS and other complete.
Will do in next 1.0.56.0 version

**Comment by DavesTechTips** [comment]
Thanks for the great solution!

One question: When will the solution for Dataverse without Dynamics be ready? This is required because of the Marketing List that is currently a dependency, that breaks the Solution import on Dataverse environments without dynamics.

**Comment by FeAsen-Sensei** [comment]
Hi Demian,

Any updates about having a separate solution for CDS? Or are there any workarounds we can do to get it installed into a CDS?
