### ISSUE TITLE
Update Child Record with Partylist data type

### ISSUE THREAD

**Issue by JohnF84** [demianrasko/Dynamics-365-Workflow-Tools#145]
Hi Demian,

I have a question about the 'Update Child Records' tool. I have created a custom activity entity which is updated via a workflow using the 'Update Child Records'. All fields are updating correctly except for one. The 'Resources' field(Data Type = Partylist) is failing to update. 

Relationships name, parent/child name and Parent Record URL are all matching.

It is failing with the following error message:

'A record with these values already exists. A duplicate record cannot be created. Select one or more unique values and try again.'

### Expected behavior and actual behavior.
Child field should update when parent field has been changed. Child field is not updating

### CRM Version - Version 1710 (9.1.0.6628) online -

 WorkflowTools version 1.0.54.2

**Comment by demianrasko** [comment]
Hi JohnF84, 
Could you please share me more details like screenshots or maybe the solution?

thanks!
