### ISSUE TITLE
String function Regular Expression only returns first match

### ISSUE THREAD

**Issue by franglais** [demianrasko/Dynamics-365-Workflow-Tools#146]
### Expected behavior and actual behavior.
Wrapping the Regular Expression with **/[]/g** causes the Regex to not return any results.

### Steps to reproduce the problem (screenshots are really usefull)
Create a workflow with the step of taking a text string and formatting against the regex **/[a-zA-Z0-9]+/g** returns no value

![image](https://user-images.githubusercontent.com/23264148/62478670-86c32900-b7a3-11e9-9a80-4512ceaa4759.png)

I am wrapping with **/[]/g** because the regex expression itself only returns the first matched item if I use **[a-zA-Z0-9]+**

So if I use **[a-zA-Z0-9]+** and put in the input of **Micr@o-soft** I get the result of **Micr** (the first found regex portion)

So when I wrap this as **/[a-zA-Z0-9]+/g** I would expect the output of **Microsoft** but get no result.

### CRM Version - online/onpremise - WorkflowTools version
D365 Online - 1.0.56.0

**Comment by demianrasko** [comment]
hi franglais, 
my code right now is doing this for reg expression:

Regex regex = new Regex(regularExpression);
                Match match = regex.Match(inputText);
                if (match.Success)
                {
                    regexSuccess = true;
                    regexText = match.Value;
                }

best regards.
