### ISSUE TITLE
Rollup functions always return zero

### ISSUE THREAD

**Issue by petertschmidt17** [demianrasko/Dynamics-365-Workflow-Tools#147]
This is a follow-up to issue #139. I downloaded build 1.0.56.0 and now I am seeing that all five functions (Average, Count, Max, Min and Sum) always return a zero value. I tried FetchXML using both the {PARENT_GUID} parameter and a hard-coded guid. Previously it was only the Min function that always returned a zero value.

### CRM Version - online/onpremise - WorkflowTools version
CRM Version 1710 (9.1.0.6633) online
Workflow tools version 1.0.56.0

**Comment by franglais** [comment]
Can confirm, this is returning 0 for all sums.

@SnippetsUnlimited not sure what's gone wrong!

**Comment by franglais** [comment]
This seems to be the part of the code that's causing the issue with this. I'm not a coder, but from my understanding of this, it's ONLY going to do any of the sums if the count of objects is less than or equal to zero!

Shouldn't this be >= 0 ?

            decimal _count = 0;
            decimal _sum = 0;
            decimal _min = 0;
            decimal _max = 0;
            decimal _average = 0;
            if (objNumbers.Count <= 0)
            {
                foreach (object obj in objNumbers)
                {
                    _count++;
                    decimal number = this.GetValue(obj);

                    _sum += number;
                    if (number < _min || _count == 1) _min = number;
                    if (number > _max || _count == 1) _max = number;
                }

                
                if (_count > 0)
                {
                    _average = _sum / _count;
                }
            }
            
            this.Count.Set(executionContext, _count);
            this.Sum.Set(executionContext, _sum);
            this.Average.Set(executionContext, _average);
            this.Min.Set(executionContext, _min);
            this.Max.Set(executionContext, _max);

**Comment by SnippetsUnlimited** [comment]
you are correct. this needs to be fixed. The correct condition should be as:

`if (objNumbers.Count <= 0)`

**Comment by SnippetsUnlimited** [comment]
You are correct and this should be fixed. The correction should be as:

`if (objNumbers.Count > 0)`

**Comment by demianrasko** [comment]
Fixed Today. 
Thanks for your feedback!
