### ISSUE TITLE
Clone Children not working.  365 v 1710 (9.1.0.6827) Online

### ISSUE THREAD

**Issue by duffer63** [demianrasko/Dynamics-365-Workflow-Tools#149]
### Expected behavior and actual behavior.
Workflow executed and the parent was cloned.  No children were cloned.  Which version should I be using for below 365 version?

### Steps to reproduce the problem (screenshots are really usefull)
![workflow](https://user-images.githubusercontent.com/54037770/62884366-58de6700-bd04-11e9-9b01-8a9c2412396f.jpg)

![Custom Step](https://user-images.githubusercontent.com/54037770/62884368-5b40c100-bd04-11e9-9653-2317bba3cf30.jpg)

### CRM Version - online/onpremise - WorkflowTools version
v 1710 (9.1.0.6827) Online
Using v56 of the tools.

**Comment by derekfinlinson** [comment]
@duffer63 You actually have to provide the new parent field name for this to work correctly even though it says it's optional.

**Comment by demianrasko** [comment]
Hi duffer63, I think the issue is because on the "Target Record URL" you are passing a GUID, and you must pass the record URL.

thanks!

**Comment by chikhalenakush** [comment]
@demianrasko  Could you please give us example of "Target Record URL" I have searched your complete Reposiotry w.r.t clone child record but could not find relevant example of cloning child Record especially after clone Parent Record. As far as I see clone Record returns Guid. How do we created  "Target Record URL" based on Guid?

It would be really awesome if you could show us example of cloning Parent and child altogether,
