### ISSUE TITLE
Update Child

### ISSUE THREAD

**Issue by bpr-admin** [demianrasko/Dynamics-365-Workflow-Tools#150]
### Expected behavior and actual behavior.
What I want to do: Update the Payment Method picklist(global) in the AP Invoice Entity with the entry from the Account Entity of the same global picklist

Just getting an error
![image](https://user-images.githubusercontent.com/10145036/63190977-0f0bbe80-c02d-11e9-9246-518a357734e5.png)

### Steps to reproduce the problem (screenshots are really usefull)
![image](https://user-images.githubusercontent.com/10145036/63190917-e5529780-c02c-11e9-8e74-2737e09983a2.png)

### CRM Version - online/onpremise - WorkflowTools version
On-Prem Version 8.2.5.4 (1612)

Workflow Tools Version: 1.0.52.1
--

**Comment by demianrasko** [comment]
Hi bpr-admin, 
I don't understund why...but:
in the plugin trac log i see that there is a valur for "_ParentFieldNameToUpdate", but the parameter called "Parent field name" is empty...
the error looks like you put the value "bpr:Paymentmethod" on the parameter "Parent Field Name", and this is why you get that error. you should leave it blank.

thanks!
