### ISSUE TITLE
Solution Failed to Import

### ISSUE THREAD

**Issue by diannemcalpine** [demianrasko/Dynamics-365-Workflow-Tools#155]
### Expected behavior and actual behavior.
I downloaded the zip file, went to Settings>>Solutions, selected 'Import', selected the zip file in the wizard.

### Steps to reproduce the problem (screenshots are really usefull)
Received the following error:
"The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

### CRM Version - online/onpremise - WorkflowTools version
D365 online - Dynamics-365-Workflow-Tools-master 1.0.56.0

**Comment by nufri** [comment]
Same problem for me in CRM 2011

**Comment by demianrasko** [comment]
Hi nufri, 
this version is only available now to online version.

thanks!

**Comment by diannemcalpine** [comment]
Hi Demian,

 

I have the same problem with the online version.

 

Regards,

Dianne

 

Dianne McAlpine
Telephone:  519-770-6667
Email:   <mailto:Dianne@innovantage.ca> dianne@innovantage.ca

**Comment by diannemcalpine** [comment]
Hello Demian,

 

I received the following error when trying to install on an online version:

 

"The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

 

Any suggestions?

 

Regards,

Dianne

 

Dianne McAlpine
Telephone:  519-770-6667
Email:   <mailto:Dianne@innovantage.ca> dianne@innovantage.ca
