### ISSUE TITLE
Email To Team - hyperlinks

### ISSUE THREAD

**Issue by VeroslavOlic** [demianrasko/Dynamics-365-Workflow-Tools#156]
Hi,

Does "Email To Team" feature support hyperlinks in the e-mail body? In my case not - the hyperlink is not "clickable" in the e-mail CRM record.

CRM D365 Version 1710 (9.1.0.8425) online
msdyncrmWorkflowTools (1.0.51.1)

Thank you.
Veroslav

**Comment by demianrasko** [comment]
Hi VeroslavOlic, 
this is not a feature regarding the Workflow Tools, is just a workflow standard feature, you can add any thing the email body creation allows to you.

thanks!

**Comment by VeroslavOlic** [comment]
Thanks for your comment.
