### ISSUE TITLE
Update Version

### ISSUE THREAD

**Issue by GlennJonesEC** [demianrasko/Dynamics-365-Workflow-Tools#157]
We have a previous version (1.0.52.1) of msdyncrmWorkflowTools deployed to our environment as a managed solution.

Does anyone have any details on how to update Dynamics to the current version?

**Comment by derekfinlinson** [comment]
@GlennJonesEC You can just download the newest version and install over the top of old version.

**Comment by franglais** [comment]
Just be aware that there seems to be a bug with the rollup functions at the moment, so would be worth checking to make sure you're not using those!

**Comment by GlennJonesEC** [comment]
I did not notice the Managed version of the package...   Will go clean my glasses.  Thank you for your replies.
