### ISSUE TITLE
how does dynamic crm 356 9.0 use this solution?

### ISSUE THREAD

**Issue by xiefengdaxia** [demianrasko/Dynamics-365-Workflow-Tools#158]
### Expected behavior and actual behavior.
when i import this solution,system say:
您只能将具有 9.0 版本或更早版本的包的解决方案导入到此组织中。此外，您无法将从 Microsoft Dynamics 365 2011 或更早版本中导出的任何解决方案导入到此组织中。
![image](https://user-images.githubusercontent.com/16302621/65386964-77f4fd80-dd74-11e9-9958-eb70b09fba8c.png)

Dynamics365WorkflowTools_1_0_56_0_managed

**Comment by franglais** [comment]
Looks like you may be on an older version of Dynamics that isn't supported by this solution? What version of Dynamics are you running?

**Comment by gooniesnsd** [comment]
Same issue here.  Tried on-prem version 9.0.3 and 9.0.8 but receive the same error.  
Love this workflow solution, by the way. 

![image](https://user-images.githubusercontent.com/56984243/67534100-3072d180-f692-11e9-8020-9a0fa166c303.png)

**Comment by demianrasko** [comment]
Hi all, 
this solution only supports online versions.

thanks!
