### ISSUE TITLE
Is it possible to capitalize text in a field, no matter the content?

### ISSUE THREAD

**Issue by ThorTankred** [demianrasko/Dynamics-365-Workflow-Tools#16]
Hi Demian,

I want to capitalize all the letters in a field (Single Line of text) no matter what text they actually put in this field. But I can't seem to figure out how to do this. I tried using the string functions, triggered as a real-time workflow on changes in that field, but I am unsure how to add all the required input lines. I am also unsure if I can capitalize the text in the same field or if I need to create a new field where I can store my capitalized 'conversion'.

Thanks for a great tool
/Thor

**Comment by ThorTankred** [comment]
No rewsponse ? :-)

**Comment by demianrasko** [comment]
I have few issues dalayed, cause last week was Directions EMEA event in Madrid. how to response soon, because I'm going to answer all of them.

**Comment by demianrasko** [comment]
Hi ThorTankred, I'm trying to understand what are you saying...
"String functions" actions returns an output parameter called "CapitalizedText" with the string capitalized like this:
1) Example: if "Capitalize All Words" =True:     
"this is the text to capitalize" ----> "This Is The Text To Capitalize"
2) 1) Example: if "Capitalize All Words" =False:     
"this is the text to capitalize" ----> "This is the text to capitalize"

then you can execute an update on the entity to change the field value..

This is what you need?

**Comment by ThorTankred** [comment]
Hi Demian,

As I said on Extreme CRM in Lisbon, I really appreciate your tool.
And I know this is pro bono, so no pressure!

I'm sorry for not being specific enough.
What I meant was, all letters in the string.
They use this field for initials and hence they want to ensure its capitalized:

Example:
"Demian" ---> "DEMIAN"

**Comment by demianrasko** [comment]
Hi ThorTankred, 
check my new version 1.0.41.2, I just included 2 new output parameters, with Uppercase and Lowercase Texts.
hope it helps ;)

thanks!

**Comment by ThorTankred** [comment]
Hi Demian,

Awesome - I Think :-)

In which field, in the form, should I put the Output parameter?

**Comment by demianrasko** [comment]
It's an output parameter of the Workflow, so you can add a step to update the entity, and set the value in any field.
I just addedd a new image at the end, to show you how to do it: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/String%20Functions.md

hope it helps.

Demian

**Comment by ThorTankred** [comment]
![screenshot](https://user-images.githubusercontent.com/31473330/31480778-0c1dc47c-af20-11e7-9cea-02528940869c.PNG)

Hi Demian,

That made a big difference - It was easy to locate the output parameter, thanks!
Its failing though, due to my input fields being incorrect.

Honestly I am unsure what to put there, I 'just' need to capitalize the whole text (Single Line text with 150 characters).

Cheers
Thor

**Comment by demianrasko** [comment]
Thanks Thor!
I found a small bug. you can make it work if you change the parameter "Substring: Length" to zero.
Otherwise update the solution to version 1.0.41.3 with the bug fixed.

regards!

**Comment by ThorTankred** [comment]
Hooray,
It works perfectly!
