### ISSUE TITLE
Query Values - Returning Lookup GUID - Bugfix for Dynamics365v8?

### ISSUE THREAD

**Issue by hansimglueck2** [demianrasko/Dynamics-365-Workflow-Tools#160]
Hallo Demian,

I saw that you fixed [this](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/issues/90) issue for Dynamics365v9.
Would it be possible to fix it for Dynamics365v8 as well?

**Comment by demianrasko** [comment]
Hi hansimglueck2, sorry about that, but I can't have differrent CRM versions to test and fixe any issue, just moving forward adding new features and fixing.
In any case you have the last version of that class here, and you can copy/pase the working source code: 
https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/msdyncrmWorkflowTools/msdyncrmWorkflowTools/Class/QueryValues.cs
