### ISSUE TITLE
Roll up Function returning 0

### ISSUE THREAD

**Issue by melaniephilion** [demianrasko/Dynamics-365-Workflow-Tools#161]
I had the workflow tool for 2 months approx and I had the ROLLUP Function to do the sum of tax on the order, and the sum of weight. Today, when I tried to add a order product, I got an error on the plugin.rollupfunction. 

I went an upload the latest version of the solution which .56.
I went and took the same FETCH XML that I had in the previous workflows that worked. 
I add lines to my order. It returns 0.

I tested the SUM and AVERAGE and all returns 0.
CRM Online latest version 9.

**Comment by franglais** [comment]
This is the same as [issue 147](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/issues/147). We know what the issue is with the code, just need someone to actually fix it!

**Comment by demianrasko** [comment]
Fixed Today. 
Thanks for your feedback!
