### ISSUE TITLE
workflow tools can work with crm 2011?

### ISSUE THREAD

**Issue by nufri** [demianrasko/Dynamics-365-Workflow-Tools#162]
I have the 2011 version of mscrm and need some tools of this proyect.

It is possible to use in this version?

Thanks

**Comment by demianrasko** [comment]
Hi nufri, 
I cannot have any CRM version and release, to test everything. Just moving forward with new features, and bug fixes with the las online version.
in any case this is on open source code, you can create a branch, and start with your own version.

thanks!
