### ISSUE TITLE
Description field on Child Email from Case changed

### ISSUE THREAD

**Issue by pokkemonner** [demianrasko/Dynamics-365-Workflow-Tools#163]
### Expected behavior and actual behavior.

The Description field should not be touched, but we have seen that the Description field form a Child Email record is unwillingly changed to the exact text:"_< body dir="LTR" contenteditable="true" onfocusout="parent.setEmailRange();" lang="en-US" style="overflow-wrap: break-word;"></body >_"

### Steps to reproduce the problem (screenshots are really usefull)

When a parent Case is changed we first fill a custom field on the Case
Then we always update two text fields on the same child Email twice in a row

![image](https://user-images.githubusercontent.com/23504167/67078645-f6856500-f191-11e9-82f7-acbe28a55175.png)

,
![image](https://user-images.githubusercontent.com/23504167/67078685-0c932580-f192-11e9-918b-bd98ee7bd30d.png)

![image](https://user-images.githubusercontent.com/23504167/67078710-19177e00-f192-11e9-9448-e80edc8ef680.png)

### CRM Version - online/onpremise - WorkflowTools version

CRM Online version: 9.1.0.9233 Tool version: 1.0.56.0

**Comment by pokkemonner** [comment]
This is what is written in the Description field on the child Email: 
"< body dir="LTR" contenteditable="true" onfocusout="parent.setEmailRange();" lang="en-US" style="overflow-wrap: break-word;"></body >"

**Comment by demianrasko** [comment]
Hi pokkemonner, 
The code doesn't update the Email description field. maybe there is any issue in other part, or you should open a case support with Microsoft.

thanks!
