### ISSUE TITLE
Roll up funtions returning 0

### ISSUE THREAD

**Issue by RobAMS1** [demianrasko/Dynamics-365-Workflow-Tools#164]
As per melaniephilion below, roll up functions on 1.0.56.0 are not working.  XML tested and verified but all calculations return 0.  Builds on older versions are unaffected.  Tried to install an earlier version on my latest build but does not install 

Dynamics365WorkflowTools_1_0_45_0_8.2_managed.zip

An error occurred while importing a Solution. : Microsoft.Crm.CrmException: PluginType [msdyncrmWorkflowTools.Class.DeleteRecordAuditHistory] not found in PluginAssembly [msdyncrmWorkflowTools, Version=1.0.53.0, Culture=neutral, PublicKeyToken=416e876b9bee261e] which has a total of [71] plugin/workflow activity types.    at Microsoft.Crm.CrmPluginAssemblyMetadata.GetPluginTypeMetadata(String typeName)    at Microsoft.Crm.ObjectModel.PluginTypeServiceInternal`1.SetIsWorkFlowActivityAttribute(PluginType pluginTypeArg, IBusinessEntity PluginAssembly, SandboxCustomActivityInfo& customActivityInfo, CrmPluginTypeMetadata& typeMetadata, ExecutionContext Context)    at Microsoft.Crm.ObjectModel.AssemblyDataCanBeUpdatedValidator.ValidateInternal()    at Microsoft.Crm.ObjectModel.PluginValidatorBase.Validate()    at Microsoft.Crm.ObjectModel.PluginAssemblyServiceInternal`1.VerifyRegistrationAbility(IBusinessEntity pluginAssembly, Boolean createCall, ExecutionContext context, CrmPluginAssemblyMetadata assemblyMetadata)    at Microsoft.Crm.ObjectModel.PluginAssemblyServiceInternal`1.ValidateOperation(String operationName, IBusinessEntity entity, ExecutionContext context)    at Microsoft.Crm.ObjectModel.SdkEntityServiceBase.UpdateInternal(IBusinessEntity entity, ExecutionContext context, Boolean verifyAction)    at Microsoft.Crm.ObjectModel.PluginAssemblyServiceInternal`1.Update(IBusinessEntity entity, ExecutionContext context)    at Microsoft.Crm.Tools.ImportExportPublish.ImportPluginAssemblyHandler.UpdateExistingPluginAssembly(PluginAssembly pluginAssembly, String fileContent, BusinessProcessObject bpoService, BusinessProcessObject pluginTypeService, List`1 importingPluginTypes, Boolean skipValidation, BusinessEntityCollection existingPluginAssembly)    at Microsoft.Crm.Tools.ImportExportPublish.ImportPluginAssemblyHandler.ImportItem()

**Comment by franglais** [comment]
This is the same as [issue 147](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/issues/147). We know what the issue is with the code, just need someone to actually fix it!

**Comment by demianrasko** [comment]
Fixed Today. 
Thanks for your feedback!

**Comment by abousarsar** [comment]
Hello,
How did you fixed the issue ?
