### ISSUE TITLE
Insert Option value not working anymore

### ISSUE THREAD

**Issue by ml501g** [demianrasko/Dynamics-365-Workflow-Tools#166]
Expected behaviour is that a new OptionSet value will Show up in CE. And this finally worked only a few weeks ago when I set up the workflow.

A workflow will fire on creation of a new record and insert the record into a global optionset for one language.
![image](https://user-images.githubusercontent.com/57348698/68111866-69ac0c80-fef0-11e9-9e61-74731d338bfd.png)
The Name is just a string and the converted number is the next number for the optionset value.

This is CRM Online - 2019, wave 2 enabled - 1710 (9.1.0.9832)
I tested with 1.0.56 and 1.0.57.

**Comment by demianrasko** [comment]
Hi ml501g, I just checked again and it still working fine.
Please note that this action only works on Async workflows, and not working in real time workflows.

thanks!
