### ISSUE TITLE
Problem with 'Update Child Record'

### ISSUE THREAD

**Issue by SynSeed** [demianrasko/Dynamics-365-Workflow-Tools#17]
Hey,
i've been using the Workflow tools in order to update a date in all child records of a record of mine.
The problem is that it's always updating the child records one day before the actual date in the parent record. Do you know something about it?
Appreciate the help,
Thanks in advance

**Comment by SynSeed** [comment]
Up, please i need some help anyone?

**Comment by SynSeed** [comment]
UP, Mates please i need advice about this subject any will do.

**Comment by ThorTankred** [comment]
Hi,

Just a quick long shot here, sometimes this can be due to different time zones. We tried that all updates were triggered at 11 PM CET one day before, not 12 AM at the actual day. 
Try investigating if this could be the issue (Different time zone settings on these fields)

**Comment by demianrasko** [comment]
Hi Guys, 
I'll try to check this during this week.
Sorry form The delay, bit I really busy after vacations, and preparing sessions forma The DirectionsEMEa....
Regards!

**Comment by SynSeed** [comment]
Thank you guys,
i will check it out and inform you if theres any changes,
Again thanks!

**Comment by demianrasko** [comment]
Hi SynSeed, 
I just checked the code with some examples.
my code retrieves the parent field value using QueryByAttribute method. This retrieves the datetime value as UTC. And then I use the Update() message to set the new value on the child, setting the UTC value too. I tested using the Date/Time user defined fields, and work fine.
What type of datetime you have in this case?

thanks!

**Comment by ArtKarp** [comment]
A few questions...

You say you are getting the date/time as UTC.  

Is the workflow running in the context of the connected user or as system?

If the server is UTC and the "user"  is located in a different time zone (e.g. GMT-8), is the date copied at GMT or based on the user time zone? 

Looks like a great collection of tools
Thanks

**Comment by SynSeed** [comment]
Thank you Demian,
your explanation was very helpful i played with the time zone and it worked out
and thanks again for the clear explanation.

**Comment by demianrasko** [comment]
Thanks SynSeed for your feedback :)

**Comment by demianrasko** [comment]
Hi ArtKarp, 
I just retrieve and update datetime fields in UTC,  and I don't manage any timezone. 
I should wotk in same way on workflow running on user context and as system. 
Thanks!
