### ISSUE TITLE
Insert option value improvement suggestions

### ISSUE THREAD

**Issue by stevenfayers** [demianrasko/Dynamics-365-Workflow-Tools#170]
Firstly, thank you for this immensely useful solution - I only wish I was a good enough coder to be able to contribute as well.

Regarding the Insert option value, I have 2 suggestions for improvements:
1) Allow the value field to be optional so that it is automatically assigned the next number available
2) Allow the newly created value to be used in subsequent workflow steps so that the value can be created and then immediately used.

**Comment by demianrasko** [comment]
Thanks stevenfayers for the Idea.
I'll try to ionclude in next releases!

regards!
