### ISSUE TITLE
Dependency Calculation

### ISSUE THREAD

**Issue by DaivatVartak** [demianrasko/Dynamics-365-Workflow-Tools#171]
### Issue Description
Getting an error "Dependency Calculation. There was an error calculating dependencies for this component. Missing component id 8eb3060d-7217-479f-8a53-8c0180590068 If you contact support, please provide the technical details." while using the "Add Role to User" step

### Repro Steps
1. Start a new Process (Workflow) 
2. Add step "Add Role To User"
3. Set Properties
4. Set the properties as per https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Add%20Role%20To%20User.md
5. Click and Save will close the page and gives the "Dependency Calculation" error

### Environement Details
CRM Online (2019 release wave 2 enabled)
Server version: 9.1.0000.10125
Client version: 1.3.2447-191031-210952
WorkflowTools version: Dynamics365WorkflowTools_1_0_57_0_managed

**Comment by demianrasko** [comment]
Hi DaivatVartak, I undesrand that this is not working on design time, so it seems that this is not an issue in our code. I just tested in my online environment, and worked fine. Please chech if you are maybe selecting a second level security role, maybe there is an issue there. Otherwise, try with another role to check.

thanks

**Comment by DaivatVartak** [comment]
Hi, I have tried the same with the user having the "System Administrator" security role and also the workflow owned by the same user with selecting the security role (linked to main/parent BU) and it works. I am looking for an option to move the user from parent BU to child BU and change his Security role as well.

Your help on same is highly appreciated.

**Comment by pradeeppatidar** [comment]
Hi Demian, As generally we define roles at root BU and if user belongs to child BU and having role assigned. But when we send email to users in role using parent BU security role, email does not goes to the users in role in child BU as they have assigned a 2nd level inherited role.
And workflow Tool does not allow to select 2nd level role at design time.

So, is there any workaround if we need to send email to users in role in child BU?
