### ISSUE TITLE
Issue with Rollup Functions

### ISSUE THREAD

**Issue by xrmthomas** [demianrasko/Dynamics-365-Workflow-Tools#172]
I'm gettting very odd behaviour using the Rollup Functions action. When I run the action with this query it runs fine:
`<?xml version="1.0"?>
<fetch distinct="false" mapping="logical" output-format="xml-platform" version="1.0">
<entity name="opportunity">
<attribute name="estimatedvalue"/>
<attribute name="opportunityid"/>
<order descending="false" attribute="estimatedvalue"/>
<filter type="and">
<filter type="or">
<condition attribute="customerid" value="{{Record ID(Get Record ID)}}" uitype="account" operator="eq"/>
<condition attribute="xrmt_targetedentity" value="{{Record ID(Get Record ID)}}" uitype="account" operator="eq"/>
</filter>
<condition attribute="statecode" value="2" operator="eq"/>
</filter>
</entity>
</fetch>`

Now when I go and change the statecode filter value in the last filter condition from "2" to "0" suddenly the action fails with the following error message:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.RollupFunctions]
[msdyncrmWorkflowTools (1.0.57.0): Rollup Functions]

`Load CRM Service from context --- OK
_FetchXML=<?xml version="1.0"?> <fetch distinct="false" mapping="logical" output-format="xml-platform" version="1.0"> <entity name="opportunity"> <attribute name="estimatedvalue"/> <attribute name="opportunityid"/> <order descending="false" attribute="estimatedvalue"/> <filter type="and"> <filter type="or"> <condition attribute="customerid" value="{1304ab78-ebff-e911-a811-000d3a6540e8}" uitype="account" operator="eq"/> <condition attribute="xrmt_targetedentity" value="{1304ab78-ebff-e911-a811-000d3a6540e8}" uitype="account" operator="eq"/> </filter> <condition attribute="statecode" value="0" operator="eq"/> </filter> </entity> </fetch>
Value: 8a3cac22-5d05-ea11-a811-000d3a65469c
Value: f9c664d9-8e0f-ea11-a811-000d3a654d16
Value: 1511de66-900f-ea11-a811-000d3a654d16
Value: Microsoft.Xrm.Sdk.Money
Query Data --- Done`

Strangely it seems the query itself is being executed without issue, and to me the error that does pop up seems strange, as the first field in the fetch is a monetary field.

*Tried changing the filter to "1". works perfectly as well...
*Tried removing the status filter entirely, results in the same issue
*Tried using a filter condition with operator="in" to include al statuses, results in the same issue
*Tried using a filter condition with operator "not-null" for the statecode, results in the same issue
*Tried a And clause with a "ne" filter on status 1 and 2. Also no luck :(

now moving to query leads with the rollup functions it reacts the exact opposite way and **ONLY** accepts the query with lead status = "0"

It's getting impossible to reach my goals using this plugin. For me this seems to be a major bug (at least it's _really_ bugging me..). 

I'm out of ideas here. Any help would be much appreciated!

**Comment by miklemiracle** [comment]
@xrmthomas I've just faced the same issue.
It happens because one or few (I didn't check this) records in your query has blank field _estimatedvalue_, so plugin uses next field, which is GUID and it crashes when trying to execute this:
https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/7514493ecac43534637157897b976da99cfad93d/msdyncrmWorkflowTools/msdyncrmWorkflowTools/Class/RollupFunctions.cs#L203

@demianrasko — in previous versions we could use non-decimal/non-money fields in first attribute of fetchXML. Cause in most cases we just need to count records. In version 55 we could use this FetchXML and it worked
```
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false" >
   <entity name="gg_container" >
        <attribute name="gg_containerid" /> -- GUID
        <order attribute="gg_containerid" descending="true" />
        <filter type="and" >
               <condition attribute="statuscode" operator="eq" value="140120011" />
               <condition attribute="gg_bookingid" operator="eq" value="{PARENT_GUID}" />
           </filter>
       </entity>
   </fetch>
```
But in version 57 it started causing crashes, cause it hasn't money/decimal fields, so we:

1. Added it
1. Forced Dynamics to populate field

So, our Fetch now looks like:
```
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false" >   
	<entity name="gg_container" >  
		<attribute name="gg_loadweight" />  -- Money/Decimal field
		<attribute name="gg_containerid" /> -- GUID
		<order attribute="gg_containerid" descending="true" />
		<filter type="and" >
			<condition attribute="statuscode" operator="eq" value="140120007" />
		    <condition attribute="gg_bookingid" operator="eq" value="{PARENT_GUID}" />
		</filter>
	</entity>
</fetch>
```

Can you smth with it and return us ability not to use money/decimal fields in FetchXML, please!

**Comment by demianrasko** [comment]
Thanks miklemiracle for the explanation, I think that if maybe I return a "0" instead an exception it should work. I just updated a fix for this.

Thanks!
