### ISSUE TITLE
Force Calculation roll up field is not working

### ISSUE THREAD

**Issue by Nirmal1510** [demianrasko/Dynamics-365-Workflow-Tools#173]
Hi Experts.

I have a roll up field to calculate child cases for parent case. Field gives the number of child records.

I have a workflow which calculates roll up field. I don't get any error however it is also not working.

Workflow:

![image](https://user-images.githubusercontent.com/52452094/70981760-11068c80-20b6-11ea-9633-e8b6aa812b9f.png)

Field Name: Schema Name of the Field available on the Case entity
Record URL :  Record URL of the parent case.

Roll Up field:
![image](https://user-images.githubusercontent.com/52452094/70982496-5c6d6a80-20b7-11ea-9439-268a28f9c3df.png)

CRM Version:  Dynamics 365 Online 
Workflow Version: 1.0.52.1

Regards,
Nirmal

**Comment by demianrasko** [comment]
Hi Nirmal, 
please share me the complete details about your parameters. (FieldName & Parent Record URL).
in the screenshot you shared, you write "Schame Name of CRM Field", but there you should fill the schema name of the field like "new_totalamount" 

thanks

thanks!
