### ISSUE TITLE
Error trying to update Child Record

### ISSUE THREAD

**Issue by tmregna1213** [demianrasko/Dynamics-365-Workflow-Tools#174]
Trying to update matching field on Child Record and getting an error.

'msdyn_customerasset' entity doesn't contain attribute with Name = 'msdyn_Account' and NameMapping = 'Platform'. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=9255819, MinActiveRowVersion=9255819

Error code: 0x80040265
Session Id: f8548122-cfb5-41ca-a974-7cfc5b08edca
Activity Id: 5c10d9d2-ede0-4154-befb-748c83ea3070
Time: Mon Jan 06 2020 14:41:47 GMT-0500 (Eastern Standard Time)

### CRM Version - online/onpremise - WorkflowTools version

Microsoft Dynamics 365 online 							 						 						2019 release wave 2 enabled
	 							 							 							 					Version 1710 (9.1.0.10968) online
WorkflowTools version 1.0.58.0

![WorkflowError](https://user-images.githubusercontent.com/59579524/71844176-9b2d8980-3093-11ea-8f8b-50d25f22066d.png)

**Comment by demianrasko** [comment]
Hi tmregna1213, can you please me explain what you whant to update? The parent entity is Asset? And child records?

Thanks
