### ISSUE TITLE
Support for version 9.0

### ISSUE THREAD

**Issue by smeranda** [demianrasko/Dynamics-365-Workflow-Tools#175]
### Expected behavior and actual behavior.
Import solution.

### Steps to reproduce the problem (screenshots are really usefull)
I have Dynamics 365 Workflow Tools v 1.0.48.3 currently installed. When importing the latest version, Dynamics won't allow it:

> You can only import solutions with a package version of 9.0 or earlier into this organization. Also, you can't import any solutions into this organization that were exported from Microsoft Dynamics 365 2011 or earlier.

Is there a workaround to this?

### CRM Version - online/onpremise - WorkflowTools version
Version 1612 (9.0.8.15) (DB 9.0.8.15) on-premises

**Comment by demianrasko** [comment]
Hi smeranda, sorry about that, but right now it only support online environments, because I cannot support all onprem versions.
In any case, ypu have all the source code and maybe ypu can create your own fork to support onprem.

Thanks

**Comment by smeranda** [comment]
I understand, thanks for the reply.

If I update the on prem to version higher, should this work? In other words, is this a numbered version issue, or is there something related to on-prem that would cause this to not work?

**Comment by demianrasko** [comment]
Hi, I just didn't test it in onprem. I used last sdk for online, and not sure if that is going to work for onprem because is a different version.

Thanks
