### ISSUE TITLE
Rollup not triggered on record changes.

### ISSUE THREAD

**Issue by Blide12** [demianrasko/Dynamics-365-Workflow-Tools#176]
I have set the workflow as per documentation and set the rollup calculation to be triggered when a record created and field changes, but it seems that the workflow only works for a record created, not for record changes.

The changes is coming from Flow to populate the fields in the booking entity. I can see the last updated time in the rollup field when a new booking record created, but nothing happened when price field being populated by the Flow.

I am using this on CRM online with WorkflowTools v 1.0.56.0

**Comment by demianrasko** [comment]
Hi Blide12, it should work as expected. Do you have the Workflow execution log? Does the action triggered ok?
please try also to change async/sync property and check.

thanks!
