### ISSUE TITLE
Managed solutions

### ISSUE THREAD

**Issue by rappen** [demianrasko/Dynamics-365-Workflow-Tools#18]
From what I see under Releases, there are only unmanaged versions of the solutions.
You do not provide managed versions?
That would make it even easier to use, so that we do not handle unmanaged solutions that we "trust" you to do the development on.
For a scenario where we always have managed solutions in test/prod, and only unmanaged for the solutions we are actually working on in dev, having managed versions of third party tools would be great :)

**Comment by demianrasko** [comment]
Hi Jonas, thanks.
I'll try to create an managed solution too un muy next release.

Regares!

**Comment by demianrasko** [comment]
Hi Jonas, 
I my last release I added the managed solutions too.

Thanks for the feedback!
Demian.
