### ISSUE TITLE
Challenge with Associate Entity

### ISSUE THREAD

**Issue by sdevinatncm** [demianrasko/Dynamics-365-Workflow-Tools#186]
### Expected behavior and actual behavior.
We have an OOB N:N relationship between account and user; we use it to allow for multiple owners on an account.   When an account is re-assigned, we need to the new owner to have this extra relationship as well.  I have added a step in the workflow to add the association but it does not appear to add; it also does not generate a failure of any kind.  I think I may have the workflow step configured incorrectly.

The N:N relationship looks like this:
![image](https://user-images.githubusercontent.com/50217919/76458438-326ad200-63a0-11ea-8414-4eccdf909dcb.png)

### Steps to reproduce the problem (screenshots are really usefull)
See the workflow, and the way the associate step is configured
![image](https://user-images.githubusercontent.com/50217919/76458579-5dedbc80-63a0-11ea-8aac-ade3f945ed20.png)
![image](https://user-images.githubusercontent.com/50217919/76458597-65ad6100-63a0-11ea-962a-f9031027bbda.png)

### CRM Version - online/onpremise - WorkflowTools version
CRM online
workflow tools 1.0.54.0

**Comment by demianrasko** [comment]
hi @sdevinatncm , I just checked with last version on online environment and it worked fine:
![issue3](https://user-images.githubusercontent.com/18124945/87251720-1ec69980-c46e-11ea-9290-700f7c0582a1.png)
![issue2](https://user-images.githubusercontent.com/18124945/87251721-1ff7c680-c46e-11ea-9cbb-533845bf9e19.png)
![issue1](https://user-images.githubusercontent.com/18124945/87251723-20905d00-c46e-11ea-9a1c-44b3e4f8f30e.png)
