### ISSUE TITLE
Rollup Functions Error

### ISSUE THREAD

**Issue by jjones419** [demianrasko/Dynamics-365-Workflow-Tools#187]
I have been getting the following error randomly in Dynamics CRM when using the Rollup Functions tool.  I do use the PARENT_GUID value I assume the cast error deals with this somehow.

An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.RollupFunctions: System.InvalidCastException: Unable to cast object of type 'Microsoft.Xrm.Sdk.EntityReference' to type 'System.IConvertible'.

### CRM Online 9.1.0000.13841
###Workflow Tools Version 1.0.50.1

**Comment by jjones419** [comment]
I think I am going to update to a newer version to see if that corrects this issue.  What is the difference between the CDS version and the regular version?  I want to make sure I put the correct version in our environments.

**Comment by acehaddock** [comment]
CDs is only for a normal cds the reg is for a d365 cds

Sent from my iPhone
Cole Haddock

**Comment by jjones419** [comment]
Thanks!

**Comment by jjones419** [comment]
It appears that updating my version of the workflow tools to the latest addressed the issue.
