### ISSUE TITLE
Entity Attachment To Email: not attaching files from ActivityMimeattachment

### ISSUE THREAD

**Issue by Nithya0108** [demianrasko/Dynamics-365-Workflow-Tools#188]
I already have a received email with attachment and it is associated with the case. My requirement is to get the attachment from that received email and create a new email with that attachment and send to the target people.

I have configured the step to retrieve the attachment from "ActivityMimeAttachment". But it is not attaching the file from the received email associated with the case.  
If I set "Retrieve ActivityMimeAttachment" to false, it is properly retrieving the attachment from Case notes and attaching it to the email.

I have configured the "Entity Attachment to Email" Step for case as below.

<img width="435" alt="EntityattachmenttoEmailconfig" src="https://user-images.githubusercontent.com/24427670/77638271-e6618500-6f7c-11ea-88bf-ee80f3b4cb0e.PNG">

### CRM Version - 9.1 online - WorkflowTools version 1.0.58.0

Am I missing anything over here?

Thanks,
Nithya

**Comment by demianrasko** [comment]
Hi @Nithya0108 , if you want to read the Attachment from the Email, you shoul use the Email Record URL on the "Main Record URL" param (not the Case).

Hope this helps!

thanks!
