### ISSUE TITLE
Can't install updated version into D365 on-prem version 8.2

### ISSUE THREAD

**Issue by KarlaK-fl** [demianrasko/Dynamics-365-Workflow-Tools#189]
### Expected behavior and actual behavior.
I'm having an issue with workflow tools version 1.0.51.1 -- the tool, Set Process Stage, is giving me an error. 
I found the issue documented here: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/issues/102  and saw that you fixed it in version 1.0.53.0 
I downloaded version 1.0.53.0 but cannot import the solution. I get this error: 
![image](https://user-images.githubusercontent.com/28058316/80027144-4599b300-84b1-11ea-81e4-ef1496c82198.png)
You can only import solutions with a package version of 8.2 or earlier into this organization. Also, you can't import any solutions into this organization that were exported from Microsoft Dynamics 365 2011 or earlier.
I looked in the Solution.xml file, and see that the solution is for version 9.1 

How can I get a version with this fix that will import into D365 version 8.2?

### Steps to reproduce the problem (screenshots are really usefull)
**   Same as was spelled out in issue #102 referenced above. 

### CRM Version - online/onpremise - WorkflowTools version
**  Microsoft Dynamics 365  Version 1612 (8.2.8.15) (DB 8.2.8.15) on-premises
**  Workflow tools version 1.0.51.1

**Comment by demianrasko** [comment]
Hi @KarlaK-fl , sorry about that, but I'm not supporting onprem environments anymore for this tool.
I haven't any onprem environment to test, to I started to work only with cloud environments. There are a lot of issues and new features in the cploud environment that are not going to work anymore onprem.
In any case, evrything is opne source, so you can get the action you need and compile it and import into your dev environment,

thanks!
