### ISSUE TITLE
Send email function does not support some characters

### ISSUE THREAD

**Issue by Rasmussor** [demianrasko/Dynamics-365-Workflow-Tools#19]
Hi,

It seems like the "send email" workflow functionality does not support some characters. One of my clients are reporting that the workflow does not recognize the Danish letters "Æ", "Ø", and "Å" and instead insert them as "?". Does anybody have a fix for this?

Would be extremely helpful! Thanks!

Kind Regards,
Rasmus

**Comment by demianrasko** [comment]
Hi Rasmussor, 
as you can see in the source code on the file "SendEmail.cs", I'm not changing anything on the content of the email, just calling the SendEmailRequest message with the email Id, to execute the sending.
So maybe there is some issue on the CRM side. If you send mannualy in CRM it works fine?

thanks!

**Comment by Rasmussor** [comment]
Hi Demianrasko, 

Yes, manual emails from the same queue works fine.

**Comment by demianrasko** [comment]
Hi, 
I think you need to open a case with support.
As you can see in my code in the link bellow, I'm just getting the Guid of the email, and executing the SendEmailRequest message.

https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/msdyncrmWorkflowTools/msdyncrmWorkflowTools/Class/SendEmail.cs

regards...

**Comment by Rasmussor** [comment]
Hi,

Support request at Microsoft or... 

Thanks!

**Comment by Rasmussor** [comment]
Hi Demian,

By support, did you mean Microsoft or...?

Thanks!

**Comment by demianrasko** [comment]
Yes, sorry.
I mean Microsoft Support.

thanks!
