### ISSUE TITLE
Can't switch process via set process or set process stage after upgrading from version 51 to v58

### ISSUE THREAD

**Issue by vnathglo** [demianrasko/Dynamics-365-Workflow-Tools#190]
### Expected behavior and actual behavior.
For record to switch to the targeted BPF when set process is invoked from a realtime workflow

### Steps to reproduce the problem (screenshots are really usefull)
![image](https://user-images.githubusercontent.com/56888332/80237926-24f16a80-8623-11ea-8c87-044845858a5c.png)

![image](https://user-images.githubusercontent.com/56888332/80235995-12296680-8620-11ea-8fb2-1d18f5503c9b.png)

The GUID referred to in the error message does not belong to the BPF being targeted to become the active process. This wasn't happening in workflow tools version 1.0.51.1 before updating to 1.0.58.0.

### CRM Version - online/onpremise - WorkflowTools version
Dynamics 365 Version 1710 (9.1.0.15343) online
WorkflowTools version: 1.0.58.0

**Comment by demianrasko** [comment]
Hi @vnathglo, we had to change deeply that action on version 1.0.53.0, to support multiple active BPF.
Please share me more details about it, and I try to reproduce it.

thanks!
