### ISSUE TITLE
Rollup functions issue

### ISSUE THREAD

**Issue by rvroemen** [demianrasko/Dynamics-365-Workflow-Tools#194]
### Expected behavior and actual behavior.
I use solution version 1.0.52.1 (because it is still an OnPremise system).
The following workflow is created;
![image](https://user-images.githubusercontent.com/14164541/82749895-9a7c6200-9dac-11ea-84e8-c13bcedcdb0c.png)

The FetchXML used is:
![image](https://user-images.githubusercontent.com/14164541/82750054-f4315c00-9dad-11ea-98ce-468238ece107.png)
(all in one line, without CR LF)

where crmpp_total_line_amount is a currency value.

I update the parent Project as:
![image](https://user-images.githubusercontent.com/14164541/82749955-0c54ab80-9dad-11ea-9545-a8f178bcf55c.png)

I know that I can use the standard Rollup functions in CRM, but only 10 fields are allowed per entity (and I reached this amount already).

NOTE: the currency attribute is a calculated field!

### Steps to reproduce the problem (screenshots are really usefull)
See above

### CRM Version - online/onpremise - WorkflowTools version
CRM version 8.2.13.21

**Comment by demianrasko** [comment]
Hi @rvroemen , we solved some bugs since that version regarding Rollup Functions. please check on last version to download the last version of that action.

Sorry about that, but I don't have an onprem environment anymore to test that.

thanks!
