### ISSUE TITLE
Value is always set to zero

### ISSUE THREAD

**Issue by dim895** [demianrasko/Dynamics-365-Workflow-Tools#195]
### Expected behavior and actual behavior.
Hello, 

I have a parent entity called project and child entity called subproject.

I have created an on demand workflow on project entity to calculate field ceb_sub_project_cost (which is a decimal) of all children records (I need a sum of this field). Like a standard roll-up in fact.

I followed the exact procedure but all results are set to 0 even though  ceb_sub_project_cost_field contains values.

Please find the XML I added in the workflow activity.

Do you have any idea what can have gone wrong?

Thanks in advance

```
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
	<entity name="ceb_subproject">
		<attribute name="ceb_sub_project_cost" />
		<attribute name="ceb_subprojectid" />
		<order descending="true" attribute="ceb_sub_project_cost" />
		<filter type="and">
			<condition attribute="ceb_project_id" operator="eq" uitype="ceb_project" value="{PARENT_GUID}" />
		</filter>
	</entity>
</fetch>
```
### CRM Version - online/onpremise - WorkflowTools version
CRm version on premise 9.0

![Workflow](https://user-images.githubusercontent.com/53216074/84147080-15a47000-aa5d-11ea-8b7f-a4ead81f7b8e.png)

**Comment by dim895** [comment]
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
  <entity name="ceb_subproject">
    <attribute name="ceb_sub_project_cost" />
    <attribute name="ceb_subprojectid" />
    <order descending="false" attribute="ceb_sub_project_cost" />
    <filter type="and">
      <condition attribute="ceb_project_id" operator="eq" uitype="ceb_project" value="{PARENT_GUID}" />
    </filter>
  </entity>
</fetch>

**Comment by demianrasko** [comment]
Hi @dim895 , sorry about that. I don't have an onprem enviroment to test anything. We made some bug fixes on Rollup Function action on lasts versions, so you should use the last version.
thanks!
