### ISSUE TITLE
Error on Clone Process

### ISSUE THREAD

**Issue by gailhaines** [demianrasko/Dynamics-365-Workflow-Tools#197]
### Expected behavior and actual behavior.
When cloning a record and the multi-select option set does not contain data, I'm getting the following error when there isn't an option selected.  A validation error occurred.  The value of 'ha_geographiescoveredcountriesstudiedmodule4' on record of type 'ha_opportunitydocument' is outside the valid range.

Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.CloneRecord]
[msdyncrmWorkflowTools (1.0.58.0): Clone Record]
Load CRM Service from context --- OK
ObjectTypeCode=10059--ParentId=23f465c7-b57d-ea11-a811-000d3a4e6dc6
entering CloneRecord
fieldstoIgnore=
retrieved object OK
attribute:ha_procedurestreatmenttypesmodule3
attribute:ha_primaryprojecttypeslevel2module6
attribute:ha_module5name
attribute:ha_primaryanalysesmodule5
attribute:ha_geographiescoveredcountriesstudiedmodule4
attribute:ha_qualsusedmodule3
attribute:ha_linktobudgetmodule5
attribute:ha_primaryresearchvendorquotesmodule3
attribute:ha_geographiescoveredcountriesstudiedmodule6
attribute:ha_primaryresearchvendorquotesmodule6
attribute:ha_primaryresearchvendorquotesmodule4
attribute:ha_primaryresearchvendorquotesmodule5
attribute:ha_qualsusedmodule1
attribute:ha_professionalfeesmodule4
attribute:ha_qualsusedmodule2
attribute:ha_qualsusedmodule5
attribute:ha_qualsusedmodule4
attribute:ha_secondaryprojecttypeslevel1module1
attribute:ha_datavendorquotesmodule4
attribute:ha_secondaryprojecttypeslevel1module3
attribute:ha_expensesmodule5
attribute:ha_keywordsmodule3
attribute:ha_newproposalname
attribute:ha_primaryprojecttypelevel1module2
attribute:ha_budgeteddurationmodule1
attribute:ha_professionalfeesmodule1
attribute:ha_revisionnotes
attribute:ha_newproposalsenton
attribute:ha_datavendorquotesmodule1
attribute:ha_linktobudgetmodule3
attribute:ha_module4name
attribute:ha_primaryresearchvendorquotesmodule1
attribute:ha_name
attribute:ha_clinicalareaslevel1module1
attribute:ha_clinicalareaslevel1module5
attribute:ha_primaryprojecttypeslevel2module2
attribute:ha_budgeteddurationmodule4
attribute:ha_clinicalareaslevel1module3
attribute:ha_primaryanalysesmodule3
attribute:ha_qualsusedmodule6
attribute:ha_procedurestreatmenttypesmodule4
attribute:ha_author
attribute:ha_secondaryprojecttypeslevel1module5
attribute:ha_primaryprojecttypeslevel2module1
attribute:ha_primaryprojecttypeslevel2module3
attribute:ha_secondaryanalysesmodule1
attribute:ha_secondaryanalysesmodule2
attribute:ha_procedurestreatmenttypesmodule2
attribute:ha_secondaryanalysesmodule5
attribute:ha_secondaryanalysesmodule6
attribute:ha_linktobudgetmodule6
attribute:ha_primaryanalysesmodule6
attribute:ha_keywordsmodule1
attribute:ha_primaryprojectobjectivemodule6
attribute:ha_clinicalareaslevel2module4
attribute:ha_secondaryanalysesmodule4
attribute:ha_primaryprojecttypelevel1module3
attribute:ha_linktobudgetmodule1
attribute:ha_expensesmodule4
attribute:ha_keywordsmodule4
attribute:ha_secondaryprojecttypeslevel1module6
attribute:ha_budgeteddurationmodule3
attribute:ha_expensesmodule1
attribute:ha_primaryprojectobjectivemodule4
attribute:ha_primaryprojectobjectivemodule5
attribute:ha_module6name
attribute:ha_primaryprojectobjectivemodule1
attribute:ha_datavendorquotesmodule6
attribute:ha_clinicalareaslevel2module3
attribute:timezoneruleversionnumber
attribute:ha_clinicalareaslevel2module5
attribute:ha_clinicalareaslevel2module6
attribute:ha_primaryresearchvendorquotesmodule2
attribute:ha_secondaryprojecttypeslevel1module4
attribute:ha_budgeteddurationmodule5
attribute:ha_secondaryanalysesmodule3
attribute:ha_primaryprojecttypelevel1module1
attribute:ha_drugsproductsinvolvedmodule5
attribute:ha_drugsproductsinvolvedmodule4
attribute:ha_primaryanalysesmodule1
attribute:ha_drugsproductsinvolvedmodule6
attribute:ha_drugsproductsinvolvedmodule1
attribute:ha_drugsproductsinvolvedmodule3
attribute:ha_drugsproductsinvolvedmodule2
attribute:ha_professionalfeesmodule5
attribute:ha_geographiescoveredcountriesstudiedmodule5
attribute:ha_procedurestreatmenttypesmodule1
attribute:ha_documenttype
attribute:ha_expensesmodule6
attribute:ha_geographiescoveredcountriesstudiedmodule3
attribute:ha_clinicalareaslevel2module2
attribute:ha_professionalfeesmodule6
attribute:ha_procedurestreatmenttypesmodule6
attribute:ha_linktobudgetmodule2
attribute:ha_expensesmodule3
attribute:ha_keywordsmodule5
attribute:ha_primaryprojectobjectivemodule3
attribute:ha_budgeteddurationmodule2
attribute:ha_module3name
attribute:ha_professionalfeesmodule3
attribute:ha_clinicalareaslevel2module1
attribute:ha_datavendorquotesmodule3
attribute:transactioncurrencyid
attribute:ha_geographiescoveredcountriesstudiedmodule1
attribute:ha_primaryanalysesmodule4
attribute:ha_numberofmodules
attribute:ha_primaryprojecttypeslevel2module4
attribute:ownerid
attribute:ha_primaryprojecttypelevel1module5
attribute:ha_clinicalareaslevel1module4
attribute:ha_proposallink
attribute:ha_version
attribute:ha_budgeteddurationmodule6
attribute:ha_primaryprojecttypeslevel2module5
attribute:ha_secondaryprojecttypeslevel2module5
attribute:ha_clinicalareaslevel1module2
attribute:ha_cloneopportunitydocument
attribute:ha_datavendorquotesmodule2
attribute:ha_module1name
attribute:ha_titleofproposal
attribute:ha_opportunity
attribute:ha_geographiescoveredcountriesstudiedmodule2
attribute:ha_expensesmodule2
attribute:ha_linktobudgetmodule4
attribute:ha_professionalfeesmodule2
attribute:ha_datesenttoclient
attribute:ha_secondaryprojecttypeslevel1module2
attribute:ha_datavendorquotesmodule5
attribute:ha_keywordsmodule6
attribute:ha_keywordsmodule2
attribute:ha_primaryanalysesmodule2
attribute:ha_casestudyincludedmodule6
attribute:ha_casestudyincludedmodule4
attribute:ha_casestudyincludedmodule5
attribute:ha_module2name
attribute:ha_casestudyincludedmodule3
attribute:ha_casestudyincludedmodule1
attribute:ha_procedurestreatmenttypesmodule5
attribute:ha_clinicalareaslevel1module6
attribute:ha_casestudyincludedmodule2
attribute:ha_primaryprojecttypelevel1module4
attribute:ha_secondaryprojecttypeslevel2module1
attribute:ha_secondaryprojecttypeslevel2module2
attribute:ha_secondaryprojecttypeslevel2module3
attribute:ha_secondaryprojecttypeslevel2module4
attribute:ha_primaryprojectobjectivemodule2
attribute:ha_secondaryprojecttypeslevel2module6
attribute:ha_primaryprojecttypelevel1module6
creating cloned object...

	
	[Microsoft.Crm.ObjectModel: Microsoft.Crm.ObjectModel.TargetAttributeValidationPlugin]
	[c754fdb4-ef2f-4f2c-b49f-186214ab4dcd: TargetAttributeValidationPlugin]
	
	

Error Message:

Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: A validation error occurred.  The value of 'ha_geographiescoveredcountriesstudiedmodule4' on record of type 'ha_opportunitydocument' is outside the valid range.
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass24_0.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.CDSExecute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --

[Clone Error.docx](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/files/4892267/Clone.Error.docx)

### CRM Version - online/onpremise - WorkflowTools version

CRM Online with the latest version

**Comment by demianrasko** [comment]
Hi @gailhaines , I just tested that it works fine with the multiselect optionset field types.
I think it could probably regarding a value you had on the definition of that field, and you removed it from the list, so right now is not existing anymore. Then it fails on the creation of the new field.
please try to include this field on the "Fields to ignore" parameter and see if that works.

thanks!
