### ISSUE TITLE
Feature request: Function to get option set value (not label)

### ISSUE THREAD

**Issue by stevenfayers** [demianrasko/Dynamics-365-Workflow-Tools#198]
While "Get Multi Select OptionSet" returns a list of values, it doesn't work with single selection option sets. Ideally it would be great to have a function that takes inputs of:
Record URL (dynamic) and 
attribute name, 
and return the numeric, internal value of the option set value (such as 1)

**Comment by demianrasko** [comment]
Thanks @stevenfayers for the idea, I just created the new action in the last version 1.0.59.0. GetOptionSetValue
