### ISSUE TITLE
[Help Needed] Clone Child - Target Record URL

### ISSUE THREAD

**Issue by Simon-Groupe-Calliope** [demianrasko/Dynamics-365-Workflow-Tools#199]
Hi,

Wanted to clone child after using "Clone Record" workflow.

My question is : How to get dynamics "Target Record URL" ?
I'm just get the cloned record ID

![image](https://user-images.githubusercontent.com/68338581/87557646-722c2800-c6b8-11ea-8547-2a64d2d56c24.png)

Thanks for answer.

Kings regards

-------------------------

CRM Version : 9.1 - online 
WorkflowTools version : 1.0.58.0

**Comment by demianrasko** [comment]
Hi Simon, sorry for the delay.
I think right now you don't have it, but you can compose it in string concatening the values.

thanks!
