### ISSUE TITLE
Solution import error: Plugin Types import: FAILURE (System.Xml.XmlElement caused an exception)

### ISSUE THREAD

**Issue by nathaniel-holder** [demianrasko/Dynamics-365-Workflow-Tools#2]
We have Dynamics 365 (8.2) and encountering the following error when trying to import the solution "Dynamics365WorkflowTools_1_0_38_0.zip":

`				<Cell ss:StyleID="s137" name="ErrorCode">
					<Data ss:Type="String">0x80048012</Data>
				</Cell>
				<Cell ss:StyleID="s137" name="ErrorText">
					<Data ss:Type="String">Plugin Types import: FAILURE. Error: Plugin: msdyncrmWorkflowTools, Version=1.0.37.0, Culture=neutral, PublicKeyToken=416e876b9bee261e of PluginTypeName: Microsoft.Crm.Entities.PluginType and PluginTypeNode: System.Xml.XmlElement caused an exception.</Data>
				</Cell>
`

I'm attaching the full importlog as well (it's xml, but had to give it a txt extension for the attachment to be accepted).

Thanks so much, I'm looking forward to using this solution!

[importlog_Dynamics365WorkflowTools_1_0_38_0.xml.txt](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/files/891505/importlog_Dynamics365WorkflowTools_1_0_38_0.xml.txt)

**Comment by nathaniel-holder** [comment]
I also tried to to enable custom XAML workflows (per https://msdn.microsoft.com/en-us/library/gg309458.aspx) and got access denied errors when running the powershell command /files/891738/get-crmsetting.customcodesettings.txt)
" as a domain admin on the crm server machine.  Not sure if it's related, but thought I'd add that.

Here's the full error:
[get-crmsetting customcodesettings.txt](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/files/891742/get-crmsetting.customcodesettings.txt)

**Comment by demianrasko** [comment]
Hi Nathaniel, to start using the solution, you can download too from Codeplex: https://msdyncrmworkflowtools.codeplex.com/
(right now they are the same version).

I have this issue opened with another user, but for me works fine. Please share me the build number version of your CRM org (see it in about... en the top right on the nav bar).

thanks!

**Comment by nathaniel-holder** [comment]
Hi Demian,

Thanks for your response!  Our version of CRM is: "Microsoft Dynamics 365 Version 1612 (8.2.0.749) (DB 8.2.0.749) on-premises".  So we're one version ahead of what you tested it on, and we're also on-prem.

I downloaded the solution from "https://msdyncrmworkflowtools.codeplex.com/downloads/get/1645798", where it says it is "Dynamics 365 Workflow Tools Solution 1.0.38.0 (SDK 8.2.0)".  The filename of the solution downloaded is "Dynamics365WorkflowTools_1_0_38_0.zip", but the error message refers to "Version=1.0.37.0" for "Plugin: msdyncrmWorkflowTools".  I wonder if that is the issue?

**Comment by demianrasko** [comment]
I think you are one version BEHIND my version:
you have:               8.2.0.749
my tested version: 8.2.0.798
So it seems your onpremise version has something different than the last version in Online. I'll try to check that issue.

So I think my version is newer. In any case I'll check if I have any more details about why this is not working.
I will try it in different versions.

thanks!

**Comment by nathaniel-holder** [comment]
Ahh, right you are.  I think I have the latest on-prem version though.  Thanks for checking it out.

**Comment by nathaniel-holder** [comment]
Figured out the problem, and fixed it on my end: The "Microsoft Dynamics CRM Sandbox Processing Service" was not running.  I just needed to start it.

**Comment by Emzil** [comment]
Had the same issue. You need to check customization.xml in the solution. Extra plugin types in my case.
