### ISSUE TITLE
Add Encrypt Text Hash Options

### ISSUE THREAD

**Issue by ArtKarp** [demianrasko/Dynamics-365-Workflow-Tools#20]
It would be great to have a choice of secure encryption options.  MD5, published in 1992, is no longer considered secure and SHA-1 has been deprecated by Microsoft.  SHA-2 (256/512) and SHA-3(256/512) would be great to used to secure data in D365.   In fact, to meet some US government requirements, a company must use a specific encryption method like SHA-2. I would keep the MD5 as an option, since existing data would need to be upgraded to a secure method of encryption.   

Here is some info on SHA-3 hash:
 https://keccak.team/index.html

**Comment by demianrasko** [comment]
Hi ArtKarp, 
i'll think about it for next releases... 
Thanks for your feedback. 

Demian

**Comment by demianrasko** [comment]
Hi ArtKArp, you have it now. I just added in my last version, the encription to SHA512.
download the lasat version: 1.0.42.1

regards

**Comment by demianrasko** [comment]
I also updated the documentation:
https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Encrypt%20Text.md

thanks
