### ISSUE TITLE
Set lookup field using ID of the record being looked up

### ISSUE THREAD

**Issue by stevenfayers** [demianrasko/Dynamics-365-Workflow-Tools#200]
**Is your feature request related to a problem? Please describe.**
We have times where we want to search for a record as an appicable parent then set the lookup on thebcurrent recore. We use FetchXML to find the ID of the parent (using concatenate from query), and would like a way to then set the lookup field on the current record to point to the parent that has previously been found

**Describe the solution you'd like**
A feature to set a lookup field on the record on which the workflow is being run providing the parameters of:
- Field name of the lookup field
- GUID (as string) or Record URL of the parent to which the lookup should be set.

**Describe alternatives you've considered**
Other workflow tools solution which requires multiple steps to achieve and is a bit clumsy,

**Comment by demianrasko** [comment]
Thanks Stevenfayers, 
the problem here is a limitation with Workflows, where we cannot set dynamic type value on lookups.
Maybe we can achieve this with Actions, but not with standard features.

The output paramenters type of the Custom activities cannot be "dynamic"

thanks
