### ISSUE TITLE
Enhance 'Concatenate from query' to stop after n records.

### ISSUE THREAD

**Issue by stevenfayers** [demianrasko/Dynamics-365-Workflow-Tools#201]
**Is your feature request related to a problem? Please describe.**
Sometimes we want to just get the top n records and concatenate the data into a string. Rather than remembering to put count=n into the fetch XML it would be simplier to have a numeric field to stop after n recrds.

**Describe the solution you'd like**
Add optiona numeric field to 'Concatenate from query' to stop after n records. Blank means all.

**Describe alternatives you've considered**
Remembering to add count= in the fetchXML

**Additional context**

**Comment by demianrasko** [comment]
Added this feature in the new version 1.0.61.0.

Thanks for the Idea!
