### ISSUE TITLE
Dynamics365WorkflowTools_1_0_60_1_managed nor Dynamics365WorkflowTools_1_0_60_0_managed.for.CDS will import into v9.0

### ISSUE THREAD

**Issue by snuzzi** [demianrasko/Dynamics-365-Workflow-Tools#205]
**Describe the bug**
We're on version 1612 (9.0.15.9) on-premises and I get the following error when trying to Import.  

![image](https://user-images.githubusercontent.com/26743669/88989957-d0592d80-d2aa-11ea-9d95-e7360bb0a532.png)

**To Reproduce**
1. Go to 'Settings\Solution'
2. Click on 'Import'
3. Choose 'Dynamics365WorkflowTools_1_0_60_1_managed.zip' file and click Open
4. Click Next

**Expected behavior**
Error states: "You can only import solutions with a package version of 9.0 or earlier into this organization. Also, you can't import any solutions into this organization that were exported from Microsoft Dynamics 365 2011 or earlier."

**Screenshots**
![image](https://user-images.githubusercontent.com/26743669/88989957-d0592d80-d2aa-11ea-9d95-e7360bb0a532.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by supercatoa** [comment]
Hi, Any solution for this?
having the same problem

**Comment by eSoroosh** [comment]
We have the same problem with 9.0.16.7 version...

**Comment by RichardToulson** [comment]
We have the same issue. Has anyone found a solution?

**Comment by RichardToulson** [comment]
> 
> 
> We have the same problem with 9.0.16.7 version...

I used version 1.0.52.1 and it works fine.

**Comment by Lgallair** [comment]
Unfortunately, 1.0.52.1 does not include v9.0 support; especially for multi-select option sets.

**Comment by demianrasko** [comment]
Hi snuzzi, 
this solution is only tested in last versions of CDS online (Dataverse). you have all the source code if you whant to complit the assembly by your own.

thanks!
