### ISSUE TITLE
CheckUserInRole not working Dynamics 365

### ISSUE THREAD

**Issue by priyeshwagh777** [demianrasko/Dynamics-365-Workflow-Tools#209]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GerritRega** [comment]
I see this issue in this way, that the "Curent" User will be checked.
As example, i try to check  a role for antoher user, i got the resuklt grm MY user.
in all user/team fields the workflow ask for the user.
Not in this workflow.
Is this wanted?

**Comment by sudipmandal** [comment]
Facing same issue, currently there is no step to check if an user has a role, this check user in role only checks the user who triggered the workflow has a role or not. This imo is not very useful.

**Comment by demianrasko** [comment]
Merged in the new version 1.0.61.0 ;)

thanks all!
