### ISSUE TITLE
Dynamics-365-Workflow-Tools : Problemas en funcion "Calculate Rollup Field"

### ISSUE THREAD

**Issue by faviocanossa** [demianrasko/Dynamics-365-Workflow-Tools#21]
Hola Demian, estoy intentando utilizar esta función y me esta dando el siguiente error:
Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: 'vta_pl_gruponet' entity doesn't contain attribute with Name = '$ 0,00'.Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>9329d6c0-29d1-44e8-aaa9-198ab93d25d4</ActivityId>
  <ErrorCode>-2147220891</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
    <KeyValuePairOfstringanyType>
      <d2p1:key>OperationStatus</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">0</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>SubErrorCode</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">-2146233088</d2p1:value>
    </KeyValuePairOfstringanyType>
  </ErrorDetails>
  <Message>'vta_pl_gruponet' entity doesn't contain attribute with Name = '$ 0,00'.</Message>
  <Timestamp>2017-10-21T16:20:51.2827988Z</Timestamp>
  <ExceptionRetriable>false</ExceptionRetriable>
  <ExceptionSource i:nil="true" />
  <InnerFault i:nil="true" />
  <OriginalException i:nil="true" />
  <TraceText>

[Microsoft.Crm.ObjectModel: Microsoft.Crm.ObjectModel.SyncWorkflowExecutionPlugin]
[542c4c03-1cb5-e711-8108-e0071b6eacf1: ]
Sync workflow 'Guponet - Calcular Campos P&amp;L' terminated with error ''vta_pl_gruponet' entity doesn't contain attribute with Name = '$ 0,00'.'

</TraceText>
</OrganizationServiceFault>

He instalado la ultima versión 1.0.42.0.1
Cree 1 entidad principal P&L donde tengo campos consolidados que hace a la otra Entidad hija llamada P&L-descripcion.
Cuando cargo datos en la entidad P&L-descripcion se deberian actualizar los campos consolidados de P&L.
Cree una relación 1:n jerarquica entre estas 2 entidades.
Arme un WF que se dispara cuando se modifica o se crea un registro en P&L-descripcion para utilizar la funcion "Calculate Rollup Field"
Te paso la definicion de los parametros: 
![wf](https://user-images.githubusercontent.com/32936598/31854383-8153f1a8-b66e-11e7-96dd-385765fbab54.JPG)

No se cual cual puede ser el problema por el cual da error la Función.

Espero tus comentarios.
Muchas Gracias.

**Comment by demianrasko** [comment]
Hola, Favio.
ya veo el error que tienes en la imagen que me envías. En el primer parámetro, tener que poner el nombre de esquema del campo consolidado de la entidad padre. En este caso tu estas poniendo el "valor" y no el nombre del campo. debes poner el texto del nombre del campo y no su valor por ejemplo: "new_campoconsolidado".
míralo en la ayuda: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Force%20Calculate%20Rollup%20Field.md

"FieldName: The Rollup field Name of the parent entity."

el error, es correcto, ya que te dice que el valor "'$ 0,00'." no existe como nombre de campo en la entidad padre.

abrazo!
