### ISSUE TITLE
Set Process works but selecting Switch Process is still required

### ISSUE THREAD

**Issue by DaveStabilify** [demianrasko/Dynamics-365-Workflow-Tools#210]
**Describe the bug**
**The Set Process action seems to work but the BPF is still not visible in the target record until Switch Process is manually set on the record.**
**To Reproduce**
1. Use the Set Process action

**Expected behavior**
**The BPF should be visible in the target record after running this action. The user still has to select Switch Process for each individual record affected by the workflow.**

**Screenshots**

**Desktop (please complete the following information):**
ANY

**Smartphone (please complete the following information):**
ANY

**Additional context**

**Comment by demianrasko** [comment]
Hi DaveStabilify, 
not sure if I understand what happend to you, please share some screenshots and some more detail.

thasnk!
