### ISSUE TITLE
Update Child Records: Timeout with many child records

### ISSUE THREAD

**Issue by LisaDor** [demianrasko/Dynamics-365-Workflow-Tools#211]
We use the Workflow "Update Child Records" to be able to update Products on for example Opportunity and Quote. When we have many products (5000) this Workflow fails due to the 2 minutes time limitation for Workflows. We use CRM Online latest version and Workflow Tools version 1.0.58.0.

It would be nice to be able to define that this workflow should run asynchronous so we avoid this timeout. Or is there another way to manage this?

![image](https://user-images.githubusercontent.com/73243491/96743843-b2d8c300-13c4-11eb-90b8-64df2328a6b3.png)

**Comment by LisaDor** [comment]
Our problem is that we have plugins triggering on the Product that creates this situation. We are trying to find ways of not triggering the Plugins in certain situation and we think we might be able to solve the situation where we use "Update Child Records" but it seems more challenging with "Clone Children".  We deactivated all plugins and got problems with "Clone Children" when we tried to copy 80 Products from one Opportunity to another. Anyone that has any idea on how to solve scenarios where you need to copy many Products?

**Comment by demianrasko** [comment]
Hi LisaDor, 
I think you cannot avoid that 2 minute limitation...
