### ISSUE TITLE
[Share Record With Team] running into Optimistic concurrency issue

### ISSUE THREAD

**Issue by shalabhgupta1985** [demianrasko/Dynamics-365-Workflow-Tools#213]
**Describe the bug**
We are using Dynamics 365 Workflow Tools version 1.0.56.0. From a Async workflow on a trigger, we are sharing a record (custom entity) with an owner team using "**msdyncrmWorkflowTools (1.0.56.0):Share Record With Team ** ". The workflow always runs on an elevated privileges. 

No change has been made in this implementation since 2 years, however lately we are seeing issues where the workflow goes into the **Waiting** state. The underlying workflow error message we are seeing is **"More than one concurrent Share requests detected for an Entity <entityid> and ObjectTypeCode XXXX."**

On further research, it was observed that as per best practices, [Optimistic concurrency](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/optimistic-concurrency) needs to be enabled to avoid such issues.

_Most of the time, resuming the same waiting workflow resolves the error, however that is not an ideal solution._

When I pulled the code from Github, it seems that is not enabled within the params of the GrantAccessRequest method of this action.

My ask is to see if this is something as a known issue or if this plugin can be modified to accommodate Optimistic Concurrency?

**Expected behavior**
The workflow calling this action "msdyncrmWorkflowTools (1.0.56.0):Share Record With Team" should run without going into waiting stage and avoid concurrency errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/13446757/99989285-6fd18d00-2d80-11eb-87bb-fab3287e7886.png)
![image](https://user-images.githubusercontent.com/13446757/99989403-968fc380-2d80-11eb-8978-0dde3ad67c12.png)

**STACK TRACE**
Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.ShareRecordWithTeam]
[msdyncrmWorkflowTools (1.0.56.0): Share Record With Team]
Load CRM Service from context --- OK
ObjectTypeCode=XXXXX--ParentId=<recordid>
Grant Request--- Start

Error Message:

Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: More than one concurrent Share requests detected for an Entity 883fec5b-b32a-eb11-a813-001dd8016c9d and ObjectTypeCode 10212.
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass27_0.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.CDSExecute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --

**Comment by shalabhgupta1985** [comment]
Hi Is there an update on this issue?

**Comment by demianrasko** [comment]
Hi shalabhgupta1985, 
This type of issues occours when you are trying to do the same action from one place and another at the same time.
Not sure how to avoid this in my code.
Any idea?

thanks

**Comment by shalabhgupta1985** [comment]
Hi @demianrasko 

Thanks for your reply. Would something like this work?
https://community.dynamics.com/crm/b/tipsandtricksofcrm/posts/optimistic-concurrency-in-dynamics-crm
![image](https://user-images.githubusercontent.com/13446757/103570146-8e09cd00-4e96-11eb-9fe7-c93fc255b594.png)

I guess we need to apply ConcurrencyBehavior in the code.

Let me know if that helps!
-Shalabh

**Comment by demianrasko** [comment]
Thanks shalabhgupta1985, but I think in this case is not when I updating a record, is when I'm sharing a record, and I think there is no "optimistic concurrency" support for sharing, just only for uptdate.
