### ISSUE TITLE
Migrating from version 1.0.58.0 to 1.0.60.1 causing import issues.

### ISSUE THREAD

**Issue by shalabhgupta1985** [demianrasko/Dynamics-365-Workflow-Tools#214]
**Describe the bug**
We are currently using a managed version (1.0.58.0) of Dynamics365WorkflowTools solution in our Dynamics Online instance as shown below:
![image](https://user-images.githubusercontent.com/13446757/100005863-9bac3d00-2d97-11eb-9ea3-dddab99ed299.png)

When trying to import a higher managed version (1.0.60.1) downloaded from https://github.com/demianrasko/Dynamics-365-Workflow-Tools/releases/tag/1.0.60.0, we are getting an import error.

![image](https://user-images.githubusercontent.com/13446757/100005966-c8605480-2d97-11eb-9d1a-c86ed1604530.png)

Following options are selected when importing the higher version:
![image](https://user-images.githubusercontent.com/13446757/100006052-e463f600-2d97-11eb-8013-65756b7ede1d.png)

![image](https://user-images.githubusercontent.com/13446757/100006071-e9c14080-2d97-11eb-8531-acf3608c1f14.png)

_Also tried with StageForUpgrade+Overwrite Customizations with the same error._

**Expected behavior**
The import should work without any issues.

**Screenshots**
Attached in the description of the issue

**Import Error File
[ImportLog.xlsx](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/files/5585328/ImportLog.xlsx)
**Plugin Assemblies import: FAILURE. Error: Plugin: msdyncrmWorkflowTools, Version=1.0.60.1, Culture=neutral, PublicKeyToken=416e876b9bee261e of PluginTypeName: Microsoft.Crm.Entities.PluginType and PluginTypeNode:  caused an exception.: Plugin Types import: FAILURE. Error: Plugin: msdyncrmWorkflowTools, Version=1.0.60.1, Culture=neutral, PublicKeyToken=416e876b9bee261e of PluginTypeName: Microsoft.Crm.Entities.PluginType caused an exception.: PluginType [msdyncrmWorkflowTools.CreateTeam] not found in PluginAssembly [msdyncrmWorkflowTools, Version=1.0.56.0, Culture=neutral, PublicKeyToken=416e876b9bee261e] which has a total of [73] plugin/workflow activity types.**
**

**Additional context**

**Comment by shalabhgupta1985** [comment]
Hi Is there an update on this issue?

**Comment by demianrasko** [comment]
Hi shalabhgupta1985, 
I'm having some issues in last versions when I try to make version updates.
I don't have different environments to test this, but probabbly is better to create a branch and uptade the code mannually.

thanks!

**Comment by shalabhgupta1985** [comment]
Hi @demianrasko,

Thanks for your reply. Can you please elaborate your approach a little bit more..
