### ISSUE TITLE
Strings with double quotes in "Entity JSON Serializer"

### ISSUE THREAD

**Issue by AntonUdalow** [demianrasko/Dynamics-365-Workflow-Tools#215]
**Describe the bug**
You don't escape double quotes and perhaps another special characters also.
Please see "using backslash escapes" here: https://www.json.org/json-en.html

**To Reproduce**
1. Set double quotes anywhere in string field of entity record.
2. Execute "Entity JSON Serializer" action
3. See error, for example, with your "JSON Parser"

**Expected behavior**
JSON special characters have to be escaped.

**Screenshots**
Message: An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute):  msdyncrmWorkflowTools.JsonParser: Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: C

### CRM Version - online/onpremise - WorkflowTools version
It doesn't matter

**Comment by demianrasko** [comment]
Solved in new version 1.0.61.0

**Comment by AntonUdalow** [comment]
Thank you, but now it does not work with JSON Parser: msdyncrmWorkflowTools.JsonParser: System.Exception: After parsing a value an unexpected character was encountered: ". Path 'wolf_annualagreement.wolf_name', line 1, position 107.
