### ISSUE TITLE
Dynamics-365-Workflow-Tools/docs/ConcatenateFromQuery

### ISSUE THREAD

**Issue by jargo365** [demianrasko/Dynamics-365-Workflow-Tools#217]
Hi Demian, 

How can I add a jump line (\n) in the field concatenated?

Currently, I have ABC123, ABC456

I need this result:
ABC123
ABC456
is It possible? 
Thank you, and kind regards!

**Comment by demianrasko** [comment]
Hi YonyM, 
sis you tried with a \n in the separator?
