### ISSUE TITLE
Zip failed to install.

### ISSUE THREAD

**Issue by Sipowers** [demianrasko/Dynamics-365-Workflow-Tools#22]
Could not install on... 

Microsoft Dynamics 365
Version 1612 (8.2.2.111) (DB 8.2.2.111) online

with error message...

![image](https://user-images.githubusercontent.com/33060523/31945955-8e1f16a4-b8c8-11e7-8d0a-4a19dc00d929.png)

Is this version not supported yet?

Si

**Comment by demianrasko** [comment]
Hi Sipowers,  it should be supported. 
Which version ofthe solution are you using? 
Share me the file name please.

**Comment by Sipowers** [comment]
Hi Demian,

Hi I cant find a version on the Download zip files, but it was the one available on 'Clone or Download' button here and has a last modified date of 15/10/2017. The file name is just 'Dynamics-365-Workflow-Tools-Master'.

Many thanks, Si

**Comment by Sipowers** [comment]
Sorry looks I closed this by mistake, this issue is actually still active. Thank you.

**Comment by demianrasko** [comment]
Sorry, but I'm not sure about what you did.
you must go to the releases page: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/releases
and donwloand the solution to your CRM version.
please tell me the name of the solution file are you using.

thanks!

**Comment by Sipowers** [comment]
Ah! Sorry Demian I'm new to Github and did not spot the 'Releases' pane, my apologies. I will re-try the install later.

Incidentally, I presume its always best to install the 'Managed' version of this solution is it?

Thanks again, I will close this thread if install goes well and I'm sure it will.

Si

**Comment by demianrasko** [comment]
Hi Sipowers, 
yes, it's better to install as managed, if you are thinking to remove in the future.
thanks!

**Comment by Sipowers** [comment]
Hi Demian,

I have installed your managed workflow Tools which seem fine. However I am struggling to achieve the functionality I want using the Goal Recalculate function.

Basically I have a dashboard with Goal metrics set-up for the Case Entity and I want the chart to display the latest goal stats dynamically when things change. The changes will only happen infrequently so should not impact the server resources too much.

What I want to do (...call this option one) is recalculate a goal based on the case entity when a specific attribute changes on a case - giving me an almost real-time dashboard. However I cant reference the goal using Goal Recalculate if the main workflow is based on the case entity. I tried creating a child workflow based on the goal entity, but then of course Start Child workflow cannot see this as it has no direct relationship to a case.

Is the only way to do this to create a custom relationship between the Goal and Case entity?

Option two. Alternatively, instead of having an 'almost' real-time dynamic goal recalculate (as above), I could perhaps just set up a blind 'Goal Recalculate' once an hour or so - not great, because it would generate more hits on the server than the 'on-demand' version of Option one.

Any suggestions?

**Comment by demianrasko** [comment]
Hi Sipower, I just released the new version 1.0.45.0. there I included on Goal Recalculate, the parameter "Goal Guid" (string) to pass the string with the Goal ID. Hope this helps you.

thanks!

**Comment by demianrasko** [comment]
Hi Sipower.
Right now the only way is to use a custom relationship or to hardcode the Goal in the parameter. Maybe in future I'll could try to add another Parameter to the Goal Recalculate action, in order to pass the Goal "Guid" (in text).

the second option is ok too, if you recalculate every hour, is not to much "work" to the server, if you have only a few user...

thanks!
