### ISSUE TITLE
Rollup Functions input size

### ISSUE THREAD

**Issue by Rob-Nightingale** [demianrasko/Dynamics-365-Workflow-Tools#23]
Is it possible to increase the field size to possibly a multi line text field or larger than 2000 character input?
I have a large FetchXML request with many conditions that doesn't fit into the current input.

Thanks

**Comment by demianrasko** [comment]
I think you cannot change that limit.
But one idea, is to create a field with the "Fetch" and pass it as a parameter value.
For instance, you can create a Configuration entity, with a ntext field called "value" with more that 2000 characters,
Then you create a record with name "fetchXML" and value with the full fetchxml.
then you can use the "Query values" to retrieve that fetch xml from the configuration entity : https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Query%20Values%20Step.md
