### ISSUE TITLE
Rollup function

### ISSUE THREAD

**Issue by thomassandsor** [demianrasko/Dynamics-365-Workflow-Tools#25]
https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Rollup%20Functions.md

Tried recreating the formula as described here, but I get 0 back every time I use (value="PARENT_GUID") in the fetch xml

Am I using this wrong, or is there an error here?:)

**Comment by demianrasko** [comment]
Hi thomassandor, 
please check your FetchXML text again, because you need to add the parameter as "{PARENT_GUID}" and not "PARENT_GUID" (you need to add "{" and "}").
on my code the "replace" is like this:
_FetchXML = _FetchXML.Replace("{PARENT_GUID}", context.PrimaryEntityId.ToString());

hope this helps.

regards

**Comment by thomassandsor** [comment]
I have tried doing exactly as you write in your example on the page. Oppty sum up to Account description field. 

XML that i used: 
![xml](https://user-images.githubusercontent.com/33664322/32996294-18dc4dc6-cd81-11e7-8456-cef98c23826e.png)


The result is in the pictures below. I use on demand worflow for testing

![wf1](https://user-images.githubusercontent.com/33664322/32996245-a54b60ae-cd80-11e7-8906-45ab0623cca5.png)
![wf2](https://user-images.githubusercontent.com/33664322/32996246-a56bb872-cd80-11e7-9ef8-9c2dbb80709f.png)
![wf3](https://user-images.githubusercontent.com/33664322/32996247-a5883b64-cd80-11e7-82ae-c8f596a961cf.png)

**Comment by thomassandsor** [comment]
PS: When i replace the {PARENT_GUID} with a real guid in XML Tester, I get a value back that I am expecting

**Comment by demianrasko** [comment]
Hi thomassandsor, 
Now I understand your issue. You are executing the Workflow on the "opportunity" entity, and the {PARENT_GUID} record is replaced with the record ID of the record context that fired the Workflow.
If you execute the same workflow, but in the Account entity, you will have what you need.

Regards!

**Comment by demianrasko** [comment]
Thanks for the feedback, I understand your point.
That could be part of an new release s new features.
In any case, you can update a field on the parent record, and fire the rollup there

Thanks!
