### ISSUE TITLE
Goal Recalculate issue

### ISSUE THREAD

**Issue by Sipowers** [demianrasko/Dynamics-365-Workflow-Tools#26]
I have the latest version of the tools installed.

I have created a workflow that triggers a Goal Recalculate after certain conditions are met on a Case entity.

The workflow triggers ok and even shows the correct Last Rollup date in the relevant Goal entity, however the rollups associated with the goal do not actually roll-up. When I use the manual Goal recalculate button however - it does rollup as you would expect.

For some reason the Goal Recalculate workflow updates the Last Rollup date correctly, but does not rollup the goals associated rollup fields.

I have set both the Goal name and the new Goal GUIDS correctly. Any ideas? Could it possibly be related to the other users rollup issue just added?

many thanks,

Sipowers

**Comment by demianrasko** [comment]
Hi Sipowers, 
I'm not sure to undestand your issue, can you share some screenshots about your goal, and your Workflow params?
Are you talking that the Parent Goal y updated ok, but the child Goals are not updated? When you click on the "Recalculate" button in Goal form, it recalculates the parent Goal and the child ones (the whole tree), but my Action only recalculate the Goal with the "Guid" you passed as parameter.

regards!

**Comment by Sipowers** [comment]
Hi, its the Parent goal - I have no child goals. Your workflow is triggered and runs fine - last rollup date on the goal shows the date/time it ran - again fine. But... the rollups (Actuals etc.) associated with the goal - have not 'rolled up' the data. When I click the Manual 'Recalculate' on the goal, everything rolls up as normal. Hope that helps.

**Comment by demianrasko** [comment]
Hi,  sharw with me ypur example with screenshots,  and I'll reproduce the same behavior to identify and fix the issue. 

Thanks

**Comment by Sipowers** [comment]
Ok will do, thanks Demian

**Comment by Sipowers** [comment]
Seems to be working now! Many thanks.

**Comment by demianrasko** [comment]
Thanks for your feedback!
