### ISSUE TITLE
Suggestion - Provide date functions (modifiers)

### ISSUE THREAD

**Issue by github3332** [demianrasko/Dynamics-365-Workflow-Tools#28]
Thanks for incredible solution that takes care of quite a lot of complex activities.

I was wondering if you have some plans to enhance the the capabilities with date functions.

For example: If Difference (Actual Date - Created On) >24 hours, set a flag.

Basically date functions to figure out duration and return the calculated dates/duration to perform further processing.

Please feel free to contact if you would need more information

**Comment by demianrasko** [comment]
Hi github3332, thanks for your feedback.
I just added a new feature in the version 1.0.46.0 called "Date Functions". 
you can download now and use it.
The full documentation is here: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/DateFunctions.md

Thanks !!
