### ISSUE TITLE
Clone Record - Ignore fields

### ISSUE THREAD

**Issue by vektastic** [demianrasko/Dynamics-365-Workflow-Tools#32]
Hey Everyone.

I am using the "Clone" feature to clone Conferences that share much of the same data but ignore some fields that need to be changed year-by-year. However, if I follow the guide on here and put fields I want to be ignored (listed by Schema name), they still show up on the copied record. I am wondering if I am doing this right or getting what I expect when I think "Ignore".

Should the fields I don't want to be cloned to the new record be put there? Should they be blank on the new record, as I would expect? Is it right to use the schema name? I tried just doing one field and it did not work, either.

Managed version of the package, used in D365 Online, version 8.2.

**Comment by amoedo** [comment]
Hi

Could you show a screenshot or just paste the text value that you are using on the list of fields to ignore?

In theory, if your list of fields to ignore is either a comma or semi colon separated list of schema names those fields should be ignored.

**Comment by vektastic** [comment]
You bet.

I create a workflow to copy the record of a conference and set up the rules per the tool:

![city](https://user-images.githubusercontent.com/19613018/33618393-0e20528c-d9a8-11e7-8f7d-02371c975d10.PNG)

I go to a record with that field filled in with data:

![record to clone](https://user-images.githubusercontent.com/19613018/33618574-888d03c6-d9a8-11e7-9053-2441c17d71a4.PNG)

And when I run the workflow, nothing is "ignored":

![copied conference](https://user-images.githubusercontent.com/19613018/33618598-997346f0-d9a8-11e7-9001-35c36bbd4069.PNG)

I tried this with multiple fields first and narrowed it down to just one here. Doesn't seem to ignore anything. Am I understanding "Ignore" right?

**Comment by demianrasko** [comment]
Hi vektastic, please try to add the "Fields to ignore" parameter in lowercase like "genoa_conferencity" and tell if that is ok.
If this works to you, I'll update the docs, and also I will update the code to be case insensitive.
Please tell me if that works.

thanks!

**Comment by demianrasko** [comment]
Thanks for the feedback and happy that worked ;)
maybe in next relaeses I can add these features.

Regards!

**Comment by demianrasko** [comment]
Included the lowercase by default in the last release - 1.0.47.0
