### ISSUE TITLE
Force Rollup Calculation - 

### ISSUE THREAD

**Issue by phamiltonwhitecapcanada** [demianrasko/Dynamics-365-Workflow-Tools#35]
Hi all,

I have installed the Dynamics-365-Workflow-Tools into our CRM online environment, but can't seem to get the "Force Rollup Calculation" workflow to work as I believe it should. I have a simple task, I want to store the sum of an attribute for a "child" entity in the parent entity (which is the Account entity in our case). I have the field in the Account entity created, "new_status_npd", which is a Rollup field of the sum of an attribute of a related entity (which is a custom Entity with a Whole Number attribute field). The new_status_npd rollup field is working and does recalculate, but like most people who use Rollups, I need the new_product_npd to update whenever one of the child records changes.

The task in the workflow is filled out with similar properties to the example provided with the toolkit, but...it doesn't update the parent field in a timely manner. 

I don't know if I have done something wrong with the Workflow task, or I have misunderstood what the workflow is supposed to do.

Again, I am relatively new to CRM, and the task of summing up values from related records is trivial in a programming environment, but I am trying to be "code free" for my solution. 

We are running the "July 2017 Update for Dynamics 365" version.  I have confirmed that the Rollup field is working properly as I can click the "Recalculate" button beside the "new_status_npd" attribute on the Account form in CRM, or...if I wait long enough, it will automatically update from the system jobs.

I have attached some screenshots of my workflow, and hopefully it is a simple thing to fix.

![applicationframehost_2017-12-06_08-11-41](https://user-images.githubusercontent.com/34282346/33663383-be2909a2-da5d-11e7-981c-879bc3cec36c.png)

![applicationframehost_2017-12-06_08-17-36](https://user-images.githubusercontent.com/34282346/33663460-0fa2c5f2-da5e-11e7-8b13-1fa582f6d4cb.png)

Thanks again for your awesome toolkit!  I hope we can get them working for my issue.

**Comment by demianrasko** [comment]
Hi phamiltonwhitecapcanada, I just tested it with the same scenario, and it worked fine.
You have an old version of the solution (1.0.37.0). Please try to download the last version of the solution from here: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/releases

**Comment by phamiltonwhitecapcanada** [comment]
Thanks Demian, I downloaded the latest version and the Rollup field is now calculating properly in CRM Online.  Now, I have another issue, we are using the new/free Portal feature for Dynamics, and the same Rollup form in the Portal doesn't seem to be displaying the updated information (but it does in CRM????).  I will open a ticket with Dynamics support as this is now a Portal issue.

Thanks again, these tools are great.

**Comment by demianrasko** [comment]
Hi, this could be an issue in the Portal, so the best wayt is to contact support.
thanks for your feedback.

Kind regards,
