### ISSUE TITLE
Statecode and Statuscode issue in Quote Detail Entity

### ISSUE THREAD

**Issue by chevy92** [demianrasko/Dynamics-365-Workflow-Tools#37]
### Expected behavior and actual behavior.
When I tried to clone Quote Detail records, statuscode code error appeared: 
![image](https://user-images.githubusercontent.com/22213188/33721608-de35deea-db67-11e7-8ad5-524c9a25fb39.png)
We found solution to ignore the error by putting in TRY-CATCH the update state of status and statecode in Clone Record method.

Guid createdGUID = service.Create(newEntity);
            tracingService.Trace("created cloned object OK");
            try
            {
                Entity record = service.Retrieve(entityName, createdGUID, new ColumnSet("statuscode", "statecode"));

                if (retrievedObject.Attributes["statuscode"] != record.Attributes["statuscode"] ||
                    retrievedObject.Attributes["statecode"] != record.Attributes["statecode"])
                {
                    Entity setStatusEnt = new Entity(entityName, createdGUID);
                    setStatusEnt.Attributes.Add("statuscode", retrievedObject.Attributes["statuscode"]);
                    setStatusEnt.Attributes.Add("statecode", retrievedObject.Attributes["statecode"]);

                    service.Update(setStatusEnt);
                }
            }
            catch (Exception)
            {

            }

Guid createdGUID = service.Create(newEntity);
            tracingService.Trace("created cloned object OK");
            try
            {
                Entity record = service.Retrieve(entityName, createdGUID, new ColumnSet("statuscode", "statecode"));

                if (retrievedObject.Attributes["statuscode"] != record.Attributes["statuscode"] ||
                    retrievedObject.Attributes["statecode"] != record.Attributes["statecode"])
                {
                    Entity setStatusEnt = new Entity(entityName, createdGUID);
                    setStatusEnt.Attributes.Add("statuscode", retrievedObject.Attributes["statuscode"]);
                    setStatusEnt.Attributes.Add("statecode", retrievedObject.Attributes["statecode"]);

                    service.Update(setStatusEnt);
                }
            }
            catch (Exception)
            {

            }
### CRM Version - online/onpremise - WorkflowTools version
We used last available version downloaded from GIT hub - Dynamics 365 and 2016

**Comment by demianrasko** [comment]
Hi chevy92,
I found the issue, and I fixed for all the cases.
you can download the new version working:
https://github.com/demianrasko/Dynamics-365-Workflow-Tools/releases/tag/1.0.47.1

I added a control to make it work for all entities without statuscode/statecode

Thanks for your feedback.
