### ISSUE TITLE
Associate Not Working

### ISSUE THREAD

**Issue by MattNC** [demianrasko/Dynamics-365-Workflow-Tools#4]
I installed version 1.0.38.0 and set up two different workflows to test the 'associate' method. It did not work in either one, with no error.
As an example of the attempt with a custom entity, I have attached two screenshots that show the Name and Relationship Entity Name of an N:N relationship between the Marketing List entity and a custom entity, and also to show the parameters I input in the workflow.
Any ideas?
![n_n_relationship](https://cloud.githubusercontent.com/assets/12701543/24820214/ed135fe0-1bb5-11e7-83f3-1db65f88b5ff.jpg)
![workflow_parameters](https://cloud.githubusercontent.com/assets/12701543/24820213/ed0d4330-1bb5-11e7-9d11-8f2498a28e7b.jpg)

**Comment by demianrasko** [comment]
Hi Matt, correct.
I found a bug, and I just ficed on the version 1.0.38.1.
Please go to Release and download this new version. 

Thanks for the feedback!

**Comment by MattNC** [comment]
Hi Demian: Thanks for the quick work! I can confirm that the 'associate' function is now working as I tested it with 1.0.39.0.

**Comment by demianrasko** [comment]
Thanks Matt!
