### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by NEHA12211** [demianrasko/Dynamics-365-Workflow-Tools#41]
Hi , 

#The deep link generated is not working on Android phone.It is only working on IOS.The generated link is showing as link on mail client of IOS.
In other mail clients, it is showing as text form.

### CRM Version - D365 8.2 - Onpremise
      WORKFLOW VERSION- Dynamics365WorkflowTools_1_0_46_0_8.2_managed

Could you please provide resolution on priority

**Comment by demianrasko** [comment]
Hi NEHA12211, on this action, I'm following this documentation: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/open-forms-views-dashboards-mobile-client-url and this one: https://msdn.microsoft.com/es-es/library/mt607595.aspx
Please check if the URL is correct, and if is working fine, maybe there is anything that changed on Android.

kind regards...
