### ISSUE TITLE
Business Process Error

### ISSUE THREAD

**Issue by DinethNipuna** [demianrasko/Dynamics-365-Workflow-Tools#43]
### Expected behavior and actual behavior.
When click on the save button, the workflow execute and change the status of the child record in another entity.
### Steps to reproduce the problem (screenshots are really usefull)
The workflow if executing, but I m getting this error. 
![image](https://user-images.githubusercontent.com/24534571/35370930-07205d50-01e5-11e8-9c9f-743660f11d14.png)

### CRM Version - online/onpremise - WorkflowTools version

Dynamics 365 online , Dynamics365WorkflowTools_1_0_48_2_8.2.zip

**Comment by demianrasko** [comment]
Hi DinethNipuna, I cannot determine the issue with these details.
Please share me CRM version (8.2, 9.0...), the fields types, values and entities you want to update, etc...
share with me also the tracing logs execution.
thanks!

**Comment by DinethNipuna** [comment]
Hi Demianrasko, Seems to be all good  now. I have used a wrong relationship.

Thanks.

**Comment by demianrasko** [comment]
Thanks for your update DinethNipuna!
