### ISSUE TITLE
Update Child Records - Option Sets bug?

### ISSUE THREAD

**Issue by asindiggler** [demianrasko/Dynamics-365-Workflow-Tools#44]
### Expected behavior and actual behavior.
Using "Update Child Record" to update the value of an option set. Can neither:
- change it to a specific value
- nor push the value for the same option set field from the parent record to the equivalent field in the child record.
### Steps to reproduce the problem (screenshots are really usefull)
Below is the current set-up my attempt to use Update Child Records, new_quotestatus is an option set, and that seems the problem, this doesn't seem to work with option sets.

I've checked to ensure the value I'm trying to update with is the same as the label and also tried using the value field from the option set. I tried updating another field to check I had got the first two fields correct (I had, it worked). I've also tried creating an equivalent option set in the parent record to try to push that through to the child records rather than explicitly setting the value. I've also tried to use a two-option field type (using No, "No" and 0) to no avail.  Is this a bug or am I not using this as intended?

I can use a text field as a work around, this is really just to report this an issue.

![image](https://user-images.githubusercontent.com/25305084/35391891-e6a9a908-01d7-11e8-8ca0-f4f099f36c12.png)

### CRM Version - online/onpremise - WorkflowTools version
Dynamics 365 - online - Dynamics365WorkflowTools_1_0_48_2_8.2

**Comment by demianrasko** [comment]
Hi asindiggler , 
please download the version 1.0.48.3. I just fixed this issue.
On the Value to Set parameter, you need to set the value in number, like "100000000" (not the string value).

thanks!
