### ISSUE TITLE
cannot upgrade sollution

### ISSUE THREAD

**Issue by mayulagoren** [demianrasko/Dynamics-365-Workflow-Tools#45]
Our environment is using Dynamics 365 Workflow Tools 1.0.35.0 but suddenly we receive errors
tried to import latest version but failed
Any help will be appreciated

  <Message>The plug-in execution failed because no Sandbox Hosts are currently available. Please check that you have a Sandbox server configured and that it is running.&amp;#13;&amp;#10;System.ServiceModel.EndpointNotFoundException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #95393350</Message>
  <Timestamp>2018-01-28T07:07:49.0535869Z</Timestamp>
  <ExceptionRetriable>false</ExceptionRetriable>
  <ExceptionSource i:nil="true" />
  <InnerFault>
    <ActivityId>ce809b5e-bc49-47d6-9e7f-79e11dd8bffa</ActivityId>
    <ErrorCode>-2147220970</ErrorCode>
    <ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
    <Message>Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.QueryValues]
[msdyncrmWorkflowTools (1.0.35.0): Query Values]

**Comment by demianrasko** [comment]
Please try to upgrade to last version, or give me more details about the error, to be able to identify if there is anything wrong.

thanks

**Comment by mayulagoren** [comment]
Thank u very much for your reply.
I tried to import latest version but the import failed. Is there a special
way to update existing sollution?

[image: תמונה מוטבעת 1]

בתאריך 28 בינו׳ 2018 16:23,‏ "Demian Adolfo Raschkovan" <
notifications@github.com> כתב:

**Comment by mayulagoren** [comment]
Any help available ?

2018-01-28 20:28 GMT+02:00 מאיה גורן <mayulagoren@gmail.com>:

**Comment by islanddog** [comment]
@mayulagoren - You have the error code in your previous message as 'The plug-in execution failed because no Sandbox Hosts are currently available. Please check that you have a Sandbox server configured and that it is running.'

I had the same issue today and was able to rectify the issue by doing the following for Dynamics CRM On Premise:

- On the server type **services.msc** and select Microsoft Dynamics CRM Asynchronous Processing Service and select Restart.

**Comment by demianrasko** [comment]
Hi, as isladdog said, please check the async service.
And try to update, if you have any error on update, try to remove the workflows, import, and re create the workflows again.

thanks!

**Comment by mayulagoren** [comment]
It helped !!
Thank u very much
Regards
Maya

2018-02-01 23:16 GMT+02:00 Christopher Soehnlein <notifications@github.com>:
