### ISSUE TITLE
Update Child Records Query

### ISSUE THREAD

**Issue by SeanKe11y** [demianrasko/Dynamics-365-Workflow-Tools#46]
Hi Demian,

I have a question about the "Update Child Records" tool. Can I include a condition so that it only attempts to write to open records?

e.g. I update a field on a contact and want to update all open child cases, or I update a field on an account and want to update all open child opportunities.

I performed a test for the first example above, it updated the first child case, then it failed at the second child case (which was resolved), then it hung and the remaining child cases didn't get updated. Is this expected behavior?

### Expected behavior
Would be that it skips records it cannot update, and actual behavior is that the workflow hangs when it reaches an uneditable record (it seems).

### Steps to reproduce the problem (screenshots are really usefull)
1. Created 1 contact with 4 open child cases
2. Ran workflow with Update Child Records and all 4 cases were updated.
3. Resolved the 2nd of the cases (looking at the database)
4. Ran workflow with Update Child Records and the 1st case was updated, then the workflow stayed in a Waiting state with the message "This case has already been resolved. Close and reopen the case record to see the updates." The remaining 2 open cases were not updated.
5. Reactivated the 2nd case and resolved the 3rd case.
6. Ran workflow with Update Child Records and the 1st and 2nd cases were updated, then the workflow stayed in a Waiting state with the message "This case has already been resolved. Close and reopen the case record to see the updates." The remaining 1 open case was not updated.

**Comment by demianrasko** [comment]
Hi SeanKe11y, 
I just addedd this feature in the last version, and you can see a new parameter con configure if you want to update all records, or only active ones: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Update%20Child%20Records.md

Hope this helps ;)

**Comment by SeanKe11y** [comment]
Hi Demian,

I've just tested and this is working perfectly, thanks very much.
