### ISSUE TITLE
Request for additional functionality: delete child records

### ISSUE THREAD

**Issue by asindiggler** [demianrasko/Dynamics-365-Workflow-Tools#48]
Hi,

Not a bug, just a request for some additional functionality. I think it's something you could do with a previous version of this solution.

I'd like to be able to delete all child records of a parent record without needing to delete the parent record itself. I could see a case for when a user might like to delete a subset of child records based on a query (which could be called using a combination of the field that identifies the parent record and a view perhaps?)

I do have a work around, a two option field in each child record that determines if the parent record requires it's child records to be deleted and then a bulk delete job that then deletes all of these child records based on that field. However, that has these records hanging around in the system for up to a week and further filtering on the child records in the goals that have been set-up to utilise them - not ideal.

I've not been able to find a solution for this elsewhere, if you are aware of one, please do let me know.

**Comment by fvakiliev** [comment]
Hi asindiggler!

Try to use [https://github.com/a33ik/UltimateWorkflowToolkit](url) - Distributed Workflow step.

OldCat

**Comment by demianrasko** [comment]
Hi asindiggler , 
thanks for your idea, I'll add it to possible future backlog.

regards,
