### ISSUE TITLE
Possible to Duplicate Subgrid Entries

### ISSUE THREAD

**Issue by islanddog** [demianrasko/Dynamics-365-Workflow-Tools#49]
I am utilizing msdyncrmWorkflowTools (1.0.48.2):Clone Record to Duplicate an Opportunity. I want to copy the custom sub-grid data as well. Is this possible? Best possible route to take?

-Thanks

**Comment by demianrasko** [comment]
Hi islanddog, 
thanks fot youe email, right now you must to find another way to do it...
regards.
