### ISSUE TITLE
Clone Children Workflow Failure - Cannot cast M:M to 1:M, even though both relationships are M:M

### ISSUE THREAD

**Issue by brf132** [demianrasko/Dynamics-365-Workflow-Tools#50]
### Expected behavior and actual behavior.
I followed the steps in the "Guide" provided here on Git, but I keep getting an error saying that I cannot cast a MM relationship to a 1M relationship.  Both relationships I am trying to use are MM.

I have a three entity setup.  Products (OOB) are M:M to Product Properties (Custom).  Product Properties are M:M to Customer Asset (OOB).  **Products are 1:M for Customer Asset (OOB relationship, on OOB records)** 

basically I am trying to pull the Product Properties that are associated with a Product, and clone them to the Customer Asset when it's created.  I am attempting to leverage the MM relationship between Products and Product Properties to tell the WF which child records to clone.

Error is as follows:

![image](https://user-images.githubusercontent.com/15112935/35705051-4b56d0dc-076f-11e8-8eb2-198bb520bd71.png)

Here is the config of the WF/Clone Children Step:
![image](https://user-images.githubusercontent.com/15112935/35705075-64ad593e-076f-11e8-99b6-c2039ddc8b86.png)

And here is the relationship I am using in this current iteration (using Product: Product Properties, MM, to locate the child records):
  
![image](https://user-images.githubusercontent.com/15112935/35705127-953fa318-076f-11e8-87af-eda483865d37.png)

I've also tried to use the relationship between Customer Asset and Product Properties, but that gives me the same failure.  Here is that relationship, but this would really be the 'target' relationship, not the 'source' relationship.
![image](https://user-images.githubusercontent.com/15112935/35705172-b0fd0078-076f-11e8-8d81-90299af0f4f4.png)

 
### Steps to reproduce the problem (screenshots are really usefull)
I believe I have provided all of this above.
### CRM Version - online/onpremise - WorkflowTools version
D365 - Version 1612 (9.0.0.3292) (DB 9.0.0.3292) online

**Comment by demianrasko** [comment]
Hi brf132, 
As you can see in the code, right now this feature only works for OneToManyRelationships.

Thanks,
