### ISSUE TITLE
Update child record : How 2 enter the optionset/picklist numbers 

### ISSUE THREAD

**Issue by HaraldM1** [demianrasko/Dynamics-365-Workflow-Tools#51]
Please help with correct entering the picklist numbers

I have a global picklist with 11 entries with numbers from 100.000.000 to 100.000.010.
In which field should I enter these numbers ?

### CRM 365 8.2 - online  - WorkflowTools 1.0.48.3

Errormessage : Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.UpdateChildRecords: System.InvalidCastException: Unable to cast object of type 'Microsoft.Xrm.Sdk.OptionSetValue' to type 'System.IConvertible'.

Thank You in advance,
Harald

**Comment by demianrasko** [comment]
Hi HaraldM1, 
please try to fill the numbers withot format like "100000000", "100000010".

Thanks!

**Comment by HaraldM1** [comment]
Thank You, but I got stuck.
Where in the form should I enter these values ?
Brgds. Harald
![image](https://user-images.githubusercontent.com/32194064/35773339-57fb2ff4-094f-11e8-8804-3075386225ec.png)

**Comment by islanddog** [comment]
@HaraldM1 - Pretty sure he is telling you to use - **"100000000", "100000010"** in the value to set field so it understands the required set. In your screen your **Value to Set** field is blank. Please inputting the recommendation data and use here for further reference: [https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Update%20Child%20Records.md](url)

**Comment by demianrasko** [comment]
Hi Harald, did it work? you closed and reopened the issue 2 times...

thanks

**Comment by HaraldM1** [comment]
Hi Demian,

 

thank you, now it works. I didn’t unterstand the method. But now I know, that I have to set for every option the value manually instead to fill in the parent field.

 

It’s a great tool, many thanks for develop this !!

 

Best regards, Harald

 

Harald u. Barbara Marchhart

3390 Melk ,   Spielbergerstr. 9

Tel.               0676 / 4285 333

Fax                  02752 / 52540

 

Von: Demian Adolfo Raschkovan [mailto:notifications@github.com] 
Gesendet: Sonntag, 11. Februar 2018 10:42
An: demianrasko/Dynamics-365-Workflow-Tools <Dynamics-365-Workflow-Tools@noreply.github.com>
Cc: HaraldM1 <marchhart@aon.at>; Mention <mention@noreply.github.com>
Betreff: Re: [demianrasko/Dynamics-365-Workflow-Tools] Update child record : How 2 enter the optionset/picklist numbers (#51)

 

Hi Harald, did it work? you closed and reopened the issue 2 times...

thanks

**Comment by demianrasko** [comment]
Hi Harald, 
Thats solution is just a workaround that works. But I just review again my code, and I found a bug on this situation, that I just solved.
Today I'm going to release a new version with this solved. I the next version you will be able to use the scenario you described on your firs message, using a parent field to map to the child record.

Thanks for pointing on this ;)
