### ISSUE TITLE
Associate Entity not creating expected relationship. 

### ISSUE THREAD

**Issue by jayrogers92** [demianrasko/Dynamics-365-Workflow-Tools#52]
I have an Entity set up called Web Page. I have a N:N relationship set up between Web Page and Web Page entity "dbc_adx_webpageadx_webpage_hottopics". 
When I create a Web Page, I want it to be linked to another Web Page.
On the WebPage I create, there is a field that holds the Web Page I want to create the N:N relationship with. 
The workflow is set up as below;
Relationship Name - dbc_adx_webpageadx_webpage_hottopics
Relationship Entity Name - dbc_adx_webpageadx_webpage_hottopics
Record URL - (DynamicURL of the Web Page I want to LINK TO)

Workflow is running as successful but the relationship isn't creating.

**Comment by demianrasko** [comment]
Hi jayrogers92, I just fixed this issue. 
It was because when you are trying to crear the association with the same entity type, it's required to set this: relationship.PrimaryEntityRole = EntityRole.Referencing;

This is going to be updated in my next relaase today.

Thanks for your help.
