### ISSUE TITLE
Entity Attachment To Email Can't  Fill Email's Parameter

### ISSUE THREAD

**Issue by chrisleeChina** [demianrasko/Dynamics-365-Workflow-Tools#55]
### Expected behavior and actual behavior.
when i fill the parameters,the parameter of Email( Email record to add all the Attachments)  can't look for like the step
![image](https://user-images.githubusercontent.com/36178495/36018447-bd99d700-0db6-11e8-8e85-a243ad7d805a.png)
### Steps to reproduce the problem (screenshots are really usefull)
1、
![image](https://user-images.githubusercontent.com/36178495/36018319-4b268420-0db6-11e8-9519-fdd1b3b989cf.png)

2、![image](https://user-images.githubusercontent.com/36178495/36018430-abe4b61a-0db6-11e8-940f-b192642d624b.png)

### CRM Version - online/onpremise - WorkflowTools version
CRM 2016 8.0 - onpremise-Dynamics CRM 2016 Workflow Tools 1.0.16.1

**Comment by demianrasko** [comment]
Hi chrisleeChina, 
the problem is the first step in your workflow.
You must use "Create record" (standard action) instead of "Send email" that you used.

![email create](https://user-images.githubusercontent.com/18124945/36077417-ef52d480-0f6a-11e8-9ce1-388157434bf2.gif)

**Comment by chrisleeChina** [comment]
Hi demianrasko,
it works.
create a draft email automatically.
Thx for your help very much.
