### ISSUE TITLE
Set Process Refresh

### ISSUE THREAD

**Issue by SeanKe11y** [demianrasko/Dynamics-365-Workflow-Tools#57]
Hi Demian,

This is an enhancement request for the SetProcess tool.

There is an out of the box SetProcess tool available that works in a similar way to your one. They both have an issue as opposed to say setting the active process via JavaScript.

When the process is set, the user has to refresh their screen in order to see that the business process flow has changed. I am using this in a real time workflow that triggers when a field on the record changes.

Would it be possible to include an optional switch to perform a form refresh after the process has been set?

I know this is not ideal but it is preferable to me than needing the user to remember to refresh the screen. This feature would be a real differentiator from the out of the box Action.

(It would be better if the new business process flow showed up immediately in a similar way to when it is changed manually from the ribbon at Process-->Switch Process, but I'm not sure if that would be possible...)

Thanks,
Sean

### CRM Version 8.2 - onpremise - WorkflowTools version 1.0.49.0

**Comment by demianrasko** [comment]
Hi Sean, 
is a good idea, but I cannot trigger a refresh (in Javascript) from the workflow.

kind regards,

**Comment by SeanKe11y** [comment]
Hi Demian, yes I thought as much, ended up triggering the refresh myself in JavaScript.
