### ISSUE TITLE
Update Child Record - not applying "Yes" (1)

### ISSUE THREAD

**Issue by tpickles1984** [demianrasko/Dynamics-365-Workflow-Tools#58]
Using Dynamics 365 8.2.2.160, Dynamics 365 Workflow Tools Solution 1.0.50.0

I set up a field on Opportunity: "Tax Applicable" (Boolean), and the same field on Opportunity Products. I used the "Update Child Records" workflow to update this value on the opportunity products, whenever the value changed on the opportunity. The "update only active child records" setting was set to no (update all records).

Strangely, the workflow works perfectly when updating the value to no (0), but does not work at all when setting the value to yes (1). I had this working and tested with version 1.0.48.1 of the tools, before the "update only active child records" flag was introduced. I wonder if this feature has had an adverse effect on functionality? I was able to resolve the issue by removing the solution, downgrading to 1.0.48.1, and then reinstating my workflow.

Many thanks for any help provided, this tool has been really invaluable to me 👍

**Comment by demianrasko** [comment]
Hi tpickles1984, 
on this I found a bug, just fixed today. I'm going to create an update on current release to fix it.

Thanks!

**Comment by demianrasko** [comment]
solved on version 1.0.50.1

thanks for your feedback.

**Comment by tpickles1984** [comment]
Thank you for looking in to it so quickly! Excellent work :-)
