### ISSUE TITLE
An error whyle performing workflow with rollup field

### ISSUE THREAD

**Issue by smallbirdru** [demianrasko/Dynamics-365-Workflow-Tools#6]
Hi, I've instaled your solution on the latest version of Dynamics 365.
When workflow starts I get the error:

Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.CalculateRollupField: System.Exception: 10013 sinto_meetings 93655fb3-6602-e711-80fe-5065f38a3bc1 1 При обращении в службу поддержки предоставьте технические сведения.

OR

that the entity doean't have paramentr "1" or "0"

I work with a custom entity and in realtime process
Please help :)

**Comment by demianrasko** [comment]
Hi smallbirdru, 
Are you trigger the workflow on the parent record or in the child record?
Please check that the field name is the name of the Calculated field on the parent record, and the record url is the url retrieved by the workflow of the parent record (as shown in the documentation: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Force%20Calculate%20Rollup%20Field.md)
could you share with me also a screenshot of the rollup field definition?

thanks!

**Comment by smallbirdru** [comment]
Hi there :)
I've performed the settings as it's shown in the manual.

I attach the screenshout with the settings.
I've got 2 entities:
meeting 1:N visitor
I create realtime workflow for the visitor, that should be perfotm just after a visitor record is created. Is means that I trigger rollup field recalculation in child record for the parent one.

For a case I also attache logfile.

Thank you in advance.
![pic1](https://cloud.githubusercontent.com/assets/27449522/25084564/e4cb5c72-2365-11e7-95a2-645741d7acb7.png)
[ErrorDetails (11).txt](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/files/925237/ErrorDetails.11.txt)

**Comment by demianrasko** [comment]
Hi, I just tested it again and for me is working fine on version 1612 (8.2.1.176) (DB 8.2.1.176) online.
- I created a custom entity called "Visitor"
- I created a Lookup field on "Visitor" to "Appointment" entity
- I created a Rollup field on Appointment called "Visitor count"
- I modified the Appointment form adding a subgrid with the visitors, and showing the "Visitor count" field
- Created a sync workflow using the Calculated Rollupf field action

Everything works in this situation...please check the images I share here if they helps, or give me some more details about your enviroment, the solution, or anything to try to reproduce your issue.

thanks
![image1](https://cloud.githubusercontent.com/assets/18124945/25303283/d62a63a0-274f-11e7-9abb-78fea4471fe7.png)
![image2](https://cloud.githubusercontent.com/assets/18124945/25303281/d62749cc-274f-11e7-8dc1-afacd5ac7eda.png)
![image3](https://cloud.githubusercontent.com/assets/18124945/25303282/d6275e62-274f-11e7-8165-cbdb19425d24.png)
