### ISSUE TITLE
JSON Parser error

### ISSUE THREAD

**Issue by fvakiliev** [demianrasko/Dynamics-365-Workflow-Tools#60]
I try to use JSON Parser step:
Json:
```
{
	"values": [
		{
			"Author": "Lisa Simpson",
			"Response Date": "2018-02-21T08:13:34.284Z"
		}
	],
	"SurveyId": "5114FA48-1DE6-E711-80E3-005056B37A5C"
}
```
Json path variants:

> - values[0].Author // Success: Lisa Simpson
> - values[0] // Error - Unhandled Exception: System.ArgumentException: Can not convert Object to String.
> - values // Error - Unhandled Exception: System.ArgumentException: Can not convert Array to String.
> - $ // Error - Unhandled Exception: System.ArgumentException: Can not convert Array to String.
> - values[0].Response Date // Error - Unhandled Exception: Newtonsoft.Json.JsonException: Unexpected character while parsing path:
> 

Please describe this...
Thanks!
OldCat

**Comment by demianrasko** [comment]
Hi OldCat, 
thaks for pointing this out. I just solved, I will be published today with a new release. 
Just one point, the last example you should put this JsonPath: 
values[0].['Response Date']

**Comment by fvakiliev** [comment]
Hi Demian!
Thank you! The errors I wrote about were corrected by you.
BUT a new one has appeared!
The program crashes if I request a non-existent key, but should simply not return anything. You should set response to empty string.
This issue must be reopened.

> values[0].Autho

Regards,
OldCat

**Comment by demianrasko** [comment]
Hi OldCat, solved in version 1.0.51.1.
If you pass an empty (or null) values, it returns the full original Json.
I'm using the "SelectToken" method from the Newtonsoft library, and this is the expected behavior with this.

Thanks!

**Comment by fvakiliev** [comment]
Hi Demian!

Let me disagree with you. This library (Newtonsoft) was not designed for the workflow step in its pure form. If the step ends with an error, then inside there is no possibility to analyze the presence of a tag with a certain key. And this is fundamentally important in the development of the workflow. Therefore, a query with a nonexistent key must be executed without any error and return an empty string or null value.

Regards,
OldCat

**Comment by fvakiliev** [comment]
Hi Demian!
Is there any news on my issue? It would be nice if the parser returned a predefined string in the absence of a result - for example, **"EMPTY"**.
Regards,
OldCat

**Comment by demianrasko** [comment]
Hi fvakiliev, 
I just solved it. I'll publish it on the next release 1.0.52.0 (hope today).

**Comment by fvakiliev** [comment]
Waiting cat... :)
