### ISSUE TITLE
Execute Workflow by ID - how to pass Record Id

### ISSUE THREAD

**Issue by Lafil** [demianrasko/Dynamics-365-Workflow-Tools#62]
### Steps to reproduce the problem (screenshots are really usefull)
I added a lookup Workflow Lookup to a custom Case Category entity pointing to workflow
I added lookup to Case Category in the Case entity
I created a synchronous on-demand workflow WFCC that creates a Task under the Case
I assigned workflow WFCC to Case Category X
I created a synchronous on-create workflow WFCase so that if Case's Case Category has a workflow assigned in its Workflow Lookup field, use that workflow on the Case.
So in ExecuteWorkflowby ID command:
Record Id = {Case(Case)} (which should by the case's Guid)
Process = {Workflow Lookup(Case Category (Case Category))}

I expect that for a Case pointing to Case Category X, it will create a Task under the Case on save.
Instead, I get
<Message>Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.Class.ExecuteWorkflowByID: System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).</Message>

The goal was to have certain Case Categories have certain automations without having a workflow with a series of If...Else If...Else If testing each possible Case Category that has a workflow associated to it.

Thanks in advance!

### CRM Version - online/onpremise - WorkflowTools version
CRM: 8.2.2 onpremise - WorkflowTools: 1_0_50_1_8.2

**Comment by demianrasko** [comment]
Hi Lafil, 
Yo need to retrieve the GUID as text, if you pass this value "{Case(Case)}" you don't retrieve the GUID.
I will create a new action to pass the recordURL, and to get the record typename and GUID as an output.
this will enable to to retrieve this GUID as text.
Hope to have it during this weekend.

thanks!

**Comment by Lafil** [comment]
Hi Demian!
I am not sure this is best approach.
If you create separate action to retrieve Guid from record, will I not have to have a field to store it in in order to invoke it in following Execute Workflow by Id action?

Perhaps best to have Execute Workflow recognize when we are passing entity primary key in Record Id and retrieve that Guid to apply workflow to?

Sorry typing this from phone without checking in CRM but I want to bring this to your attention before you spend time coding something :-)

Best regards,
Louis

On Feb 24, 2018 6:00 AM, Demian Adolfo Raschkovan <notifications@github.com> wrote:

Hi Lafil,
Yo need to retrieve the GUID as text, if you pass this value "{Case(Case)}" you don't retrieve the GUID.
I will create a new action to pass the recordURL, and to get the record typename and GUID as an output.
this will enable to to retrieve this GUID as text.
Hope to have it during this weekend.

thanks!

**Comment by demianrasko** [comment]
Thanks, 
You don't  need to store the string with the Id nowhere,  because you can use the output parameter of the action. 
No problem to code it,  because this action is useful to other activities too. 

Thanks!

**Comment by Lafil** [comment]
Hi Demian!

Got the updated solution this morning and amended my workflow to use the new Get Record Id action.
Works great!

Thanks for looking into this. I now have the potential to replace a heavy workflow with about a dozen “If… Else If” steps into a straightforward “Run the workflow associated to the category if there is one”.

Best,
Louis-Alain

De : Demian Adolfo Raschkovan [mailto:notifications@github.com]
Envoyé : 24 février 2018 10:59
À : demianrasko/Dynamics-365-Workflow-Tools <Dynamics-365-Workflow-Tools@noreply.github.com>
Cc : Lafil <lafil@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [demianrasko/Dynamics-365-Workflow-Tools] Execute Workflow by ID - how to pass Record Id (#62)


Thanks,
You don't need to store the string with the Id nowhere, because you can use the output parameter of the action.
No problem to code it, because this action is useful to other activities too.

Thanks!

**Comment by demianrasko** [comment]
Thanks Louis-Alain!!
