### ISSUE TITLE
Solution import error: Plugin Types import: FAILURE (System.Xml.XmlElement caused an exception)

### ISSUE THREAD

**Issue by donalmc** [demianrasko/Dynamics-365-Workflow-Tools#63]
### Expected behavior and actual behavior.
Trying to import the Dynamics365WorkflowTools_1_0_51_1_8.2_managed.zip into our production CRM fails and displays the below error.

Error Code: 0x80048012
Error Text:
Plugin Types import: FAILURE. Error: Plugin: msdyncrmWorkflowTools, Version=1.0.50.1, Culture=neutral, PublicKeyToken=416e876b9bee261e of PluginTypeName: Microsoft.Crm.Entities.PluginType and PluginTypeNode: System.Xml.XmlElement caused an 

### CRM Version - online/onpremise - WorkflowTools version
Dynamics 365, v8.2
Version 1612 (8.2.2.333) (DB 8.2.2.333) online

**Comment by demianrasko** [comment]
Hi donalmc, did already have the solution installed in your dev environment?
did you have a prevous version of the workflow tools?
do you have any workflow running using the workflow tools?

regards

**Comment by donalmc** [comment]
Hi Damian,

Yes - the solution is installed in our dev environment.

Yes - previously we had 1.0.38 installed. I updated dev to 1.0.50 last week. Before I went to import my own updated unmanaged solution, I tried to update production to 1.0.51 and this failed. I realized that I should update dev and installed 1.0.51 this morning and this blocked access to all solutions. I rolled back my sandbox to the backup before installing 1.0.51 and regained access to my solutions. Currently we have 1.0.38 installed on Production.

Yes - should I deactivate all workflows before updating?

Thank you for your time and your marvellous workflow tools.

**Comment by Aseasilverb** [comment]
Hi Demian, 

I am also experiencing this same import issue however I have not previously installed the solution in to my environment. DEV is currently 365 on premise with update 2.2

Any help or advice you can give would be greatly appreciated, this looks like a great solution and i'm excited to try it out!

Best wishes,

**Comment by Koenvdv** [comment]
Hi Demian,

I'm having the same issue as mentioned earlier.

Version: 1612 (8.2.1.176) (DB 8.2.1.176) On-premises.

I've tried importing the following versions of workflowtools:
- Dynamics365WorkflowTools_1_0_51_1_8.2_managed
- Dynamics365WorkflowTools_1_0_49_0_8.2_managed
- Dynamics365WorkflowTools_1_0_46_0_8.2_managed
- Dynamics365WorkflowTools_1_0_44_0_8.2_managed
- Dynamics365WorkflowTools_1_0_42_1_8.2_managed
- Dynamics365WorkflowTools_1_0_41_3_8.2_managed

**Hard error:**
<Data ss:Type="String">Plugin Types import: FAILURE. Error: Plugin: msdyncrmWorkflowTools, Version=1.0.51.1, Culture=neutral, PublicKeyToken=416e876b9bee261e of PluginTypeName: Microsoft.Crm.Entities.PluginType and PluginTypeNode: System.Xml.XmlElement caused an exception.</Data>

**Comment by demianrasko** [comment]
Hi all, 
I just trying to play and test for this issue, but cannot reproduce the error with the managed solution.
I just tried to import it on this version: versión 1612 (8.2.2.339) (DB 8.2.2.339) online
and I tried installed previous versions and with running workflows...and every time I try it it works fine.

Please share with me the logs files (if you are onprem) to see if we can get more details about the error.

thanks!

**Comment by Aseasilverb** [comment]
Hello,

Thank you for your email!

Our customer DEV environment (where we had the issue) had to be rolled back last week. Since then I have been able to import the corresponding version of your solution into it without issue.

It seems it may have been a problem related to the environment

We hope to go back to the later 2.2 version very soon and I will of course let you know should we have any further import issue and a log file to go with it.

Best wishes,

Alberta

**Comment by Koenvdv** [comment]
Hi Demian,

Added the logfile for (8.2.1.176) (DB 8.2.1.176) on-premises


[importlog_Dynamics365WorkflowTools_1_0_51_1.zip](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/files/1874854/importlog_Dynamics365WorkflowTools_1_0_51_1.zip)

**Comment by Koenvdv** [comment]
Hi Demian, any update on this issue?

**Comment by demianrasko** [comment]
sorry for the delay...hard days organizing the Dynamics Saturday in Madrid. Will see it this weekend.

thanks

**Comment by demianrasko** [comment]
Hi MohitMdd, 
Maybe you need to follow this answer from Microsoft suuport to othernoe in the community: https://community.dynamics.com/crm/f/117/t/208497

remove it, and then reimport it...

thanks!

**Comment by Koenvdv** [comment]
Hi Demian,

I don't see how that provides an answer to my issue :)
