### ISSUE TITLE
Send Email To Team

### ISSUE THREAD

**Issue by DynamicsLMP** [demianrasko/Dynamics-365-Workflow-Tools#64]
Hi,

Thank you for this Dynamics-365-Workflow-Tools. Sent To Team is working when I manually create the Email and send it to the Team Queue. When I create the Email from a Workflow it doesn't send the email. It is stuck on Draft status and is not able to send to Team Members. When I select "Send Email" on the workflow, the Send to Team was not able to change the receiver from the team queue to team members.

I hope you consider to add this to your future update. This will help lot of people. 
Thanks

**Comment by demianrasko** [comment]
thanks, I'll put it on the list...
You have all the code open sourced, so maybe if you have developer knowledge you can develop and send a pull request and include it to the solution ;)
