### ISSUE TITLE
Error Message in process

### ISSUE THREAD

**Issue by BandowM** [demianrasko/Dynamics-365-Workflow-Tools#65]
### Steps to reproduce the problem (screenshots are really usefull)

Since round about 6 month we sent our Mails by select them in the queue and send more mails at the same time. Since 3 weeks we have that issue that this process runs to the status 'wait' with following error message:

Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.Class.SendEmail]
[msdyncrmWorkflowTools (1.0.51.1): Send Email]
Load CRM Service from context --- OK

Error Message:

Unhandled Exception: Microsoft.Crm.CrmException: There is no active transaction. This error is usually caused by custom plug-ins that ignore errors from service calls and continue processing.
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.Execute(IExecutionContext context)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)

![image](https://user-images.githubusercontent.com/30173687/37079805-2bba9f62-21e4-11e8-82f0-eb3fa9bbb0e7.png)

### CRM Version - online/onpremise - WorkflowTools version

CRM online - Version 1612

**Comment by demianrasko** [comment]
Did you change this workflow from async to sync?
did you updated the CRM online environment?

**Comment by demianrasko** [comment]
Hi BandowM, do you still have this issue?

**Comment by BandowM** [comment]
Hi demianrasko, thanks for asking. No we don´t have this issue anymore.
