### ISSUE TITLE
Attach to mail

### ISSUE THREAD

**Issue by GoSoli** [demianrasko/Dynamics-365-Workflow-Tools#66]
Hi Damian,
This is a following issue to 53.
Now I could test the function in detail and noticed that it only seemed to work.
The original file lines from the attachment of the appointment are copied but all files have no size, so they are not usable.
I attach a screenshot of the original record (appointment) and the new record (email).
WorkflowTools version 1.0.51.1
![image](https://user-images.githubusercontent.com/36201081/37083073-aa7d25fe-21ee-11e8-9693-cb8f87960e11.png)
![image](https://user-images.githubusercontent.com/36201081/37083126-dc50d6de-21ee-11e8-81bc-9621702676a6.png)

**Comment by demianrasko** [comment]
is this a sync or async workflow?
does the user has all the rights to do this action?
send me more details about your environment.

thanks

**Comment by GoSoli** [comment]
Hi Demian,
it is a sync workflow which reacts on the change of a field in the appointment. I tested with a user with admin rights. In the workflow I create an email record, add the recipients and add the attachment with your function.
Our CRM test environment is a simple installation where everything is on the same server (CRM, database). In the live environment I have the same behavior.

Thanks for help

**Comment by demianrasko** [comment]
Hi GoSoli, 
solved today and will published with the next release (hopefully today) 1.0.52.0.

kind regards!
