### ISSUE TITLE
String Functions missing validation.

### ISSUE THREAD

**Issue by irah2008** [demianrasko/Dynamics-365-Workflow-Tools#67]
###Used string function to truncate the lead topic to 50 characters.

**Comment by irah2008** [comment]
Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.StringFunctions]
[msdyncrmWorkflowTools (1.0.33.0): String Functions]

Load CRM Service from context --- OK



Error Message:

Unhandled Exception: Microsoft.Crm.CrmException: Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.StringFunctions: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.Execute(IExecutionContext context)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)

**Comment by demianrasko** [comment]
thanks!
I'll check this issue...

regards

**Comment by demianrasko** [comment]
Hi irah2008, 
this issue is solved in my next release 1.0.52.0.

thanks!
