### ISSUE TITLE
Associate Entity Doesn't Work

### ISSUE THREAD

**Issue by MicioGatto** [demianrasko/Dynamics-365-Workflow-Tools#7]
Hi, 

I'm trying to use the Associate Entity option but it doesn't create an association.  The workflow executes correctly and displays no errors.  Do you have any suggestions as to why this might not be working?

![image](https://cloud.githubusercontent.com/assets/20626721/25336975/c22555ba-28f1-11e7-9627-f1bf0fcf4ed0.png)

![image](https://cloud.githubusercontent.com/assets/20626721/25336916/7a687306-28f1-11e7-8c05-e7bf0be9f493.png)

![image](https://cloud.githubusercontent.com/assets/20626721/25336939/95756924-28f1-11e7-8454-24619d4311f4.png)

**Comment by demianrasko** [comment]
Hi MicioGatto, 
please explain me the type of relationships you have, the names of the two entities, and I can check.
Please also chck that the parameters are ok following the tdetails explained here: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Associate%20Entity.md

regards

**Comment by MicioGatto** [comment]
Thanks for your reply.

The two entities are called "rs_support" and "rs_issue".  There is an N:N relationship between them.

**Support:**
![image](https://cloud.githubusercontent.com/assets/20626721/25803046/127a429a-33ed-11e7-83da-f797bb4bac9b.png)

**Issue:**
![image](https://cloud.githubusercontent.com/assets/20626721/25803093/3a95ff76-33ed-11e7-8b37-48a7d5d10c50.png)

**The relationship parameters are as follows:**
![image](https://cloud.githubusercontent.com/assets/20626721/25802981/c225f154-33ec-11e7-8512-f888e91c10e1.png)


The relationship name is "rs_support_issue".
The relationship Entity Name is "rs_rs_support_rs_issue".

These are then the values that I entered as parameters in the workflow.

The workflow runs when the rs_support entity is created:
![image](https://cloud.githubusercontent.com/assets/20626721/25802913/6dbff7ea-33ec-11e7-8d7f-637ce6167a48.png)

The update statement in the workflow just adds text to a field to show that the workflow executed.
The associate entity step parameters are as follows:
![image](https://cloud.githubusercontent.com/assets/20626721/25802959/a90c6f2c-33ec-11e7-88c9-c09c0d1b9355.png)

Is there any other information that I can provide?

**Comment by demianrasko** [comment]
Hi, 
I see that you have the version number 1.0.37.0.
I fixed an issue in a newer version:
1.0.38.1: Bug Fixed on AssociateEntity. (you can see it in the commit change log)

Please update the version and it should work fine ;)

**Comment by MicioGatto** [comment]
Thanks Demian, that's fixed it.

Also, thank you so much for these tools.  They've been vital for keeping our solutions simple but powerful.

**Comment by demianrasko** [comment]
Thanks MicioGatto!!

kind regards!
