### ISSUE TITLE
Update Child Records: How to use the actual record as value to be set

### ISSUE THREAD

**Issue by thomasBID** [demianrasko/Dynamics-365-Workflow-Tools#70]
Hi Damian,

please help me on #47: I want to walk through all sub accounts and set the customized lookup field [new_companygroupid] with the actual account which in this case is the parent account.

In Update Child Records some things are very clear:
- Parent Record URL = {Record URL (Dynamic)(Account)}
- Relationship Name = account_parent_account
- Child Field Name to Update = new_companygroupid

But how can I use the "actual account" as value to be set? All I tried went wrong.

I use Dynamics 2016  / 8.1.0.395, Workflow Tools 1.0.51.1

**Comment by demianrasko** [comment]
I think I didn't test it with lookups fields.
maybe you can:
1) try to pass the account in the value to set.
2) create a string field on children, where you change any field, and then create another workflow in ths child on update of this field, and there you can update this custom lookup

thanks

**Comment by thomasBID** [comment]
Hi Demian,

many thanks for your reply.

To pass the account in the value to set doesn't work, I tried it. And the workaround with an additional field to trigger workflows is not the way I want.

Perhaps you will test the function with lookups in the next days? That would be great.

Best regards, Thomas

**Comment by rbeste** [comment]
Running into same issue.  Can't cast a string as an entityreference.  Any progress on getting this to work?

**Comment by PKgg** [comment]
Hi Demian, 

These are the parameters that I'm passing:

Parent Record URL |  {Record URL(Dynamic)(Property/Account)} |
Relationship Name | lead_parent_record
Parent Field Name |   
Value to Set | Test
Child Field Name to Update | Address1_City
Update only Active |True

I am getting the following message;

"The requested record was not found or you do not have sufficient permissions to view it."

Could not find attribute for entity with objecttypecode: 4 , entity id: dc6574cb-92ce-446c-a5d6-885a75107d52

Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.UpdateChildRecords]
[msdyncrmWorkflowTools (1.0.51.1): Update Child Records]
Load CRM Service from context --- OK
ObjectTypeCode=1--ParentId=3518a12b-b95d-490b-89f7-e28c268c1074
RelationshipName=lead_parent_account--_ParentFieldNameToUpdate=
_ValueToSet=Test--_ChildFieldNameToUpdate=Address1_City


Error Message:

Unhandled Exception: Microsoft.Crm.CrmException: Could not find attribute for entity with objecttypecode: 4 , entity id: dc6574cb-92ce-446c-a5d6-885a75107d52
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.Execute(IExecutionContext context)
   at Microsoft.Crm.Sandbox.SandboxCustomActivity.Execute(IServiceProvider serviceProvider)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)

I have tried a number of different options, but I can't get this to work. Any idea what would cause this?

**Comment by donalmc** [comment]
I hope Demien does not mind me suggesting this solution for lookups.
I was unable to ever populate lookups via a string until I found another solution called TCS Tools.
This works brilliantly with Dynamics 365 Workflow Tools.

**Comment by demianrasko** [comment]
Hi all, I'll add this to my backlog to include a string field on parent to fill a child lookups records.

thanks for the idea...

**Comment by thomasBID** [comment]
Hi Demian,
do you have an idea until when you can provide a working solution for this? I Need it :-)
Many thanks in advance, Thomas
