### ISSUE TITLE
Provide a function to start a workflow for each child record

### ISSUE THREAD

**Issue by thomasBID** [demianrasko/Dynamics-365-Workflow-Tools#71]
Hi Damian,

please could you provide a function to start a workflow for each child record?
This would be great in complex situations, where "Update Child Records" is not sufficient enough.

Many thanks in advance.

**Comment by demianrasko** [comment]
thanks, another one for the backlog that is growing.
you can also try to develop by your own, and make a pull request to this project and share with the community... ;)

thanks

**Comment by thomasBID** [comment]
Believe me, nobody wants my code - I'm not a developer :-)
It would be great if this could be done by somebody experienced.
