### ISSUE TITLE
Associate Entity Clarification

### ISSUE THREAD

**Issue by lynn-fisher** [demianrasko/Dynamics-365-Workflow-Tools#75]
I have an N:N relationship between the 'salesorderdetail' entity and a custom entity I create called 'Authorisation Environmental Conditions'. 

I have found a plugin that allows me to query an entity and return a recordset and loop though the list of records and do something as a result. (see screenshotbelow).

![image1](https://user-images.githubusercontent.com/34034697/38781070-95f1a600-40cf-11e8-9fb5-5617abd145e6.png)

Within the loop I am creating a  'Authorisation Environmental Conditions' record which I then want to assoicate with the salesorderdetail entity. It is at this point, within the loop, that I have to tried do the association using  'associate entity', but I am not longer in the primary entity and cant get it to work. 

![image2](https://user-images.githubusercontent.com/34034697/38781224-67ba42c2-40d1-11e8-8ab2-3154c16cc2ae.png)

Will it be possible to use your 'Associate entity' within the loop or is it only possible on Primary entity that triggers the workflow? Do I only need to do it once or twice? One for the association of one entity and once for the association of the other?

I am using Dynamics 365 Version 1612 (9.0.1.733) (DB 9.0.1.733) 

Many thanks for your time in advance

**Comment by demianrasko** [comment]
Hi lynn-fisher, right now this is not possible.

kind regards,
