### ISSUE TITLE
Update Child Records missing input field

### ISSUE THREAD

**Issue by mickey4nay** [demianrasko/Dynamics-365-Workflow-Tools#77]
### Expected behavior and actual behavior.
We receive the following error when using the Update Child records function.
![image](https://user-images.githubusercontent.com/13772864/39017035-12e17f4e-441a-11e8-9714-5b0728fd4e90.png)
It appears to be missing the "Update only Actual" field 
![image](https://user-images.githubusercontent.com/13772864/39017052-25d72c84-441a-11e8-9788-fd3e24b2bd43.png)

### CRM Version - online/onpremise - WorkflowTools version
We are on 1.0.51.1 upgraded from 1.0.37.0

**Comment by demianrasko** [comment]
Hi mickey4nay , 
as you can see on my documentation: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Update%20Child%20Records.md
there is a new bool parameter Called "Update only Active" to set if you want to update all children records, or only the active ones.
Please update the step in the workflow, or try to re-create it.

thanks!

**Comment by mickey4nay** [comment]
Hi
I notice in our version we have that field missing for some reason. Big thank you for responding to my question

Kind regards
Michael Nunes

On 2 May 2018, at 19:40, Demian Adolfo Raschkovan <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #77<https://github.com/demianrasko/Dynamics-365-Workflow-Tools/issues/77>.

**Comment by mickey4nay** [comment]
Hi
Just revisiting this again.  On a new environment I can see that the Update Child Record Active flag field exists but in the dev environment it does not even so I have performed an update to the latest version.  How can the old 1.37 manged solution version be removed and a fresh new update performed
