### ISSUE TITLE
Clone Record and Childs

### ISSUE THREAD

**Issue by Roxxinger** [demianrasko/Dynamics-365-Workflow-Tools#78]
Hi,

is it possible to Clone a record and then clone children from the source record to the clone record? Don't know what to insert in the Target Record URL field.

Thanks,
Jan

**Comment by demianrasko** [comment]
Hi Roxxinger,
the answer is yes. 
there are two different actions, one to clone the current record, (Clone Record) and another one to Clone Children. you have the documentation here: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Clone%20Children.md

regards

**Comment by zeusfaber** [comment]
Will it work if we put the Record ID to the Target Record URL field? It asks for URL, not for the Record ID
![image](https://user-images.githubusercontent.com/45037384/60434234-566df500-9c0f-11e9-9453-d871fa20c313.png)
