### ISSUE TITLE
34 Set Process Stage error

### ISSUE THREAD

**Issue by shentz** [demianrasko/Dynamics-365-Workflow-Tools#8]
Hello

Microsoft just upgraded us to Dynamics 365 (13 May 2017) and function 34 (set process stage) no longer works. Error is below. Could it be that the new Dynamics no longer lets you "jump steps" in a process, without properly completing earlier steps? (the error seems to focus on: _To move to the next stage, complete the required steps)_.

With thanks
James

Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: An error occurred while trying to update Business Process to Case Id = 5d4531d6-123a-e711-810a-70106fa7b0a1Exception message To move to the next stage, complete the required steps. Inner exception: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: To move to the next stage, complete the required steps. (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault).Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>efa59f4e-9abd-416b-99ca-9a95f5d2b2ea</ActivityId>
  <ErrorCode>-2147220891</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
  <Message>An error occurred while trying to update Business Process to Case Id = 5d4531d6-123a-e711-810a-70106fa7b0a1Exception message To move to the next stage, complete the required steps. Inner exception: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: To move to the next stage, complete the required steps. (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault).</Message>
  <Timestamp>2017-05-16T09:20:23.4057879Z</Timestamp>
  <ExceptionRetriable>false</ExceptionRetriable>
  <ExceptionSource i:nil="true" />
  <InnerFault>
    <ActivityId>efa59f4e-9abd-416b-99ca-9a95f5d2b2ea</ActivityId>
    <ErrorCode>-2147220970</ErrorCode>
    <ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
    <Message>Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.Class.SetProcessStage]
[msdyncrmWorkflowTools (1.0.37.0): Set Process Stage]

Load CRM Service from context --- OK
ObjectTypeCode=3--ParentId=5d4531d6-123a-e711-810a-70106fa7b0a1
[Dynamics.ChangeBPFandPhase.Execute] Process stage: Awaiting Fact Find
[Dynamics.ChangeBPFandPhase.Execute] Fetching the requested Stage.
[Dynamics.ChangeBPFandPhase.Execute] Case tu update Id = 5d4531d6-123a-e711-810a-70106fa7b0a1, Name = 
[Dynamics.ChangeBPFandPhase.Execute] Updating  Case to Update Id = 5d4531d6-123a-e711-810a-70106fa7b0a1 Process Id = 14224ab2-df39-4b6d-a6cc-b60eaaf1ff58 | Process Name =  Stage Id = d1ca2a40-562b-30c0-d530-3a914865ad2c
[Dynamics.ChangeBPFandPhase.Execute] Error while setting the active BPF. Details: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: To move to the next stage, complete the required steps. (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault).

Error Message:

Unhandled Exception: Microsoft.Crm.CrmException: An error occurred while trying to update Business Process to Case Id = 5d4531d6-123a-e711-810a-70106fa7b0a1Exception message To move to the next stage, complete the required steps. Inner exception: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: To move to the next stage, complete the required steps. (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault).
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.Execute(IExecutionContext context)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
</Message>
    <Timestamp>2017-05-16T09:20:23.4057879Z</Timestamp>
    <ExceptionRetriable>false</ExceptionRetriable>
    <ExceptionSource i:nil="true" />
    <InnerFault i:nil="true" />
    <OriginalException i:nil="true" />
    <TraceText i:nil="true" />
  </InnerFault>
  <OriginalException i:nil="true" />
  <TraceText i:nil="true" />
</OrganizationServiceFault>

**Comment by demianrasko** [comment]
Hi shentz, sorry for the delay in my answer.
The error I see "To move to the next stage, complete the required steps" show me that you have some required fields in previuos phases to be filled before to move to next stage.
Try to complete these fields, and try it againg, and if you need to automate it, you can update it in previous step in the workflow.

thanks!

**Comment by demianrasko** [comment]
And I just tested it again with the standard BPF for Opportunities, and Works fine in my environment with this versión:

Microsoft Dynamics 365  versiÃ³n 1612 (8.2.1.271) (DB 8.2.1.271) online

thanks!
