### ISSUE TITLE
All failing with 'Context' error after online update .180

### ISSUE THREAD

**Issue by rbeste** [demianrasko/Dynamics-365-Workflow-Tools#80]
Microsoft Dynamics 365 
Version 1612 (9.0.2.180) (DB 9.0.2.180) online 
since this update last night (4/30/18)  the update child records, force recalculate and email to team functions all fail with an error of 'context'.  The logs simply all say that the workflow in question using one of your routines failed with an error of 'context'.  So, something changed in the SDK in that most recent release that your code is not accounting for.  Any ideas???  Everything was working well until this update and now taking out your routines is just not really an option without writing a lot of replacement code or reengineering how we're doing all of these things.  Any guidance would be great.

**Comment by demianrasko** [comment]
Hi rbeste, 
right now I didn't test the solution with 9.0.2.
My dev environment is still 8.2, but I'm working to update it to 9.0, and stop supportting 8.x versions.

thanks!

**Comment by rbeste** [comment]
Any ETA on updating it? It was working for 9.0.2.54 as of Monday but fails with the update to 9.0.2.180.



Thanks,

Ray Beste
630-566-7342


-------- Original message --------

**Comment by demianrasko** [comment]
Not sure, 
If this is the case,  probably you can open case with Microsoft support. 
All the source code is available on github if you need to test anything there faster. 
Thanks

**Comment by rbeste** [comment]
Demian,

I heard from Microsoft today and they admitted that it was actually a bug in v .180 and not the code. They pushed out a fix and your code and ours now works as is.

Thought you would like to know.



Thanks,

Ray Beste
630-566-7342


-------- Original message --------

**Comment by demianrasko** [comment]
Thanks for the answer and sharing!! 

Regards!
