### ISSUE TITLE
Clone Children tool not working

### ISSUE THREAD

**Issue by MagnusNorlem** [demianrasko/Dynamics-365-Workflow-Tools#81]
Dear Community ... help would be appreciated, since I'm on a customer project where we need this feature:

I've created a new entity "Requirements" with a lookup to Opportunity. The idea is that when a user creates an Opportunity, a prepopulated list of 10 Requirements should be copied to the Opportunity from a template Opportunity.

I've found Demians workflow tool but cannot get the Clone Children to work:
https://github.com/demianrasko/Dynamics-365-Workflow-Tools/blob/master/docs/Clone%20Children.md

I assume/understand that this workflow should do the job and I'm desparately looking for a person, who have managed to make this feature work (I'm on CRM Online on a brand new 9.0.2 trial).

/Magnus

Here are the parametres used in the workflow: https://imgur.com/a/3wF4OS3
![bvsxtij](https://user-images.githubusercontent.com/38916790/39528902-a9869eb0-4e25-11e8-83cf-41e66b466113.jpg)

**Comment by demianrasko** [comment]
Hi MagnusNorlem, 
it should work, but right now I didn't check it on 9.0.2, please check the "New Parent Field Name" (is empty)
My dev enviroment is still 8.2, and I will change it in the next few weeks to 9.x.

thanks

**Comment by MagnusNorlem** [comment]
Hi Demian,
We assume you have suggested us to fill in the "New Parent Field Name" - so we have tried this (so we put "wik_Opportunity" in both fields). If we do this, then the workflows throws an error (and it is actually the only way we get a reaction from the workflow) ... below you see the error - we hope it helps you in debugging - and if you get a updated 9.0.2 version of you tool, we hope the clone children will work.

_> Plugin Trace:
> 
> [msdyncrmWorkflowTools: msdyncrmWorkflowTools.CloneChildren]
> [msdyncrmWorkflowTools (1.0.51.1): Clone Children]
> 
> Load CRM Service from context --- OK
> ObjectTypeCode=3--ParentId=a0d3b91a-5a41-e811-a94e-000d3a391893
> ObjectTypeCode=3--ParentId=14f6dcf6-6441-e811-a94e-000d3a391893
> 
> 
> 
> Error Message:
> 
> Unhandled Exception: Microsoft.Crm.CrmException: Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.CloneChildren: System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
>    at Microsoft.Crm.Sandbox.SandboxCodeUnit.Execute(IExecutionContext context)
>    at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)
>    at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
>_

**Comment by meghanareed** [comment]
@demianrasko - were you able to replicate this issue? having the same problem and looking to use the tool. Thanks!
