### ISSUE TITLE
Set Process Stage not working in Real-Time Workflows

### ISSUE THREAD

**Issue by KentHar** [demianrasko/Dynamics-365-Workflow-Tools#82]
I am on Dynamics 365 on premise v 8.2.

I am calling an on demand workflow from the Business Process Flow - on entry to a stage.

The workflow that contains the Set Process Stage plugin will simply not fire, no error messages are flared.

If I change the same workflow to run in the background, the process works as expected, however I need this to run in real-time to update the UI for the users.

**Comment by demianrasko** [comment]
On this action I just updating the main entity on the fields called "processid" and "stageid", maybe I need to change to the new 8.x methods to move next and previous.

thanks
