### ISSUE TITLE
Add new type of Value for Calculations Rollup Functions

### ISSUE THREAD

**Issue by DynamicsResources** [demianrasko/Dynamics-365-Workflow-Tools#84]
### Expected behavior and actual behavior.
Want to rollap Date and Time Atribute type
### Steps to reproduce the problem (screenshots are really usefull)
Right now Rollup Function has possibilities to use Money and INT field types
### CRM Version - online/onpremise - WorkflowTools version
Microsoft Dynamics 365
Version 1612 (8.2.2.1559) (DB 8.2.2.1559) online
msdyncrmWorkflowTools (1.0.40.0):Rollup Functions

**Comment by demianrasko** [comment]
Thanks, I shoud include it in my backlog.

regards
