### ISSUE TITLE
 Entity Attachment to Email - Error When from Attachment

### ISSUE THREAD

**Issue by GoSoli** [demianrasko/Dynamics-365-Workflow-Tools#88]
Hi Demain,
I have now installed 1.0.52.0 but still no success to attach a document from attachments (not notes).
Even when no document is attached in the appointment I get the error message
'ActivityMimeAttachment' entity doesn't contain attribute with Name = 'createdon'
ErrorDetails is attached 
[ErrorDetails - ActivityMimeAttachment.txt](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/files/2053126/ErrorDetails.-.ActivityMimeAttachment.txt)

Detail in Workflow
![image](https://user-images.githubusercontent.com/36201081/40709659-f4730b3e-63f6-11e8-9532-06088cf799d8.png)

Can you solve this problem?
CRM version 8.2.2

Thanks in advance
Gottfried

**Comment by demianrasko** [comment]
Fixed on my next release, hope to be 1.0.52.1.

thanks!
