### ISSUE TITLE
Associate Lead to Parent Contact

### ISSUE THREAD

**Issue by findleybc** [demianrasko/Dynamics-365-Workflow-Tools#9]
Can I use Associate Entity in a Lead workflow to set the Parent contact of a lead? I am able to get the Record URL of the Contact I want to reference using Query Values. Using that Record URL, does Associate Entity work for 1:N parent relationship or is there another way of doing this?

**Comment by demianrasko** [comment]
Hi findleybc, The associate action is only for N-N relationship creation.
regards,
