### ISSUE TITLE
Query Values - Returning Lookup GUID

### ISSUE THREAD

**Issue by SeanKe11y** [demianrasko/Dynamics-365-Workflow-Tools#90]
Hi Demian,

I have a quick question. I'm calling the Query Values step which I'm using to return a lookup field from another CRM record as an attribute, new_contactid is the attribute name. This seems to be returning "Microsoft.Xrm.Sdk.EntityReference" I was hoping it would return the GUID of the contact so that I could compare against the result of "Get Record ID" that I am also using in the workflow.

My question is, is there a way using Dynamics-365-Workflow-Tools to easily get the GUID of a lookup field on another CRM record? (I can't use Get Record ID as I need to apply 2 filters to my query and I don't think I can use Query Values to return the "Record URL (Dynamic)"...)

### CRM Version - online/onpremise - WorkflowTools version
CRM V8.2 Online, Workflow Tool 1.0.51.1

**Comment by jagovier** [comment]
In the optionset the same thing happens. Can you return the int?

**Comment by wingzeroaa** [comment]
yes, it is same for the optionset.
It returns Microsoft.Xrm.Sdk.OptionSetValue
I need the int

Anyone can help?

**Comment by demianrasko** [comment]
Solved today. will be deployed in the next version 1.0.53.0 during this weekend. 
Thanks!
