### ISSUE TITLE
Clone Record Issue

### ISSUE THREAD

**Issue by amback00** [demianrasko/Dynamics-365-Workflow-Tools#91]
### Expected behavior and actual behavior.
Clone Record issue: I am unable to see the Output parameters input screen as indicated in the instructions. It seems that many steps are missing in the instructions that show how to get to the Output parameters screen.

### Steps to reproduce the problem (screenshots are really usefull)
Unable to show screen shots as I am unable to get to the Output parameters screen.

### CRM Version - online/onpremise - WorkflowTools version
CRM Version: Dynamics 365 Version 9.0 
Workflow Tools version; 1_0_52_1_8.2

**Comment by leibishr** [comment]
I am experiencing this same issue.
At first when running the workflow with the input parameters, i would get an error stating that it is a duplicate record. so i remove the prefix and i got  null reference error which i cannot view.

**Comment by demianrasko** [comment]
Solved today few issues with this. will be deployed in the next version 1.0.53.0 during this weekend. 

also, please check if there is any alternated key that could cause the duplicate deetection error.

Thanks!
