### ISSUE TITLE
Roll Up Field to Be Recalculated Error

### ISSUE THREAD

**Issue by LeeMather** [demianrasko/Dynamics-365-Workflow-Tools#94]
### Roll Up Field to Be Recalculated

I'm using the plug in
![image](https://user-images.githubusercontent.com/41200877/43137027-7d41ddfc-8f42-11e8-9de8-a5367d2a658f.png)

but am getting the following error

![image](https://user-images.githubusercontent.com/41200877/43136864-df9159ca-8f41-11e8-87d4-311349a71a14.png)

Even tho the field exists

![image](https://user-images.githubusercontent.com/41200877/43136926-19130248-8f42-11e8-9f67-539d718c0118.png)

CRM v9 Online 1.52

**Comment by demianrasko** [comment]
Not sure why is happening, I just using here this function: https://docs.microsoft.com/en-us/dotnet/api/microsoft.crm.sdk.messages.calculaterollupfieldrequest?view=dynamics-general-ce-9
