### ISSUE TITLE
Entity Mobile Deep Link Hyperlink Issue after V9 Update

### ISSUE THREAD

**Issue by grantjohanson** [demianrasko/Dynamics-365-Workflow-Tools#95]
PREFACE:  Based on the testing below we've already completed, this seems like it might be on the Microsoft side.  I am asking the question here to see if, on the off chance, @demianrasko or anyone else using the Entity Mobile Deep Link to do something similar has run into the same issue and has a viable solution.  

Problem Description:

After updating D365 Online to v9 (specifically release 9.0.2.0758), we found that the Mobile Deep Links we have embedded as hyperlinks in an e-mail generated from workflow are now dead and do not have an actual web address behind them (just a #).

Prior to the upgrade, this functionality worked as expected and we were able to send an e-mail with a hyperlink that pointed to the mobile deep link and opened the app on the phone.  I looked back through the version release history and it does not appear that this has been specifically addressed in the releases past our current installed version.  

Steps to reproduce the problem (screenshots in linked docx file):

[Entity Mobile Deep Link Hyperlink Testing.docx](https://github.com/demianrasko/Dynamics-365-Workflow-Tools/files/2233613/Entity.Mobile.Deep.Link.Hyperlink.Testing.docx)

Ran a plugin trace - found that plugin is executing as expected and produces a viable deep link to the record in question.  Verified by copying and pasting the url generated from the plugin trace and sending it to myself manually as a hyperlink.  Opened up the app on the phone as expected to the expected record.

Tried to recreate the hyperlink in the workflow step.  Found that when trying to use dynamic values from the Get Mobile Deep Link function that fired in step 1 of the workflow to populate the URL field of the hyperlink in the workflow e-mail, CRM returns a null value instead of a reference when the hyperlink windows is close and it tries to insert the resultant HTML into the e-mail.  

However, that null value in and of itself may be a red herring because when just adding a reference to one of the Mobile Deep Link fields into body of the e-mail without the hyperlink, it shows up successfully in the e-mail sent from CRM.  

We have hyperlinks for both the web and phone app versions of the software in this e-mail..  The weblink continues to work as expected.  

Is there a known issue with deep links not resolving upon generation of the actual e-mail in version 9? 

I couldn't find anyone talking about this yet in any of the community posts and information on mobile deep linking seems generally scarce.  Hoping someone else is running into this or that @demianrasko can ask the person who contributed to the deep link tool to see if they can replicate the issue.  

CRM Version - online- 9.0.2.0758

WorkflowTools version - 1.0.42.1

**Comment by grantjohanson** [comment]
One additional test performed to confirm my suspicion that this is a Microsoft issue.  Hard coded the deep link into the hyperlink in the workflow-generated e-mail.  Same result, the deep links no longer resolve as hyperlinks when server side sync generates the actual e-mail.  I'll post this in the community boards as well to see if it gets a response.

**Comment by demianrasko** [comment]
I should work as expected here: https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/open-forms-views-dashboards-mobile-client-url

**Comment by grantjohanson** [comment]
Thanks Demian!  We’ll test it out

Grant Johanson
843-480-1854



On Fri, Dec 14, 2018 at 6:38 PM -0600, "Demian Adolfo Raschkovan" <notifications@github.com<mailto:notifications@github.com>> wrote:


I should work as expected here: https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/open-forms-views-dashboards-mobile-client-url

**Comment by CPow123** [comment]
The link above states how to hardcode the url into an email but I can't seem to utilize the Get Mobile Deep Link feature of the WF Tools to dynamically set this for each form submission. 

Our requirement is to include hyperlinks to both the web app as well as the mobile App (Dynamics 365). This would give our users the ability to click the mobile app link and launch the Dynamics 365 app OR click the web app to open in a web browser.

Has anyone successfully used Get Mobile Deep Link in V9 yet?
