### ISSUE TITLE
Set Process Stage - Failed for Cross-Entity BPF

### ISSUE THREAD

**Issue by vijayygr** [demianrasko/Dynamics-365-Workflow-Tools#98]
### Expected behavior and actual behavior.
I have a cross-entity Business Process Flow which starts on Opportunity and end on Quote entity.
Set Process Stage works very fine if the Stage movement is only on Opportunity. It should work even when move from Opportunity to Quote stage. But is failed with the following error:

An error occurred while trying to update Business Process to Case Id = 35375bd4-faa3-e811-81c3-005056b5a975Exception message Invalid cross-entity stage transition. Target entity must be specified. Inner exception: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Invalid cross-entity stage transition. Target entity must be specified. (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault). | An error occurred while trying to update Business Process to Case Id = 35375bd4-faa3-e811-81c3-005056b5a975Exception message Invalid cross-entity stage transition. Target entity must be specified. Inner exception: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Invalid cross-entity stage transition. Target entity must be specified. (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault). | An error occurred while trying to update Business Process to Case Id = 35375bd4-faa3-e811-81c3-005056b5a975Exception message Invalid cross-entity stage transition. Target entity must be specified. Inner exception: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Invalid cross-entity stage transition. Target entity must be specified. (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault).
-- | -- | --
An error occurred while trying to update Business Process to Case Id = 35375bd4-faa3-e811-81c3-005056b5a975Exception message Invalid cross-entity stage transition. Target entity must be specified. Inner exception: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Invalid cross-entity stage transition. Target entity must be specified. (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault). | An error occurred while trying to update Business Process to Case Id = 35375bd4-faa3-e811-81c3-005056b5a975Exception message Invalid cross-entity stage transition. Target entity must be specified. Inner exception: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Invalid cross-entity stage transition. Target entity must be specified. (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault).
An error occurred while trying to update Business Process to Case Id = 35375bd4-faa3-e811-81c3-005056b5a975Exception message Invalid cross-entity stage transition. Target entity must be specified. Inner exception: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Invalid cross-entity stage transition. Target entity must be specified. (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault).

### Steps to reproduce the problem (screenshots are really usefull)
Created workflow using Set Process Stage from this solution, it gives error when move a stage that jumps from Opportunity to Quote. 
### CRM Version - online/onpremise - WorkflowTools version
Dynamics 365 onpremise (8.2.2.112)

**Comment by sutibun-w** [comment]
I cannot get mine to change stage either this is what I have configured but I dont know if this is correct for on prem. I am running the same version of on prem. Does the settings look correct, sorry I am not very experienced with CRM.

![image](https://user-images.githubusercontent.com/43276924/45563181-77d92e00-b801-11e8-953b-c8bbc8f111a5.png) 

![image](https://user-images.githubusercontent.com/43276924/45563405-16658f00-b802-11e8-8fc2-4627aae0fdc8.png)

**Comment by demianrasko** [comment]
Solved today. It should be solved because I changed from an entity processstage focus to a process instance approach now.
will be deployed in the next version 1.0.53.0 during this weekend. 
Thanks!
